<?php
// Batch 7: Lessons 927-967 (Third Intro, Possessive, Prepositions, Demonstratives, Linking Words, Midterm 4)
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
use App\Models\PronunciationExercise;
use App\Models\Lesson;

$data = [
    927 => ['s1'=>'Welcome to stage three. You will now learn about possessives, prepositions, demonstratives, and linking words to build more complex sentences.','s2'=>'Stage three takes your English from basic to intermediate level.','s3'=>'Every new concept builds on what you already know.','pe'=>'مرحباً بالمرحلة الثالثة — هتتعلم الملكية وحروف الجر وأسماء الإشارة وكلمات الربط.','se'=>'كل مفهوم جديد يبني على اللي تعرفه أصلاً.','v'=>json_encode([['word'=>'possessive','pronunciation'=>'/pəˈzes.ɪv/','meaning_ar'=>'ملكية'],['word'=>'preposition','pronunciation'=>'/ˌprep.əˈzɪʃ.ən/','meaning_ar'=>'حرف جر'],['word'=>'demonstrative','pronunciation'=>'/dɪˈmɒn.strə.tɪv/','meaning_ar'=>'إشاري'],['word'=>'complex','pronunciation'=>'/ˈkɒm.pleks/','meaning_ar'=>'معقد'],['word'=>'concept','pronunciation'=>'/ˈkɒn.sept/','meaning_ar'=>'مفهوم'],['word'=>'intermediate','pronunciation'=>'/ˌɪn.tərˈmiː.di.ət/','meaning_ar'=>'متوسط'],['word'=>'basic','pronunciation'=>'/ˈbeɪ.sɪk/','meaning_ar'=>'أساسي'],['word'=>'build','pronunciation'=>'/bɪld/','meaning_ar'=>'يبني'],['word'=>'already','pronunciation'=>'/ɔːlˈred.i/','meaning_ar'=>'بالفعل'],['word'=>'welcome','pronunciation'=>'/ˈwel.kəm/','meaning_ar'=>'مرحباً']])],
    928 => ['s1'=>'The curriculum for stage three includes possessive adjectives and pronouns, prepositions of place and time, this that these those, and linking words like however and therefore.','s2'=>'Follow the lessons in order for the best learning experience.','s3'=>'You are building a strong foundation for advanced English.','pe'=>'منهج المرحلة الثالثة يشمل الملكية وحروف الجر وأسماء الإشارة وكلمات الربط.','se'=>'أنت تبني أساس قوي للإنجليزي المتقدم.','v'=>json_encode([['word'=>'curriculum','pronunciation'=>'/kəˈrɪk.jə.ləm/','meaning_ar'=>'منهج'],['word'=>'adjective','pronunciation'=>'/ˈædʒ.ɪk.tɪv/','meaning_ar'=>'صفة'],['word'=>'pronoun','pronunciation'=>'/ˈproʊ.naʊn/','meaning_ar'=>'ضمير'],['word'=>'however','pronunciation'=>'/haʊˈev.ər/','meaning_ar'=>'ومع ذلك'],['word'=>'therefore','pronunciation'=>'/ˈðer.fɔːr/','meaning_ar'=>'لذلك'],['word'=>'experience','pronunciation'=>'/ɪkˈspɪr.i.əns/','meaning_ar'=>'تجربة'],['word'=>'strong','pronunciation'=>'/strɒŋ/','meaning_ar'=>'قوي'],['word'=>'foundation','pronunciation'=>'/faʊnˈdeɪ.ʃən/','meaning_ar'=>'أساس'],['word'=>'advanced','pronunciation'=>'/ədˈvænst/','meaning_ar'=>'متقدم'],['word'=>'include','pronunciation'=>'/ɪnˈkluːd/','meaning_ar'=>'يشمل']])],
    929 => ['s1'=>'Possessive adjectives show who owns something. My book, your pen, his car, her bag, its color, our house, their school.','s2'=>'Possessive adjectives come before the noun they describe.','s3'=>'This is my phone. That is her laptop. Those are their keys.','pe'=>'صفات الملكية توضح لمن الشيء: my, your, his, her, its, our, their.','se'=>'هذا تلفوني. ذاك لابتوبها. ذيك مفاتيحهم.','v'=>json_encode([['word'=>'my','pronunciation'=>'/maɪ/','meaning_ar'=>'لي / خاصتي'],['word'=>'your','pronunciation'=>'/jɔːr/','meaning_ar'=>'لك / خاصتك'],['word'=>'his','pronunciation'=>'/hɪz/','meaning_ar'=>'له / خاصته'],['word'=>'her','pronunciation'=>'/hɜːr/','meaning_ar'=>'لها / خاصتها'],['word'=>'its','pronunciation'=>'/ɪts/','meaning_ar'=>'له (لغير العاقل)'],['word'=>'our','pronunciation'=>'/aʊər/','meaning_ar'=>'لنا / خاصتنا'],['word'=>'their','pronunciation'=>'/ðer/','meaning_ar'=>'لهم / خاصتهم'],['word'=>'phone','pronunciation'=>'/foʊn/','meaning_ar'=>'هاتف'],['word'=>'laptop','pronunciation'=>'/ˈlæp.tɒp/','meaning_ar'=>'لابتوب'],['word'=>'keys','pronunciation'=>'/kiːz/','meaning_ar'=>'مفاتيح']])],
    930 => ['s1'=>'Possessive pronouns replace a noun with ownership. This book is mine. That pen is yours. The car is his. The bag is hers. The house is ours. The school is theirs.','s2'=>'Mine, yours, his, hers, ours, and theirs stand alone without a noun.','s3'=>'Is this yours? No, it is not mine. It must be theirs.','pe'=>'ضمائر الملكية تحل محل الاسم مع الملكية: mine, yours, his, hers, ours, theirs.','se'=>'هذا لك؟ لا، مش لي. لازم يكون لهم.','v'=>json_encode([['word'=>'mine','pronunciation'=>'/maɪn/','meaning_ar'=>'لي'],['word'=>'yours','pronunciation'=>'/jɔːrz/','meaning_ar'=>'لك'],['word'=>'hers','pronunciation'=>'/hɜːrz/','meaning_ar'=>'لها'],['word'=>'ours','pronunciation'=>'/aʊərz/','meaning_ar'=>'لنا'],['word'=>'theirs','pronunciation'=>'/ðerz/','meaning_ar'=>'لهم'],['word'=>'alone','pronunciation'=>'/əˈloʊn/','meaning_ar'=>'وحده'],['word'=>'stand','pronunciation'=>'/stænd/','meaning_ar'=>'يقف'],['word'=>'without','pronunciation'=>'/wɪˈðaʊt/','meaning_ar'=>'بدون'],['word'=>'must','pronunciation'=>'/mʌst/','meaning_ar'=>'لازم'],['word'=>'replace','pronunciation'=>'/rɪˈpleɪs/','meaning_ar'=>'يستبدل']])],
    933 => ['s1'=>'Prepositions of place tell us where something is. The cat is on the table. The ball is under the chair. The book is between the cups.','s2'=>'In, on, at, under, above, below, beside, between, behind, and in front of are all prepositions of place.','s3'=>'The picture is above the bed and the shoes are under it.','pe'=>'حروف الجر المكانية توضح وين الشيء: on, under, between, behind, in front of.','se'=>'الصورة فوق السرير والأحذية تحته.','v'=>json_encode([['word'=>'on','pronunciation'=>'/ɒn/','meaning_ar'=>'على'],['word'=>'under','pronunciation'=>'/ˈʌn.dər/','meaning_ar'=>'تحت'],['word'=>'above','pronunciation'=>'/əˈbʌv/','meaning_ar'=>'فوق'],['word'=>'below','pronunciation'=>'/bɪˈloʊ/','meaning_ar'=>'أسفل'],['word'=>'beside','pronunciation'=>'/bɪˈsaɪd/','meaning_ar'=>'بجانب'],['word'=>'between','pronunciation'=>'/bɪˈtwiːn/','meaning_ar'=>'بين'],['word'=>'behind','pronunciation'=>'/bɪˈhaɪnd/','meaning_ar'=>'خلف'],['word'=>'chair','pronunciation'=>'/tʃer/','meaning_ar'=>'كرسي'],['word'=>'picture','pronunciation'=>'/ˈpɪk.tʃər/','meaning_ar'=>'صورة'],['word'=>'bed','pronunciation'=>'/bed/','meaning_ar'=>'سرير']])],
    934 => ['s1'=>'Prepositions of time tell us when something happens. I wake up at seven. She was born in May. We have class on Monday.','s2'=>'Use at for specific times, in for months and years, on for days and dates.','s3'=>'At noon, in the morning, on Friday, in winter, at midnight.','pe'=>'حروف الجر الزمانية: at للأوقات المحددة، in للشهور والسنين، on للأيام والتواريخ.','se'=>'في الظهر، في الصباح، يوم الجمعة، في الشتاء، في منتصف الليل.','v'=>json_encode([['word'=>'at','pronunciation'=>'/æt/','meaning_ar'=>'في (وقت محدد)'],['word'=>'in','pronunciation'=>'/ɪn/','meaning_ar'=>'في (شهر/سنة)'],['word'=>'on','pronunciation'=>'/ɒn/','meaning_ar'=>'في (يوم/تاريخ)'],['word'=>'born','pronunciation'=>'/bɔːrn/','meaning_ar'=>'وُلد'],['word'=>'noon','pronunciation'=>'/nuːn/','meaning_ar'=>'ظهر'],['word'=>'midnight','pronunciation'=>'/ˈmɪd.naɪt/','meaning_ar'=>'منتصف الليل'],['word'=>'morning','pronunciation'=>'/ˈmɔːr.nɪŋ/','meaning_ar'=>'صباح'],['word'=>'winter','pronunciation'=>'/ˈwɪn.tər/','meaning_ar'=>'شتاء'],['word'=>'Friday','pronunciation'=>'/ˈfraɪ.deɪ/','meaning_ar'=>'الجمعة'],['word'=>'May','pronunciation'=>'/meɪ/','meaning_ar'=>'مايو']])],
    937 => ['s1'=>'This and that refer to singular nouns. These and those refer to plural nouns. This book is mine. That car is old. These apples are fresh. Those houses are big.','s2'=>'This and these are for things near you. That and those are for things far away.','s3'=>'This is my pen. That is your bag over there.','pe'=>'this/that للمفرد، these/those للجمع. this/these للقريب، that/those للبعيد.','se'=>'هذا قلمي. ذاك شنطتك هناك.','v'=>json_encode([['word'=>'this','pronunciation'=>'/ðɪs/','meaning_ar'=>'هذا / هذه'],['word'=>'that','pronunciation'=>'/ðæt/','meaning_ar'=>'ذلك / تلك'],['word'=>'these','pronunciation'=>'/ðiːz/','meaning_ar'=>'هؤلاء / هذه (جمع)'],['word'=>'those','pronunciation'=>'/ðoʊz/','meaning_ar'=>'أولئك / تلك (جمع)'],['word'=>'near','pronunciation'=>'/nɪr/','meaning_ar'=>'قريب'],['word'=>'far','pronunciation'=>'/fɑːr/','meaning_ar'=>'بعيد'],['word'=>'fresh','pronunciation'=>'/freʃ/','meaning_ar'=>'طازج'],['word'=>'old','pronunciation'=>'/oʊld/','meaning_ar'=>'قديم'],['word'=>'over there','pronunciation'=>'/ˈoʊ.vər ðer/','meaning_ar'=>'هناك'],['word'=>'refer','pronunciation'=>'/rɪˈfɜːr/','meaning_ar'=>'يشير إلى']])],
    940 => ['s1'=>'Linking words connect ideas in sentences and paragraphs. And adds information. But shows contrast. So shows result. Because shows reason.','s2'=>'I studied hard, so I passed the exam. She is tired, but she keeps working.','s3'=>'Linking words make your writing and speaking smoother and more organized.','pe'=>'كلمات الربط تربط الأفكار: and للإضافة، but للتناقض، so للنتيجة، because للسبب.','se'=>'كلمات الربط تخلي كتابتك وكلامك أسلس وأكثر تنظيم.','v'=>json_encode([['word'=>'and','pronunciation'=>'/ænd/','meaning_ar'=>'و'],['word'=>'but','pronunciation'=>'/bʌt/','meaning_ar'=>'لكن'],['word'=>'so','pronunciation'=>'/soʊ/','meaning_ar'=>'لذلك'],['word'=>'because','pronunciation'=>'/bɪˈkɒz/','meaning_ar'=>'لأن'],['word'=>'contrast','pronunciation'=>'/ˈkɒn.træst/','meaning_ar'=>'تناقض'],['word'=>'result','pronunciation'=>'/rɪˈzʌlt/','meaning_ar'=>'نتيجة'],['word'=>'reason','pronunciation'=>'/ˈriː.zən/','meaning_ar'=>'سبب'],['word'=>'paragraph','pronunciation'=>'/ˈpær.ə.ɡræf/','meaning_ar'=>'فقرة'],['word'=>'organized','pronunciation'=>'/ˈɔːr.ɡən.aɪzd/','meaning_ar'=>'منظم'],['word'=>'studied','pronunciation'=>'/ˈstʌd.id/','meaning_ar'=>'درس']])],
    941 => ['s1'=>'However, moreover, furthermore, and therefore are formal linking words. However shows contrast. Moreover adds information. Therefore shows a logical result.','s2'=>'She was tired; however, she finished the project on time.','s3'=>'He studied hard; therefore, he got the highest score.','pe'=>'however تعارض، moreover تضيف، furthermore تزيد، therefore نتيجة منطقية.','se'=>'درس بجد، لذلك حصل على أعلى درجة.','v'=>json_encode([['word'=>'however','pronunciation'=>'/haʊˈev.ər/','meaning_ar'=>'ومع ذلك'],['word'=>'moreover','pronunciation'=>'/mɔːrˈoʊ.vər/','meaning_ar'=>'علاوة على ذلك'],['word'=>'furthermore','pronunciation'=>'/ˌfɜːr.ðərˈmɔːr/','meaning_ar'=>'فضلاً عن ذلك'],['word'=>'therefore','pronunciation'=>'/ˈðer.fɔːr/','meaning_ar'=>'لذلك'],['word'=>'formal','pronunciation'=>'/ˈfɔːr.məl/','meaning_ar'=>'رسمي'],['word'=>'logical','pronunciation'=>'/ˈlɒdʒ.ɪ.kəl/','meaning_ar'=>'منطقي'],['word'=>'project','pronunciation'=>'/ˈprɒdʒ.ekt/','meaning_ar'=>'مشروع'],['word'=>'finished','pronunciation'=>'/ˈfɪn.ɪʃt/','meaning_ar'=>'أنهى'],['word'=>'highest','pronunciation'=>'/ˈhaɪ.ɪst/','meaning_ar'=>'أعلى'],['word'=>'score','pronunciation'=>'/skɔːr/','meaning_ar'=>'درجة']])],
    967 => ['s1'=>'Welcome to the fourth midterm. This test covers possessives, prepositions, demonstratives, and linking words. You are halfway through the course!','s2'=>'Review all the grammar rules from stage three carefully.','s3'=>'Believe in your abilities and give it your best effort.','pe'=>'مرحباً بالاختبار النصفي الرابع — يغطي الملكية وحروف الجر وأسماء الإشارة وكلمات الربط.','se'=>'ثق في قدراتك واعطها أفضل مجهود.','v'=>json_encode([['word'=>'halfway','pronunciation'=>'/ˌhæfˈweɪ/','meaning_ar'=>'في المنتصف'],['word'=>'through','pronunciation'=>'/θruː/','meaning_ar'=>'خلال'],['word'=>'abilities','pronunciation'=>'/əˈbɪl.ə.tiz/','meaning_ar'=>'قدرات'],['word'=>'effort','pronunciation'=>'/ˈef.ərt/','meaning_ar'=>'مجهود'],['word'=>'grammar','pronunciation'=>'/ˈɡræm.ər/','meaning_ar'=>'قواعد'],['word'=>'carefully','pronunciation'=>'/ˈker.fə.li/','meaning_ar'=>'بعناية'],['word'=>'believe','pronunciation'=>'/bɪˈliːv/','meaning_ar'=>'يؤمن'],['word'=>'review','pronunciation'=>'/rɪˈvjuː/','meaning_ar'=>'يراجع'],['word'=>'test','pronunciation'=>'/test/','meaning_ar'=>'اختبار'],['word'=>'course','pronunciation'=>'/kɔːrs/','meaning_ar'=>'دورة / كورس']])],
];

$created = 0; $updated = 0; $skipped = 0;
foreach ($data as $lid => $c) {
    $lesson = Lesson::find($lid);
    if (!$lesson) { echo "SKIP:{$lid}\n"; $skipped++; continue; }
    $lesson->update(['has_pronunciation_exercise' => true]);
    $ex = PronunciationExercise::where('lesson_id', $lid)->first();
    $d = ['lesson_id'=>$lid,'sentence_1'=>$c['s1'],'sentence_2'=>$c['s2'],'sentence_3'=>$c['s3'],
          'vocabulary_json'=>$c['v'],'passage_explanation'=>$c['pe'],
          'sentence_explanation'=>$c['se'],'passing_score'=>60,'max_duration_seconds'=>30,'allow_retake'=>true];
    if ($ex) { $ex->update($d); echo "UPD:{$lid}\n"; $updated++; }
    else { PronunciationExercise::create($d); echo "NEW:{$lid}\n"; $created++; }
}
echo "\n=== BATCH 7 DONE === C:{$created} U:{$updated} S:{$skipped}\n";
