<?php
// Batch 2: Lessons 814-837 (Numbers + Parts of Speech + Midterm 1)
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

use App\Models\PronunciationExercise;
use App\Models\Lesson;

$data = [
    814 => [
        'sentence_1' => 'The numbers one, two, three, four, and five are the first group. We use numbers every day to count things around us.',
        'sentence_2' => 'I have three books and two pens on my desk.',
        'sentence_3' => 'Counting from one to five is the first step in learning numbers.',
        'passage_explanation' => 'المجموعة الأولى من الأرقام: 1 إلى 5 — نستخدم الأرقام يومياً لعد الأشياء حولنا.',
        'sentence_explanation' => 'العد من 1 لـ 5 هو أول خطوة في تعلم الأرقام.',
        'vocabulary_json' => json_encode([
            ['word' => 'one', 'pronunciation' => '/wʌn/', 'meaning_ar' => 'واحد'],
            ['word' => 'two', 'pronunciation' => '/tuː/', 'meaning_ar' => 'اثنان'],
            ['word' => 'three', 'pronunciation' => '/θriː/', 'meaning_ar' => 'ثلاثة'],
            ['word' => 'four', 'pronunciation' => '/fɔːr/', 'meaning_ar' => 'أربعة'],
            ['word' => 'five', 'pronunciation' => '/faɪv/', 'meaning_ar' => 'خمسة'],
            ['word' => 'number', 'pronunciation' => '/ˈnʌm.bər/', 'meaning_ar' => 'رقم'],
            ['word' => 'count', 'pronunciation' => '/kaʊnt/', 'meaning_ar' => 'يعدّ'],
            ['word' => 'group', 'pronunciation' => '/ɡruːp/', 'meaning_ar' => 'مجموعة'],
            ['word' => 'desk', 'pronunciation' => '/desk/', 'meaning_ar' => 'مكتب'],
            ['word' => 'around', 'pronunciation' => '/əˈraʊnd/', 'meaning_ar' => 'حول'],
        ]),
    ],
    815 => [
        'sentence_1' => 'The second group of numbers includes six, seven, eight, nine, and ten. These numbers are used in phone numbers and addresses.',
        'sentence_2' => 'My phone number has ten digits.',
        'sentence_3' => 'Can you count from six to ten without stopping?',
        'passage_explanation' => 'المجموعة الثانية: 6 إلى 10 — نستخدمها في أرقام الهواتف والعناوين.',
        'sentence_explanation' => 'تقدر تعد من 6 لـ 10 بدون ما توقف؟',
        'vocabulary_json' => json_encode([
            ['word' => 'six', 'pronunciation' => '/sɪks/', 'meaning_ar' => 'ستة'],
            ['word' => 'seven', 'pronunciation' => '/ˈsev.ən/', 'meaning_ar' => 'سبعة'],
            ['word' => 'eight', 'pronunciation' => '/eɪt/', 'meaning_ar' => 'ثمانية'],
            ['word' => 'nine', 'pronunciation' => '/naɪn/', 'meaning_ar' => 'تسعة'],
            ['word' => 'ten', 'pronunciation' => '/ten/', 'meaning_ar' => 'عشرة'],
            ['word' => 'include', 'pronunciation' => '/ɪnˈkluːd/', 'meaning_ar' => 'يشمل'],
            ['word' => 'phone', 'pronunciation' => '/foʊn/', 'meaning_ar' => 'هاتف'],
            ['word' => 'address', 'pronunciation' => '/əˈdres/', 'meaning_ar' => 'عنوان'],
            ['word' => 'digit', 'pronunciation' => '/ˈdɪdʒ.ɪt/', 'meaning_ar' => 'رقم / خانة'],
            ['word' => 'stopping', 'pronunciation' => '/ˈstɒp.ɪŋ/', 'meaning_ar' => 'توقف'],
        ]),
    ],
    816 => [
        'sentence_1' => 'Eleven, twelve, thirteen, fourteen, and fifteen make up the third group. Notice that thirteen, fourteen, and fifteen end with teen.',
        'sentence_2' => 'She is thirteen years old and her brother is fifteen.',
        'sentence_3' => 'Numbers ending in teen are called the teens.',
        'passage_explanation' => 'المجموعة الثالثة: 11 إلى 15 — لاحظ إن 13 و14 و15 تنتهي بـ teen.',
        'sentence_explanation' => 'الأرقام اللي تنتهي بـ teen اسمها الـ teens.',
        'vocabulary_json' => json_encode([
            ['word' => 'eleven', 'pronunciation' => '/ɪˈlev.ən/', 'meaning_ar' => 'أحد عشر'],
            ['word' => 'twelve', 'pronunciation' => '/twelv/', 'meaning_ar' => 'اثنا عشر'],
            ['word' => 'thirteen', 'pronunciation' => '/ˌθɜːrˈtiːn/', 'meaning_ar' => 'ثلاثة عشر'],
            ['word' => 'fourteen', 'pronunciation' => '/ˌfɔːrˈtiːn/', 'meaning_ar' => 'أربعة عشر'],
            ['word' => 'fifteen', 'pronunciation' => '/ˌfɪfˈtiːn/', 'meaning_ar' => 'خمسة عشر'],
            ['word' => 'notice', 'pronunciation' => '/ˈnoʊ.tɪs/', 'meaning_ar' => 'يلاحظ'],
            ['word' => 'year', 'pronunciation' => '/jɪr/', 'meaning_ar' => 'سنة'],
            ['word' => 'old', 'pronunciation' => '/oʊld/', 'meaning_ar' => 'عُمر / قديم'],
            ['word' => 'brother', 'pronunciation' => '/ˈbrʌð.ər/', 'meaning_ar' => 'أخ'],
            ['word' => 'called', 'pronunciation' => '/kɔːld/', 'meaning_ar' => 'يُسمى'],
        ]),
    ],
    817 => [
        'sentence_1' => 'Sixteen, seventeen, eighteen, nineteen, and twenty complete the teens and start the twenties. Twenty is the first number with two syllables.',
        'sentence_2' => 'There are twenty students in our classroom.',
        'sentence_3' => 'After nineteen comes twenty, and then we start counting again.',
        'passage_explanation' => 'المجموعة الرابعة: 16 إلى 20 — twenty هو أول رقم فيه مقطعين لفظيين.',
        'sentence_explanation' => 'بعد 19 يجي 20، وبعدها نبدأ العد من جديد.',
        'vocabulary_json' => json_encode([
            ['word' => 'sixteen', 'pronunciation' => '/ˌsɪksˈtiːn/', 'meaning_ar' => 'ستة عشر'],
            ['word' => 'seventeen', 'pronunciation' => '/ˌsev.ənˈtiːn/', 'meaning_ar' => 'سبعة عشر'],
            ['word' => 'eighteen', 'pronunciation' => '/ˌeɪˈtiːn/', 'meaning_ar' => 'ثمانية عشر'],
            ['word' => 'nineteen', 'pronunciation' => '/ˌnaɪnˈtiːn/', 'meaning_ar' => 'تسعة عشر'],
            ['word' => 'twenty', 'pronunciation' => '/ˈtwen.ti/', 'meaning_ar' => 'عشرون'],
            ['word' => 'complete', 'pronunciation' => '/kəmˈpliːt/', 'meaning_ar' => 'يكمل'],
            ['word' => 'start', 'pronunciation' => '/stɑːrt/', 'meaning_ar' => 'يبدأ'],
            ['word' => 'student', 'pronunciation' => '/ˈstuː.dənt/', 'meaning_ar' => 'طالب'],
            ['word' => 'classroom', 'pronunciation' => '/ˈklæs.ruːm/', 'meaning_ar' => 'فصل / صف'],
            ['word' => 'again', 'pronunciation' => '/əˈɡen/', 'meaning_ar' => 'مرة ثانية'],
        ]),
    ],
    818 => [
        'sentence_1' => 'Thirty, forty, and fifty are multiples of ten. Thirty comes after twenty-nine. Forty is often misspelled as fourty, but the correct spelling is forty.',
        'sentence_2' => 'He is forty years old and works fifty hours a week.',
        'sentence_3' => 'The numbers thirty, forty, and fifty all end with the suffix ty.',
        'passage_explanation' => 'المجموعة الخامسة: 30 و40 و50 — كلها مضاعفات عشرة. لاحظ إن forty تُكتب بدون u.',
        'sentence_explanation' => 'الأرقام 30 و40 و50 كلها تنتهي بالمقطع ty.',
        'vocabulary_json' => json_encode([
            ['word' => 'thirty', 'pronunciation' => '/ˈθɜːr.ti/', 'meaning_ar' => 'ثلاثون'],
            ['word' => 'forty', 'pronunciation' => '/ˈfɔːr.ti/', 'meaning_ar' => 'أربعون'],
            ['word' => 'fifty', 'pronunciation' => '/ˈfɪf.ti/', 'meaning_ar' => 'خمسون'],
            ['word' => 'multiple', 'pronunciation' => '/ˈmʌl.tɪ.pəl/', 'meaning_ar' => 'مضاعف'],
            ['word' => 'often', 'pronunciation' => '/ˈɒf.ən/', 'meaning_ar' => 'غالباً'],
            ['word' => 'misspelled', 'pronunciation' => '/ˌmɪsˈspeld/', 'meaning_ar' => 'مكتوب غلط'],
            ['word' => 'correct', 'pronunciation' => '/kəˈrekt/', 'meaning_ar' => 'صحيح'],
            ['word' => 'work', 'pronunciation' => '/wɜːrk/', 'meaning_ar' => 'يعمل'],
            ['word' => 'hour', 'pronunciation' => '/aʊər/', 'meaning_ar' => 'ساعة'],
            ['word' => 'week', 'pronunciation' => '/wiːk/', 'meaning_ar' => 'أسبوع'],
        ]),
    ],
    819 => [
        'sentence_1' => 'Sixty, seventy, eighty, and ninety take us close to one hundred. These numbers follow a simple pattern: the single digit plus ty.',
        'sentence_2' => 'My grandmother is eighty years old and still very active.',
        'sentence_3' => 'Ninety-nine is the last two-digit number before one hundred.',
        'passage_explanation' => 'المجموعة السادسة: 60-90 — كلها تتبع نمط بسيط: الرقم الفردي + ty.',
        'sentence_explanation' => '99 هو آخر رقم من خانتين قبل المئة.',
        'vocabulary_json' => json_encode([
            ['word' => 'sixty', 'pronunciation' => '/ˈsɪks.ti/', 'meaning_ar' => 'ستون'],
            ['word' => 'seventy', 'pronunciation' => '/ˈsev.ən.ti/', 'meaning_ar' => 'سبعون'],
            ['word' => 'eighty', 'pronunciation' => '/ˈeɪ.ti/', 'meaning_ar' => 'ثمانون'],
            ['word' => 'ninety', 'pronunciation' => '/ˈnaɪn.ti/', 'meaning_ar' => 'تسعون'],
            ['word' => 'hundred', 'pronunciation' => '/ˈhʌn.drəd/', 'meaning_ar' => 'مئة'],
            ['word' => 'close', 'pronunciation' => '/kloʊs/', 'meaning_ar' => 'قريب'],
            ['word' => 'simple', 'pronunciation' => '/ˈsɪm.pəl/', 'meaning_ar' => 'بسيط'],
            ['word' => 'grandmother', 'pronunciation' => '/ˈɡræn.mʌð.ər/', 'meaning_ar' => 'جدة'],
            ['word' => 'active', 'pronunciation' => '/ˈæk.tɪv/', 'meaning_ar' => 'نشيط'],
            ['word' => 'still', 'pronunciation' => '/stɪl/', 'meaning_ar' => 'لا يزال'],
        ]),
    ],
    820 => [
        'sentence_1' => 'One hundred, two hundred, and one thousand are larger numbers. We use them to talk about prices, distances, and populations.',
        'sentence_2' => 'This book costs two hundred riyals.',
        'sentence_3' => 'One thousand meters equals one kilometer.',
        'passage_explanation' => 'المجموعة السابعة: المئات والآلاف — نستخدمها للأسعار والمسافات والسكان.',
        'sentence_explanation' => 'ألف متر يساوي كيلومتر واحد.',
        'vocabulary_json' => json_encode([
            ['word' => 'thousand', 'pronunciation' => '/ˈθaʊ.zənd/', 'meaning_ar' => 'ألف'],
            ['word' => 'larger', 'pronunciation' => '/ˈlɑːr.dʒər/', 'meaning_ar' => 'أكبر'],
            ['word' => 'price', 'pronunciation' => '/praɪs/', 'meaning_ar' => 'سعر'],
            ['word' => 'distance', 'pronunciation' => '/ˈdɪs.təns/', 'meaning_ar' => 'مسافة'],
            ['word' => 'population', 'pronunciation' => '/ˌpɒp.juˈleɪ.ʃən/', 'meaning_ar' => 'سكان'],
            ['word' => 'cost', 'pronunciation' => '/kɒst/', 'meaning_ar' => 'يكلف'],
            ['word' => 'meter', 'pronunciation' => '/ˈmiː.tər/', 'meaning_ar' => 'متر'],
            ['word' => 'equal', 'pronunciation' => '/ˈiː.kwəl/', 'meaning_ar' => 'يساوي'],
            ['word' => 'kilometer', 'pronunciation' => '/kɪˈlɒm.ɪ.tər/', 'meaning_ar' => 'كيلومتر'],
            ['word' => 'riyal', 'pronunciation' => '/riˈɑːl/', 'meaning_ar' => 'ريال'],
        ]),
    ],
    821 => [
        'sentence_1' => 'Ten thousand, one hundred thousand, and one million are very large numbers. A million has six zeros after the one.',
        'sentence_2' => 'The city has a population of two million people.',
        'sentence_3' => 'Practice saying large numbers out loud to build confidence.',
        'passage_explanation' => 'المجموعة الثامنة: عشرات الآلاف ومئات الآلاف والملايين. المليون فيه ست أصفار بعد الواحد.',
        'sentence_explanation' => 'تمرن على قول الأرقام الكبيرة بصوت عالي عشان تبني ثقتك.',
        'vocabulary_json' => json_encode([
            ['word' => 'million', 'pronunciation' => '/ˈmɪl.jən/', 'meaning_ar' => 'مليون'],
            ['word' => 'zero', 'pronunciation' => '/ˈzɪə.roʊ/', 'meaning_ar' => 'صفر'],
            ['word' => 'large', 'pronunciation' => '/lɑːrdʒ/', 'meaning_ar' => 'كبير'],
            ['word' => 'very', 'pronunciation' => '/ˈver.i/', 'meaning_ar' => 'جداً'],
            ['word' => 'people', 'pronunciation' => '/ˈpiː.pəl/', 'meaning_ar' => 'ناس'],
            ['word' => 'after', 'pronunciation' => '/ˈæf.tər/', 'meaning_ar' => 'بعد'],
            ['word' => 'confidence', 'pronunciation' => '/ˈkɒn.fɪ.dəns/', 'meaning_ar' => 'ثقة'],
            ['word' => 'saying', 'pronunciation' => '/ˈseɪ.ɪŋ/', 'meaning_ar' => 'قول'],
            ['word' => 'billion', 'pronunciation' => '/ˈbɪl.jən/', 'meaning_ar' => 'مليار'],
            ['word' => 'half', 'pronunciation' => '/hæf/', 'meaning_ar' => 'نصف'],
        ]),
    ],
    822 => [
        'sentence_1' => 'A billion has nine zeros. Very few people can imagine a billion of anything. Large numbers are important in science and economics.',
        'sentence_2' => 'There are nearly eight billion people on Earth.',
        'sentence_3' => 'Understanding large numbers connects you to the real world.',
        'passage_explanation' => 'المليار فيه 9 أصفار — الأرقام الكبيرة مهمة في العلوم والاقتصاد.',
        'sentence_explanation' => 'فهم الأرقام الكبيرة يربطك بالعالم الحقيقي.',
        'vocabulary_json' => json_encode([
            ['word' => 'billion', 'pronunciation' => '/ˈbɪl.jən/', 'meaning_ar' => 'مليار'],
            ['word' => 'imagine', 'pronunciation' => '/ɪˈmædʒ.ɪn/', 'meaning_ar' => 'يتخيل'],
            ['word' => 'science', 'pronunciation' => '/ˈsaɪ.əns/', 'meaning_ar' => 'علم'],
            ['word' => 'economics', 'pronunciation' => '/ˌiː.kəˈnɒm.ɪks/', 'meaning_ar' => 'اقتصاد'],
            ['word' => 'important', 'pronunciation' => '/ɪmˈpɔːr.tənt/', 'meaning_ar' => 'مهم'],
            ['word' => 'nearly', 'pronunciation' => '/ˈnɪr.li/', 'meaning_ar' => 'تقريباً'],
            ['word' => 'Earth', 'pronunciation' => '/ɜːrθ/', 'meaning_ar' => 'الأرض'],
            ['word' => 'real', 'pronunciation' => '/rɪəl/', 'meaning_ar' => 'حقيقي'],
            ['word' => 'world', 'pronunciation' => '/wɜːrld/', 'meaning_ar' => 'عالم'],
            ['word' => 'connect', 'pronunciation' => '/kəˈnekt/', 'meaning_ar' => 'يربط'],
        ]),
    ],
    823 => [
        'sentence_1' => 'Ordinal numbers show position or order. First, second, third, fourth, and fifth tell us the rank of something in a list.',
        'sentence_2' => 'She finished in first place and he came in third.',
        'sentence_3' => 'We use ordinal numbers with dates like January first.',
        'passage_explanation' => 'الأرقام الترتيبية توضح الموقع أو الترتيب: first, second, third وهكذا.',
        'sentence_explanation' => 'نستخدم الأرقام الترتيبية مع التواريخ مثل January first.',
        'vocabulary_json' => json_encode([
            ['word' => 'ordinal', 'pronunciation' => '/ˈɔːr.dɪ.nəl/', 'meaning_ar' => 'ترتيبي'],
            ['word' => 'position', 'pronunciation' => '/pəˈzɪʃ.ən/', 'meaning_ar' => 'موقع'],
            ['word' => 'order', 'pronunciation' => '/ˈɔːr.dər/', 'meaning_ar' => 'ترتيب'],
            ['word' => 'first', 'pronunciation' => '/fɜːrst/', 'meaning_ar' => 'أول'],
            ['word' => 'second', 'pronunciation' => '/ˈsek.ənd/', 'meaning_ar' => 'ثاني'],
            ['word' => 'third', 'pronunciation' => '/θɜːrd/', 'meaning_ar' => 'ثالث'],
            ['word' => 'fourth', 'pronunciation' => '/fɔːrθ/', 'meaning_ar' => 'رابع'],
            ['word' => 'fifth', 'pronunciation' => '/fɪfθ/', 'meaning_ar' => 'خامس'],
            ['word' => 'rank', 'pronunciation' => '/ræŋk/', 'meaning_ar' => 'ترتيب / مرتبة'],
            ['word' => 'list', 'pronunciation' => '/lɪst/', 'meaning_ar' => 'قائمة'],
        ]),
    ],
    824 => [
        'sentence_1' => 'Let us practice all the numbers from one to twenty. Say them out loud and try to pronounce each one clearly and confidently.',
        'sentence_2' => 'One, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty.',
        'sentence_3' => 'Excellent! You can now count to twenty in English.',
        'passage_explanation' => 'تمرين مراجعة على كل الأرقام من 1 لـ 20 — قولها بصوت واضح وبثقة.',
        'sentence_explanation' => 'ممتاز! دلوقتي تقدر تعد لـ 20 بالإنجليزي.',
        'vocabulary_json' => json_encode([
            ['word' => 'practice', 'pronunciation' => '/ˈpræk.tɪs/', 'meaning_ar' => 'يتمرن'],
            ['word' => 'aloud', 'pronunciation' => '/əˈlaʊd/', 'meaning_ar' => 'بصوت عالي'],
            ['word' => 'try', 'pronunciation' => '/traɪ/', 'meaning_ar' => 'يحاول'],
            ['word' => 'pronounce', 'pronunciation' => '/prəˈnaʊns/', 'meaning_ar' => 'ينطق'],
            ['word' => 'clearly', 'pronunciation' => '/ˈklɪr.li/', 'meaning_ar' => 'بوضوح'],
            ['word' => 'confidently', 'pronunciation' => '/ˈkɒn.fɪ.dənt.li/', 'meaning_ar' => 'بثقة'],
            ['word' => 'excellent', 'pronunciation' => '/ˈek.sə.lənt/', 'meaning_ar' => 'ممتاز'],
            ['word' => 'now', 'pronunciation' => '/naʊ/', 'meaning_ar' => 'الآن'],
            ['word' => 'loud', 'pronunciation' => '/laʊd/', 'meaning_ar' => 'عالي'],
            ['word' => 'each', 'pronunciation' => '/iːtʃ/', 'meaning_ar' => 'كل واحد'],
        ]),
    ],
    825 => [
        'sentence_1' => 'A chart of ordinal and cardinal numbers shows the difference. Cardinal numbers tell how many, like one, two, three. Ordinal numbers tell the position, like first, second, third.',
        'sentence_2' => 'Cardinal numbers count things, ordinal numbers rank them.',
        'sentence_3' => 'Use this chart as a reference whenever you need to check a number.',
        'passage_explanation' => 'جدول الأرقام العادية والترتيبية يوضح الفرق: العادية تعد (كم)، والترتيبية ترتب (الموقع).',
        'sentence_explanation' => 'استخدم الجدول كمرجع كل ما تحتاج تتأكد من رقم.',
        'vocabulary_json' => json_encode([
            ['word' => 'chart', 'pronunciation' => '/tʃɑːrt/', 'meaning_ar' => 'جدول / رسم بياني'],
            ['word' => 'cardinal', 'pronunciation' => '/ˈkɑːr.dɪ.nəl/', 'meaning_ar' => 'عادي / أساسي'],
            ['word' => 'difference', 'pronunciation' => '/ˈdɪf.ər.əns/', 'meaning_ar' => 'فرق'],
            ['word' => 'show', 'pronunciation' => '/ʃoʊ/', 'meaning_ar' => 'يوضح'],
            ['word' => 'how many', 'pronunciation' => '/haʊ ˈmen.i/', 'meaning_ar' => 'كم عدد'],
            ['word' => 'reference', 'pronunciation' => '/ˈref.ər.əns/', 'meaning_ar' => 'مرجع'],
            ['word' => 'whenever', 'pronunciation' => '/wenˈev.ər/', 'meaning_ar' => 'كلما'],
            ['word' => 'need', 'pronunciation' => '/niːd/', 'meaning_ar' => 'يحتاج'],
            ['word' => 'check', 'pronunciation' => '/tʃek/', 'meaning_ar' => 'يتأكد'],
            ['word' => 'use', 'pronunciation' => '/juːz/', 'meaning_ar' => 'يستخدم'],
        ]),
    ],
    827 => [
        'sentence_1' => 'A noun is a word that names a person, place, thing, or idea. Teacher is a person. School is a place. Book is a thing. Freedom is an idea.',
        'sentence_2' => 'Every sentence in English must contain at least one noun.',
        'sentence_3' => 'Nouns are the building blocks of the English language.',
        'passage_explanation' => 'الاسم هو كلمة تسمّي شخص أو مكان أو شيء أو فكرة. مثل teacher (شخص)، school (مكان)، book (شيء)، freedom (فكرة).',
        'sentence_explanation' => 'الأسماء هي اللبنات الأساسية في اللغة الإنجليزية.',
        'vocabulary_json' => json_encode([
            ['word' => 'noun', 'pronunciation' => '/naʊn/', 'meaning_ar' => 'اسم'],
            ['word' => 'person', 'pronunciation' => '/ˈpɜːr.sən/', 'meaning_ar' => 'شخص'],
            ['word' => 'place', 'pronunciation' => '/pleɪs/', 'meaning_ar' => 'مكان'],
            ['word' => 'thing', 'pronunciation' => '/θɪŋ/', 'meaning_ar' => 'شيء'],
            ['word' => 'idea', 'pronunciation' => '/aɪˈdɪə/', 'meaning_ar' => 'فكرة'],
            ['word' => 'teacher', 'pronunciation' => '/ˈtiː.tʃər/', 'meaning_ar' => 'معلم'],
            ['word' => 'school', 'pronunciation' => '/skuːl/', 'meaning_ar' => 'مدرسة'],
            ['word' => 'freedom', 'pronunciation' => '/ˈfriː.dəm/', 'meaning_ar' => 'حرية'],
            ['word' => 'building', 'pronunciation' => '/ˈbɪl.dɪŋ/', 'meaning_ar' => 'بناء / مبنى'],
            ['word' => 'block', 'pronunciation' => '/blɒk/', 'meaning_ar' => 'لبنة / قالب'],
        ]),
    ],
    828 => [
        'sentence_1' => 'A pronoun replaces a noun to avoid repetition. Instead of saying Ali is tall and Ali is smart, we say Ali is tall and he is smart.',
        'sentence_2' => 'He, she, it, they, and we are all common pronouns.',
        'sentence_3' => 'Pronouns make our speech smoother and more natural.',
        'passage_explanation' => 'الضمير يحل محل الاسم عشان ما نكرر. بدل ما نقول "علي طويل وعلي ذكي" نقول "علي طويل وهو ذكي".',
        'sentence_explanation' => 'الضمائر تخلي كلامنا أسلس وأطبع.',
        'vocabulary_json' => json_encode([
            ['word' => 'pronoun', 'pronunciation' => '/ˈproʊ.naʊn/', 'meaning_ar' => 'ضمير'],
            ['word' => 'replace', 'pronunciation' => '/rɪˈpleɪs/', 'meaning_ar' => 'يستبدل'],
            ['word' => 'avoid', 'pronunciation' => '/əˈvɔɪd/', 'meaning_ar' => 'يتجنب'],
            ['word' => 'repetition', 'pronunciation' => '/ˌrep.ɪˈtɪʃ.ən/', 'meaning_ar' => 'تكرار'],
            ['word' => 'instead', 'pronunciation' => '/ɪnˈsted/', 'meaning_ar' => 'بدلاً من'],
            ['word' => 'tall', 'pronunciation' => '/tɔːl/', 'meaning_ar' => 'طويل'],
            ['word' => 'smart', 'pronunciation' => '/smɑːrt/', 'meaning_ar' => 'ذكي'],
            ['word' => 'common', 'pronunciation' => '/ˈkɒm.ən/', 'meaning_ar' => 'شائع'],
            ['word' => 'smooth', 'pronunciation' => '/smuːð/', 'meaning_ar' => 'سلس'],
            ['word' => 'natural', 'pronunciation' => '/ˈnætʃ.ər.əl/', 'meaning_ar' => 'طبيعي'],
        ]),
    ],
    829 => [
        'sentence_1' => 'A verb is an action word that tells what the subject does. Run, eat, sleep, and study are all verbs. Without a verb, a sentence is incomplete.',
        'sentence_2' => 'She runs every morning and studies every night.',
        'sentence_3' => 'Verbs are the engine of every sentence.',
        'passage_explanation' => 'الفعل كلمة تدل على الحركة أو الحدث — مثل run و eat و sleep. بدون فعل الجملة ما تكتمل.',
        'sentence_explanation' => 'الأفعال هي محرك كل جملة.',
        'vocabulary_json' => json_encode([
            ['word' => 'verb', 'pronunciation' => '/vɜːrb/', 'meaning_ar' => 'فعل'],
            ['word' => 'action', 'pronunciation' => '/ˈæk.ʃən/', 'meaning_ar' => 'حركة / فعل'],
            ['word' => 'subject', 'pronunciation' => '/ˈsʌb.dʒekt/', 'meaning_ar' => 'فاعل'],
            ['word' => 'run', 'pronunciation' => '/rʌn/', 'meaning_ar' => 'يجري'],
            ['word' => 'eat', 'pronunciation' => '/iːt/', 'meaning_ar' => 'يأكل'],
            ['word' => 'sleep', 'pronunciation' => '/sliːp/', 'meaning_ar' => 'ينام'],
            ['word' => 'study', 'pronunciation' => '/ˈstʌd.i/', 'meaning_ar' => 'يدرس'],
            ['word' => 'incomplete', 'pronunciation' => '/ˌɪn.kəmˈpliːt/', 'meaning_ar' => 'غير مكتمل'],
            ['word' => 'morning', 'pronunciation' => '/ˈmɔːr.nɪŋ/', 'meaning_ar' => 'صباح'],
            ['word' => 'engine', 'pronunciation' => '/ˈen.dʒɪn/', 'meaning_ar' => 'محرك'],
        ]),
    ],
    830 => [
        'sentence_1' => 'An adjective describes a noun. It tells us about size, color, shape, or feeling. The big house has a red door and a beautiful garden.',
        'sentence_2' => 'Adjectives make our descriptions more vivid and interesting.',
        'sentence_3' => 'The happy child played with the small, colorful ball.',
        'passage_explanation' => 'الصفة تصف الاسم — توضح الحجم أو اللون أو الشكل أو الإحساس. مثل big, red, beautiful.',
        'sentence_explanation' => 'الصفات تخلي أوصافنا أحيى وأكثر تشويق.',
        'vocabulary_json' => json_encode([
            ['word' => 'adjective', 'pronunciation' => '/ˈædʒ.ɪk.tɪv/', 'meaning_ar' => 'صفة'],
            ['word' => 'describe', 'pronunciation' => '/dɪˈskraɪb/', 'meaning_ar' => 'يصف'],
            ['word' => 'size', 'pronunciation' => '/saɪz/', 'meaning_ar' => 'حجم'],
            ['word' => 'color', 'pronunciation' => '/ˈkʌl.ər/', 'meaning_ar' => 'لون'],
            ['word' => 'shape', 'pronunciation' => '/ʃeɪp/', 'meaning_ar' => 'شكل'],
            ['word' => 'big', 'pronunciation' => '/bɪɡ/', 'meaning_ar' => 'كبير'],
            ['word' => 'beautiful', 'pronunciation' => '/ˈbjuː.tɪ.fəl/', 'meaning_ar' => 'جميل'],
            ['word' => 'vivid', 'pronunciation' => '/ˈvɪv.ɪd/', 'meaning_ar' => 'حيوي / واضح'],
            ['word' => 'interesting', 'pronunciation' => '/ˈɪn.trə.stɪŋ/', 'meaning_ar' => 'مثير للاهتمام'],
            ['word' => 'happy', 'pronunciation' => '/ˈhæp.i/', 'meaning_ar' => 'سعيد'],
        ]),
    ],
    831 => [
        'sentence_1' => 'An adverb modifies a verb, adjective, or another adverb. It often tells how, when, or where. She sings beautifully. He always arrives early.',
        'sentence_2' => 'Many adverbs end in ly, like quickly, slowly, and carefully.',
        'sentence_3' => 'Adverbs add detail and depth to your sentences.',
        'passage_explanation' => 'الظرف يوصف الفعل أو الصفة أو ظرف ثاني — يوضح كيف أو متى أو وين. مثل beautifully و always.',
        'sentence_explanation' => 'الظروف تضيف تفاصيل وعمق لجملك.',
        'vocabulary_json' => json_encode([
            ['word' => 'adverb', 'pronunciation' => '/ˈæd.vɜːrb/', 'meaning_ar' => 'ظرف'],
            ['word' => 'modify', 'pronunciation' => '/ˈmɒd.ɪ.faɪ/', 'meaning_ar' => 'يُعدّل / يصف'],
            ['word' => 'how', 'pronunciation' => '/haʊ/', 'meaning_ar' => 'كيف'],
            ['word' => 'when', 'pronunciation' => '/wen/', 'meaning_ar' => 'متى'],
            ['word' => 'where', 'pronunciation' => '/wer/', 'meaning_ar' => 'أين'],
            ['word' => 'quickly', 'pronunciation' => '/ˈkwɪk.li/', 'meaning_ar' => 'بسرعة'],
            ['word' => 'slowly', 'pronunciation' => '/ˈsloʊ.li/', 'meaning_ar' => 'ببطء'],
            ['word' => 'beautifully', 'pronunciation' => '/ˈbjuː.tɪ.fəl.i/', 'meaning_ar' => 'بشكل جميل'],
            ['word' => 'always', 'pronunciation' => '/ˈɔːl.weɪz/', 'meaning_ar' => 'دائماً'],
            ['word' => 'early', 'pronunciation' => '/ˈɜːr.li/', 'meaning_ar' => 'مبكراً'],
        ]),
    ],
    832 => [
        'sentence_1' => 'A preposition shows the relationship between a noun and other words. Common prepositions include in, on, at, under, and between.',
        'sentence_2' => 'The cat is under the table and the book is on the shelf.',
        'sentence_3' => 'Prepositions help us describe location, time, and direction.',
        'passage_explanation' => 'حرف الجر يوضح العلاقة بين الاسم والكلمات الثانية — مثل in, on, at, under, between.',
        'sentence_explanation' => 'حروف الجر تساعدنا نوصف المكان والزمان والاتجاه.',
        'vocabulary_json' => json_encode([
            ['word' => 'preposition', 'pronunciation' => '/ˌprep.əˈzɪʃ.ən/', 'meaning_ar' => 'حرف جر'],
            ['word' => 'relationship', 'pronunciation' => '/rɪˈleɪ.ʃən.ʃɪp/', 'meaning_ar' => 'علاقة'],
            ['word' => 'under', 'pronunciation' => '/ˈʌn.dər/', 'meaning_ar' => 'تحت'],
            ['word' => 'between', 'pronunciation' => '/bɪˈtwiːn/', 'meaning_ar' => 'بين'],
            ['word' => 'table', 'pronunciation' => '/ˈteɪ.bəl/', 'meaning_ar' => 'طاولة'],
            ['word' => 'shelf', 'pronunciation' => '/ʃelf/', 'meaning_ar' => 'رف'],
            ['word' => 'location', 'pronunciation' => '/loʊˈkeɪ.ʃən/', 'meaning_ar' => 'موقع'],
            ['word' => 'direction', 'pronunciation' => '/dɪˈrek.ʃən/', 'meaning_ar' => 'اتجاه'],
            ['word' => 'above', 'pronunciation' => '/əˈbʌv/', 'meaning_ar' => 'فوق'],
            ['word' => 'beside', 'pronunciation' => '/bɪˈsaɪd/', 'meaning_ar' => 'بجانب'],
        ]),
    ],
    833 => [
        'sentence_1' => 'A conjunction joins two words or sentences together. And, but, or, and because are common conjunctions. I like tea and coffee.',
        'sentence_2' => 'She is tired but she keeps working hard.',
        'sentence_3' => 'Conjunctions connect ideas and make writing flow smoothly.',
        'passage_explanation' => 'حرف العطف يربط كلمتين أو جملتين مع بعض — مثل and, but, or, because.',
        'sentence_explanation' => 'حروف العطف تربط الأفكار وتخلي الكتابة تمشي بسلاسة.',
        'vocabulary_json' => json_encode([
            ['word' => 'conjunction', 'pronunciation' => '/kənˈdʒʌŋk.ʃən/', 'meaning_ar' => 'حرف عطف'],
            ['word' => 'join', 'pronunciation' => '/dʒɔɪn/', 'meaning_ar' => 'يربط'],
            ['word' => 'and', 'pronunciation' => '/ænd/', 'meaning_ar' => 'و'],
            ['word' => 'but', 'pronunciation' => '/bʌt/', 'meaning_ar' => 'لكن'],
            ['word' => 'or', 'pronunciation' => '/ɔːr/', 'meaning_ar' => 'أو'],
            ['word' => 'because', 'pronunciation' => '/bɪˈkɒz/', 'meaning_ar' => 'لأن'],
            ['word' => 'tired', 'pronunciation' => '/taɪərd/', 'meaning_ar' => 'تعبان'],
            ['word' => 'hard', 'pronunciation' => '/hɑːrd/', 'meaning_ar' => 'بجد'],
            ['word' => 'flow', 'pronunciation' => '/floʊ/', 'meaning_ar' => 'يتدفق'],
            ['word' => 'idea', 'pronunciation' => '/aɪˈdɪə/', 'meaning_ar' => 'فكرة'],
        ]),
    ],
    834 => [
        'sentence_1' => 'An interjection is a short word that expresses strong emotion. Wow shows surprise. Ouch shows pain. Hurray shows happiness.',
        'sentence_2' => 'Wow, that movie was absolutely amazing!',
        'sentence_3' => 'Interjections add emotion and excitement to our speech.',
        'passage_explanation' => 'حرف التعجب كلمة قصيرة تعبر عن عاطفة قوية — Wow للدهشة، Ouch للألم، Hurray للفرح.',
        'sentence_explanation' => 'حروف التعجب تضيف عاطفة وحماس لكلامنا.',
        'vocabulary_json' => json_encode([
            ['word' => 'interjection', 'pronunciation' => '/ˌɪn.tərˈdʒek.ʃən/', 'meaning_ar' => 'حرف تعجب'],
            ['word' => 'express', 'pronunciation' => '/ɪkˈspres/', 'meaning_ar' => 'يعبر عن'],
            ['word' => 'emotion', 'pronunciation' => '/ɪˈmoʊ.ʃən/', 'meaning_ar' => 'عاطفة'],
            ['word' => 'surprise', 'pronunciation' => '/sərˈpraɪz/', 'meaning_ar' => 'مفاجأة'],
            ['word' => 'pain', 'pronunciation' => '/peɪn/', 'meaning_ar' => 'ألم'],
            ['word' => 'happiness', 'pronunciation' => '/ˈhæp.i.nəs/', 'meaning_ar' => 'سعادة'],
            ['word' => 'amazing', 'pronunciation' => '/əˈmeɪ.zɪŋ/', 'meaning_ar' => 'مذهل'],
            ['word' => 'movie', 'pronunciation' => '/ˈmuː.vi/', 'meaning_ar' => 'فيلم'],
            ['word' => 'excitement', 'pronunciation' => '/ɪkˈsaɪt.mənt/', 'meaning_ar' => 'حماس'],
            ['word' => 'strong', 'pronunciation' => '/strɒŋ/', 'meaning_ar' => 'قوي'],
        ]),
    ],
    835 => [
        'sentence_1' => 'The eight parts of speech work together in every sentence. Nouns name things, verbs show actions, and adjectives describe them. Understanding these parts is essential.',
        'sentence_2' => 'A good sentence uses different parts of speech correctly.',
        'sentence_3' => 'Master the parts of speech and your English will improve greatly.',
        'passage_explanation' => 'أقسام الكلام الثمانية تشتغل مع بعض في كل جملة — الأسماء تسمي، الأفعال تبين الأفعال، والصفات تصف.',
        'sentence_explanation' => 'أتقن أقسام الكلام وإنجليزيك هيتحسن كثير.',
        'vocabulary_json' => json_encode([
            ['word' => 'speech', 'pronunciation' => '/spiːtʃ/', 'meaning_ar' => 'كلام'],
            ['word' => 'together', 'pronunciation' => '/təˈɡeð.ər/', 'meaning_ar' => 'مع بعض'],
            ['word' => 'essential', 'pronunciation' => '/ɪˈsen.ʃəl/', 'meaning_ar' => 'ضروري'],
            ['word' => 'good', 'pronunciation' => '/ɡʊd/', 'meaning_ar' => 'جيد'],
            ['word' => 'different', 'pronunciation' => '/ˈdɪf.ər.ənt/', 'meaning_ar' => 'مختلف'],
            ['word' => 'master', 'pronunciation' => '/ˈmæs.tər/', 'meaning_ar' => 'يتقن'],
            ['word' => 'greatly', 'pronunciation' => '/ˈɡreɪt.li/', 'meaning_ar' => 'كثيراً'],
            ['word' => 'sentence', 'pronunciation' => '/ˈsen.təns/', 'meaning_ar' => 'جملة'],
            ['word' => 'eight', 'pronunciation' => '/eɪt/', 'meaning_ar' => 'ثمانية'],
            ['word' => 'work', 'pronunciation' => '/wɜːrk/', 'meaning_ar' => 'يعمل'],
        ]),
    ],
    836 => [
        'sentence_1' => 'Identify the part of speech in each word. For example, in the sentence the tall boy runs fast, boy is a noun, tall is an adjective, and runs is a verb.',
        'sentence_2' => 'Practice identifying parts of speech in everything you read.',
        'sentence_3' => 'The more you practice, the easier grammar becomes.',
        'passage_explanation' => 'حدد نوع كل كلمة في الجملة — مثلاً: boy اسم، tall صفة، runs فعل.',
        'sentence_explanation' => 'كل ما تمرنت أكثر، القواعد تصير أسهل.',
        'vocabulary_json' => json_encode([
            ['word' => 'identify', 'pronunciation' => '/aɪˈden.tɪ.faɪ/', 'meaning_ar' => 'يحدد'],
            ['word' => 'example', 'pronunciation' => '/ɪɡˈzæm.pəl/', 'meaning_ar' => 'مثال'],
            ['word' => 'tall', 'pronunciation' => '/tɔːl/', 'meaning_ar' => 'طويل'],
            ['word' => 'boy', 'pronunciation' => '/bɔɪ/', 'meaning_ar' => 'ولد'],
            ['word' => 'fast', 'pronunciation' => '/fæst/', 'meaning_ar' => 'سريع'],
            ['word' => 'everything', 'pronunciation' => '/ˈev.ri.θɪŋ/', 'meaning_ar' => 'كل شيء'],
            ['word' => 'grammar', 'pronunciation' => '/ˈɡræm.ər/', 'meaning_ar' => 'قواعد'],
            ['word' => 'easy', 'pronunciation' => '/ˈiː.zi/', 'meaning_ar' => 'سهل'],
            ['word' => 'more', 'pronunciation' => '/mɔːr/', 'meaning_ar' => 'أكثر'],
            ['word' => 'become', 'pronunciation' => '/bɪˈkʌm/', 'meaning_ar' => 'يصبح'],
        ]),
    ],
    837 => [
        'sentence_1' => 'You have reached the first midterm. This test covers everything from the alphabet to parts of speech. Take your time and do your best.',
        'sentence_2' => 'Review all previous lessons before taking the midterm exam.',
        'sentence_3' => 'Believe in yourself and you will succeed.',
        'passage_explanation' => 'وصلت للاختبار النصفي الأول — يغطي كل شيء من الأبجدية لأقسام الكلام. خذ وقتك واعمل أفضل ما عندك.',
        'sentence_explanation' => 'ثق في نفسك وبتنجح.',
        'vocabulary_json' => json_encode([
            ['word' => 'midterm', 'pronunciation' => '/ˈmɪd.tɜːrm/', 'meaning_ar' => 'اختبار نصفي'],
            ['word' => 'exam', 'pronunciation' => '/ɪɡˈzæm/', 'meaning_ar' => 'اختبار'],
            ['word' => 'reach', 'pronunciation' => '/riːtʃ/', 'meaning_ar' => 'يصل'],
            ['word' => 'cover', 'pronunciation' => '/ˈkʌv.ər/', 'meaning_ar' => 'يغطي'],
            ['word' => 'previous', 'pronunciation' => '/ˈpriː.vi.əs/', 'meaning_ar' => 'سابق'],
            ['word' => 'review', 'pronunciation' => '/rɪˈvjuː/', 'meaning_ar' => 'يراجع'],
            ['word' => 'believe', 'pronunciation' => '/bɪˈliːv/', 'meaning_ar' => 'يؤمن / يصدق'],
            ['word' => 'yourself', 'pronunciation' => '/jɔːrˈself/', 'meaning_ar' => 'نفسك'],
            ['word' => 'succeed', 'pronunciation' => '/səkˈsiːd/', 'meaning_ar' => 'ينجح'],
            ['word' => 'best', 'pronunciation' => '/best/', 'meaning_ar' => 'أفضل'],
        ]),
    ],
];

$created = 0; $updated = 0; $skipped = 0;
foreach ($data as $lessonId => $content) {
    $lesson = Lesson::find($lessonId);
    if (!$lesson) { echo "SKIP: Lesson {$lessonId}\n"; $skipped++; continue; }
    $lesson->update(['has_pronunciation_exercise' => true]);
    $exercise = PronunciationExercise::where('lesson_id', $lessonId)->first();
    $d = [
        'lesson_id' => $lessonId, 'sentence_1' => $content['sentence_1'],
        'sentence_2' => $content['sentence_2'], 'sentence_3' => $content['sentence_3'],
        'vocabulary_json' => $content['vocabulary_json'],
        'passage_explanation' => $content['passage_explanation'],
        'sentence_explanation' => $content['sentence_explanation'],
        'passing_score' => 60, 'max_duration_seconds' => 30, 'allow_retake' => true,
    ];
    if ($exercise) { $exercise->update($d); echo "UPD: {$lessonId}\n"; $updated++; }
    else { PronunciationExercise::create($d); echo "NEW: {$lessonId}\n"; $created++; }
}
echo "\n=== BATCH 2 DONE === Created:{$created} Updated:{$updated} Skipped:{$skipped}\n";
