<?php
// Batch 8: Lessons 968-1007 (Present Tenses + Midterm 5)
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
use App\Models\PronunciationExercise;
use App\Models\Lesson;

$data = [
    968 => ['s1'=>'The present simple tense describes habits, facts, and routines. I drink coffee every morning. The sun rises in the east. She works at a hospital.','s2'=>'Use present simple for things that are always true or happen regularly.','s3'=>'Water boils at one hundred degrees. He plays football every weekend.','pe'=>'المضارع البسيط يصف العادات والحقائق والروتين اليومي. مثل I drink coffee every morning.','se'=>'الماء يغلي عند 100 درجة. هو يلعب كرة قدم كل نهاية أسبوع.','v'=>json_encode([['word'=>'habit','pronunciation'=>'/ˈhæb.ɪt/','meaning_ar'=>'عادة'],['word'=>'fact','pronunciation'=>'/fækt/','meaning_ar'=>'حقيقة'],['word'=>'routine','pronunciation'=>'/ruːˈtiːn/','meaning_ar'=>'روتين'],['word'=>'boil','pronunciation'=>'/bɔɪl/','meaning_ar'=>'يغلي'],['word'=>'degree','pronunciation'=>'/dɪˈɡriː/','meaning_ar'=>'درجة'],['word'=>'hospital','pronunciation'=>'/ˈhɒs.pɪ.təl/','meaning_ar'=>'مستشفى'],['word'=>'regularly','pronunciation'=>'/ˈreɡ.jə.lər.li/','meaning_ar'=>'بانتظام'],['word'=>'rise','pronunciation'=>'/raɪz/','meaning_ar'=>'يطلع'],['word'=>'weekend','pronunciation'=>'/ˌwiːkˈend/','meaning_ar'=>'نهاية الأسبوع'],['word'=>'true','pronunciation'=>'/truː/','meaning_ar'=>'صحيح']])],
    969 => ['s1'=>'To make negative sentences in present simple, use do not or does not before the base verb. I do not like spicy food. She does not watch television.','s2'=>'Don\'t and doesn\'t are the short forms used in everyday speech.','s3'=>'They don\'t live here anymore. He doesn\'t speak French.','pe'=>'للنفي في المضارع البسيط نستخدم do not أو does not قبل الفعل الأساسي.','se'=>'هم ما يعيشون هنا بعد. هو ما يتكلم فرنسي.','v'=>json_encode([['word'=>'spicy','pronunciation'=>'/ˈspaɪ.si/','meaning_ar'=>'حار'],['word'=>'food','pronunciation'=>'/fuːd/','meaning_ar'=>'طعام'],['word'=>'television','pronunciation'=>'/ˈtel.ə.vɪʒ.ən/','meaning_ar'=>'تلفزيون'],['word'=>'anymore','pronunciation'=>'/ˌen.iˈmɔːr/','meaning_ar'=>'بعد الآن'],['word'=>'French','pronunciation'=>'/frentʃ/','meaning_ar'=>'فرنسي'],['word'=>'everyday','pronunciation'=>'/ˈev.ri.deɪ/','meaning_ar'=>'يومي'],['word'=>'base','pronunciation'=>'/beɪs/','meaning_ar'=>'أساسي'],['word'=>'short','pronunciation'=>'/ʃɔːrt/','meaning_ar'=>'قصير'],['word'=>'negative','pronunciation'=>'/ˈneɡ.ə.tɪv/','meaning_ar'=>'نفي'],['word'=>'form','pronunciation'=>'/fɔːrm/','meaning_ar'=>'صيغة']])],
    975 => ['s1'=>'The present continuous tense describes actions happening right now or around now. I am studying English. She is cooking dinner. They are playing outside.','s2'=>'Form it with am, is, or are plus the verb with ing ending.','s3'=>'Look! The children are running in the park. It is raining heavily.','pe'=>'المضارع المستمر يصف أفعال تحصل الآن. نكونه بـ am/is/are + فعل + ing.','se'=>'شوف! الأطفال يجرون في الحديقة. المطر نازل بقوة.','v'=>json_encode([['word'=>'studying','pronunciation'=>'/ˈstʌd.i.ɪŋ/','meaning_ar'=>'يدرس'],['word'=>'cooking','pronunciation'=>'/ˈkʊk.ɪŋ/','meaning_ar'=>'يطبخ'],['word'=>'dinner','pronunciation'=>'/ˈdɪn.ər/','meaning_ar'=>'عشاء'],['word'=>'playing','pronunciation'=>'/ˈpleɪ.ɪŋ/','meaning_ar'=>'يلعب'],['word'=>'running','pronunciation'=>'/ˈrʌn.ɪŋ/','meaning_ar'=>'يجري'],['word'=>'raining','pronunciation'=>'/ˈreɪ.nɪŋ/','meaning_ar'=>'تمطر'],['word'=>'heavily','pronunciation'=>'/ˈhev.ɪ.li/','meaning_ar'=>'بقوة'],['word'=>'happening','pronunciation'=>'/ˈhæp.ən.ɪŋ/','meaning_ar'=>'يحصل'],['word'=>'right now','pronunciation'=>'/raɪt naʊ/','meaning_ar'=>'الآن'],['word'=>'outside','pronunciation'=>'/ˌaʊtˈsaɪd/','meaning_ar'=>'خارج']])],
    976 => ['s1'=>'The present continuous can also describe future plans that are already arranged. I am meeting my friend tomorrow. She is flying to London next week.','s2'=>'When talking about arranged plans, use present continuous with a future time word.','s3'=>'We are having a party this Saturday. He is starting his new job on Monday.','pe'=>'المضارع المستمر ممكن يصف خطط مستقبلية مرتبة. مثل I am meeting my friend tomorrow.','se'=>'عندنا حفلة يوم السبت. هو يبدأ وظيفته الجديدة يوم الاثنين.','v'=>json_encode([['word'=>'meeting','pronunciation'=>'/ˈmiː.tɪŋ/','meaning_ar'=>'يقابل'],['word'=>'tomorrow','pronunciation'=>'/təˈmɒr.oʊ/','meaning_ar'=>'بكرة'],['word'=>'flying','pronunciation'=>'/ˈflaɪ.ɪŋ/','meaning_ar'=>'يطير'],['word'=>'London','pronunciation'=>'/ˈlʌn.dən/','meaning_ar'=>'لندن'],['word'=>'arranged','pronunciation'=>'/əˈreɪndʒd/','meaning_ar'=>'مرتب'],['word'=>'party','pronunciation'=>'/ˈpɑːr.ti/','meaning_ar'=>'حفلة'],['word'=>'Saturday','pronunciation'=>'/ˈsæt.ər.deɪ/','meaning_ar'=>'السبت'],['word'=>'starting','pronunciation'=>'/ˈstɑːr.tɪŋ/','meaning_ar'=>'يبدأ'],['word'=>'job','pronunciation'=>'/dʒɒb/','meaning_ar'=>'وظيفة'],['word'=>'plan','pronunciation'=>'/plæn/','meaning_ar'=>'خطة']])],
    982 => ['s1'=>'The present perfect tense connects the past to the present. I have visited Paris twice. She has lived here for five years. They have just finished eating.','s2'=>'Form it with have or has plus the past participle of the verb.','s3'=>'He has already done his homework. We have never seen that movie.','pe'=>'المضارع التام يربط الماضي بالحاضر. نكونه بـ have/has + التصريف الثالث.','se'=>'هو خلّص واجبه بالفعل. إحنا أبداً ما شفنا ذاك الفيلم.','v'=>json_encode([['word'=>'visited','pronunciation'=>'/ˈvɪz.ɪ.tɪd/','meaning_ar'=>'زار'],['word'=>'twice','pronunciation'=>'/twaɪs/','meaning_ar'=>'مرتين'],['word'=>'lived','pronunciation'=>'/lɪvd/','meaning_ar'=>'عاش'],['word'=>'finished','pronunciation'=>'/ˈfɪn.ɪʃt/','meaning_ar'=>'أنهى'],['word'=>'already','pronunciation'=>'/ɔːlˈred.i/','meaning_ar'=>'بالفعل'],['word'=>'homework','pronunciation'=>'/ˈhoʊm.wɜːrk/','meaning_ar'=>'واجب'],['word'=>'never','pronunciation'=>'/ˈnev.ər/','meaning_ar'=>'أبداً'],['word'=>'done','pronunciation'=>'/dʌn/','meaning_ar'=>'أنجز'],['word'=>'seen','pronunciation'=>'/siːn/','meaning_ar'=>'رأى (تصريف ثالث)'],['word'=>'just','pronunciation'=>'/dʒʌst/','meaning_ar'=>'للتو']])],
    990 => ['s1'=>'The present perfect continuous shows an action that started in the past and is still continuing now. I have been studying for three hours. She has been working all day.','s2'=>'Form it with have been or has been plus the verb with ing.','s3'=>'They have been waiting since morning. It has been raining since yesterday.','pe'=>'المضارع التام المستمر يوضح فعل بدأ في الماضي ولا يزال مستمر. نكونه بـ have/has been + verb+ing.','se'=>'هم ينتظرون من الصباح. المطر نازل من أمس.','v'=>json_encode([['word'=>'studying','pronunciation'=>'/ˈstʌd.i.ɪŋ/','meaning_ar'=>'يدرس'],['word'=>'hours','pronunciation'=>'/aʊərz/','meaning_ar'=>'ساعات'],['word'=>'working','pronunciation'=>'/ˈwɜːr.kɪŋ/','meaning_ar'=>'يشتغل'],['word'=>'waiting','pronunciation'=>'/ˈweɪ.tɪŋ/','meaning_ar'=>'ينتظر'],['word'=>'since','pronunciation'=>'/sɪns/','meaning_ar'=>'منذ'],['word'=>'continuing','pronunciation'=>'/kənˈtɪn.juː.ɪŋ/','meaning_ar'=>'مستمر'],['word'=>'started','pronunciation'=>'/ˈstɑːr.tɪd/','meaning_ar'=>'بدأ'],['word'=>'still','pronunciation'=>'/stɪl/','meaning_ar'=>'لا يزال'],['word'=>'raining','pronunciation'=>'/ˈreɪ.nɪŋ/','meaning_ar'=>'تمطر'],['word'=>'all day','pronunciation'=>'/ɔːl deɪ/','meaning_ar'=>'طول اليوم']])],
    1007 => ['s1'=>'This is the fifth midterm exam. It covers all four present tenses: simple, continuous, perfect, and perfect continuous.','s2'=>'Understanding tenses is the backbone of English grammar.','s3'=>'You have learned so much. Be proud of your progress!','pe'=>'الاختبار النصفي الخامس — يغطي الأزمنة المضارعة الأربعة: البسيط والمستمر والتام والتام المستمر.','se'=>'تعلمت كثير — افتخر بتقدمك!','v'=>json_encode([['word'=>'tense','pronunciation'=>'/tens/','meaning_ar'=>'زمن'],['word'=>'backbone','pronunciation'=>'/ˈbæk.boʊn/','meaning_ar'=>'عمود فقري / أساس'],['word'=>'simple','pronunciation'=>'/ˈsɪm.pəl/','meaning_ar'=>'بسيط'],['word'=>'continuous','pronunciation'=>'/kənˈtɪn.ju.əs/','meaning_ar'=>'مستمر'],['word'=>'perfect','pronunciation'=>'/ˈpɜːr.fɪkt/','meaning_ar'=>'تام'],['word'=>'proud','pronunciation'=>'/praʊd/','meaning_ar'=>'فخور'],['word'=>'much','pronunciation'=>'/mʌtʃ/','meaning_ar'=>'كثير'],['word'=>'learned','pronunciation'=>'/lɜːrnd/','meaning_ar'=>'تعلم'],['word'=>'covers','pronunciation'=>'/ˈkʌv.ərz/','meaning_ar'=>'يغطي'],['word'=>'exam','pronunciation'=>'/ɪɡˈzæm/','meaning_ar'=>'اختبار']])],
];

$created = 0; $updated = 0; $skipped = 0;
foreach ($data as $lid => $c) {
    $lesson = Lesson::find($lid);
    if (!$lesson) { echo "SKIP:{$lid}\n"; $skipped++; continue; }
    $lesson->update(['has_pronunciation_exercise' => true]);
    $ex = PronunciationExercise::where('lesson_id', $lid)->first();
    $d = ['lesson_id'=>$lid,'sentence_1'=>$c['s1'],'sentence_2'=>$c['s2'],'sentence_3'=>$c['s3'],
          'vocabulary_json'=>$c['v'],'passage_explanation'=>$c['pe'],
          'sentence_explanation'=>$c['se'],'passing_score'=>60,'max_duration_seconds'=>30,'allow_retake'=>true];
    if ($ex) { $ex->update($d); echo "UPD:{$lid}\n"; $updated++; }
    else { PronunciationExercise::create($d); echo "NEW:{$lid}\n"; $created++; }
}
echo "\n=== BATCH 8 DONE === C:{$created} U:{$updated} S:{$skipped}\n";
