<?php
// Batch 4: Lessons 858-871 (Singular/Plural + Articles)
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
use App\Models\PronunciationExercise;
use App\Models\Lesson;

$data = [
    858 => [
        's1' => 'To make most nouns plural, we add S to the end. One cat becomes two cats. One book becomes two books. One car becomes two cars.',
        's2' => 'Adding S is the simplest way to make a noun plural.',
        's3' => 'Dogs, houses, and trees are all plural nouns with S.',
        'pe' => 'لتحويل معظم الأسماء للجمع، نضيف S في النهاية. cat تصير cats، book تصير books.',
        'se' => 'إضافة S هي أبسط طريقة لجمع الأسماء.',
        'v' => [
            ['word'=>'plural','pronunciation'=>'/ˈplʊr.əl/','meaning_ar'=>'جمع'],
            ['word'=>'singular','pronunciation'=>'/ˈsɪŋ.ɡjə.lər/','meaning_ar'=>'مفرد'],
            ['word'=>'cat','pronunciation'=>'/kæt/','meaning_ar'=>'قطة'],
            ['word'=>'book','pronunciation'=>'/bʊk/','meaning_ar'=>'كتاب'],
            ['word'=>'car','pronunciation'=>'/kɑːr/','meaning_ar'=>'سيارة'],
            ['word'=>'dog','pronunciation'=>'/dɒɡ/','meaning_ar'=>'كلب'],
            ['word'=>'house','pronunciation'=>'/haʊs/','meaning_ar'=>'بيت'],
            ['word'=>'tree','pronunciation'=>'/triː/','meaning_ar'=>'شجرة'],
            ['word'=>'add','pronunciation'=>'/æd/','meaning_ar'=>'يضيف'],
            ['word'=>'end','pronunciation'=>'/end/','meaning_ar'=>'نهاية'],
        ],
    ],
    859 => [
        's1' => 'When a noun ends in S, SH, CH, X, or Z, we add ES. One bus becomes two buses. One box becomes two boxes. One watch becomes two watches.',
        's2' => 'The ES ending makes pronunciation easier after these sounds.',
        's3' => 'Dishes, churches, and foxes all use the ES plural rule.',
        'pe' => 'لما الاسم ينتهي بـ S, SH, CH, X, Z نضيف ES. مثل buses, boxes, watches.',
        'se' => 'نهاية ES تسهل النطق بعد هذي الأصوات.',
        'v' => [
            ['word'=>'bus','pronunciation'=>'/bʌs/','meaning_ar'=>'حافلة'],
            ['word'=>'box','pronunciation'=>'/bɒks/','meaning_ar'=>'صندوق'],
            ['word'=>'watch','pronunciation'=>'/wɒtʃ/','meaning_ar'=>'ساعة يد'],
            ['word'=>'dish','pronunciation'=>'/dɪʃ/','meaning_ar'=>'طبق'],
            ['word'=>'church','pronunciation'=>'/tʃɜːrtʃ/','meaning_ar'=>'كنيسة'],
            ['word'=>'fox','pronunciation'=>'/fɒks/','meaning_ar'=>'ثعلب'],
            ['word'=>'brush','pronunciation'=>'/brʌʃ/','meaning_ar'=>'فرشاة'],
            ['word'=>'match','pronunciation'=>'/mætʃ/','meaning_ar'=>'مباراة'],
            ['word'=>'class','pronunciation'=>'/klæs/','meaning_ar'=>'فصل'],
            ['word'=>'buzz','pronunciation'=>'/bʌz/','meaning_ar'=>'طنين'],
        ],
    ],
    860 => [
        's1' => 'When a noun ends in a consonant plus Y, we change Y to I and add ES. One baby becomes two babies. One city becomes two cities.',
        's2' => 'If a vowel comes before Y, just add S like in boys and keys.',
        's3' => 'Stories, families, and countries all follow the Y to IES rule.',
        'pe' => 'لما الاسم ينتهي بحرف ساكن + Y، نغير Y لـ I ونضيف ES. مثل babies, cities.',
        'se' => 'لو قبل Y حرف صوتي، نضيف S بس مثل boys و keys.',
        'v' => [
            ['word'=>'baby','pronunciation'=>'/ˈbeɪ.bi/','meaning_ar'=>'طفل رضيع'],
            ['word'=>'city','pronunciation'=>'/ˈsɪt.i/','meaning_ar'=>'مدينة'],
            ['word'=>'story','pronunciation'=>'/ˈstɔːr.i/','meaning_ar'=>'قصة'],
            ['word'=>'family','pronunciation'=>'/ˈfæm.əl.i/','meaning_ar'=>'عائلة'],
            ['word'=>'country','pronunciation'=>'/ˈkʌn.tri/','meaning_ar'=>'بلد'],
            ['word'=>'key','pronunciation'=>'/kiː/','meaning_ar'=>'مفتاح'],
            ['word'=>'boy','pronunciation'=>'/bɔɪ/','meaning_ar'=>'ولد'],
            ['word'=>'consonant','pronunciation'=>'/ˈkɒn.sə.nənt/','meaning_ar'=>'حرف ساكن'],
            ['word'=>'party','pronunciation'=>'/ˈpɑːr.ti/','meaning_ar'=>'حفلة'],
            ['word'=>'lady','pronunciation'=>'/ˈleɪ.di/','meaning_ar'=>'سيدة'],
        ],
    ],
    861 => [
        's1' => 'Some nouns change their spelling completely in the plural. One man becomes two men. One woman becomes two women. One child becomes two children.',
        's2' => 'These irregular plurals must be memorized because they have no pattern.',
        's3' => 'Teeth, feet, mice, and geese are all irregular plurals.',
        'pe' => 'بعض الأسماء تتغير كلياً في الجمع — man تصير men، woman تصير women، child تصير children.',
        'se' => 'الجموع الشاذة لازم تحفظها لأنها ما تتبع قاعدة.',
        'v' => [
            ['word'=>'man','pronunciation'=>'/mæn/','meaning_ar'=>'رجل'],
            ['word'=>'men','pronunciation'=>'/men/','meaning_ar'=>'رجال'],
            ['word'=>'woman','pronunciation'=>'/ˈwʊm.ən/','meaning_ar'=>'امرأة'],
            ['word'=>'women','pronunciation'=>'/ˈwɪm.ɪn/','meaning_ar'=>'نساء'],
            ['word'=>'child','pronunciation'=>'/tʃaɪld/','meaning_ar'=>'طفل'],
            ['word'=>'children','pronunciation'=>'/ˈtʃɪl.drən/','meaning_ar'=>'أطفال'],
            ['word'=>'tooth','pronunciation'=>'/tuːθ/','meaning_ar'=>'سن'],
            ['word'=>'teeth','pronunciation'=>'/tiːθ/','meaning_ar'=>'أسنان'],
            ['word'=>'mouse','pronunciation'=>'/maʊs/','meaning_ar'=>'فأر'],
            ['word'=>'mice','pronunciation'=>'/maɪs/','meaning_ar'=>'فئران'],
        ],
    ],
    862 => [
        's1' => 'Some nouns do not change at all in the plural. One sheep stays two sheep. One fish stays two fish. One deer stays two deer.',
        's2' => 'These words look the same whether they are singular or plural.',
        's3' => 'Context tells us if the word is singular or plural.',
        'pe' => 'بعض الأسماء ما تتغير أبداً في الجمع — sheep تظل sheep، fish تظل fish.',
        'se' => 'السياق يوضح لنا إذا الكلمة مفرد ولا جمع.',
        'v' => [
            ['word'=>'sheep','pronunciation'=>'/ʃiːp/','meaning_ar'=>'خروف'],
            ['word'=>'fish','pronunciation'=>'/fɪʃ/','meaning_ar'=>'سمكة'],
            ['word'=>'deer','pronunciation'=>'/dɪr/','meaning_ar'=>'غزال'],
            ['word'=>'aircraft','pronunciation'=>'/ˈer.kræft/','meaning_ar'=>'طائرة'],
            ['word'=>'species','pronunciation'=>'/ˈspiː.ʃiːz/','meaning_ar'=>'نوع / فصيلة'],
            ['word'=>'series','pronunciation'=>'/ˈsɪr.iːz/','meaning_ar'=>'سلسلة'],
            ['word'=>'same','pronunciation'=>'/seɪm/','meaning_ar'=>'نفس'],
            ['word'=>'context','pronunciation'=>'/ˈkɒn.tekst/','meaning_ar'=>'سياق'],
            ['word'=>'whether','pronunciation'=>'/ˈweð.ər/','meaning_ar'=>'إذا'],
            ['word'=>'stay','pronunciation'=>'/steɪ/','meaning_ar'=>'يبقى'],
        ],
    ],
    863 => [
        's1' => 'Nouns ending in F or FE change to VES in the plural. One knife becomes two knives. One leaf becomes two leaves. One wife becomes two wives.',
        's2' => 'Not all F words follow this rule. Roofs and beliefs just add S.',
        's3' => 'Wolves, lives, and halves all change F to VES.',
        'pe' => 'الأسماء اللي تنتهي بـ F أو FE تتغير لـ VES — مثل knife تصير knives، leaf تصير leaves.',
        'se' => 'مش كل كلمات F تتبع القاعدة — roofs و beliefs نضيف S بس.',
        'v' => [
            ['word'=>'knife','pronunciation'=>'/naɪf/','meaning_ar'=>'سكين'],
            ['word'=>'knives','pronunciation'=>'/naɪvz/','meaning_ar'=>'سكاكين'],
            ['word'=>'leaf','pronunciation'=>'/liːf/','meaning_ar'=>'ورقة شجر'],
            ['word'=>'leaves','pronunciation'=>'/liːvz/','meaning_ar'=>'أوراق شجر'],
            ['word'=>'wife','pronunciation'=>'/waɪf/','meaning_ar'=>'زوجة'],
            ['word'=>'wolf','pronunciation'=>'/wʊlf/','meaning_ar'=>'ذئب'],
            ['word'=>'life','pronunciation'=>'/laɪf/','meaning_ar'=>'حياة'],
            ['word'=>'half','pronunciation'=>'/hæf/','meaning_ar'=>'نصف'],
            ['word'=>'roof','pronunciation'=>'/ruːf/','meaning_ar'=>'سقف'],
            ['word'=>'belief','pronunciation'=>'/bɪˈliːf/','meaning_ar'=>'اعتقاد'],
        ],
    ],
    864 => [
        's1' => 'Let us practice all the plural rules together. Add S, ES, or IES. Change F to VES. Remember the irregular plurals that must be memorized.',
        's2' => 'Practice makes perfect when learning plural forms.',
        's3' => 'You are now an expert at making nouns plural!',
        'pe' => 'تمرين شامل — أضف S أو ES أو IES، غيّر F لـ VES، وتذكر الجموع الشاذة.',
        'se' => 'دلوقتي صرت خبير في جمع الأسماء!',
        'v' => [
            ['word'=>'expert','pronunciation'=>'/ˈek.spɜːrt/','meaning_ar'=>'خبير'],
            ['word'=>'perfect','pronunciation'=>'/ˈpɜːr.fɪkt/','meaning_ar'=>'مثالي'],
            ['word'=>'remember','pronunciation'=>'/rɪˈmem.bər/','meaning_ar'=>'يتذكر'],
            ['word'=>'together','pronunciation'=>'/təˈɡeð.ər/','meaning_ar'=>'مع بعض'],
            ['word'=>'form','pronunciation'=>'/fɔːrm/','meaning_ar'=>'شكل / صيغة'],
            ['word'=>'making','pronunciation'=>'/ˈmeɪ.kɪŋ/','meaning_ar'=>'صنع'],
            ['word'=>'learning','pronunciation'=>'/ˈlɜːr.nɪŋ/','meaning_ar'=>'تعلم'],
            ['word'=>'rule','pronunciation'=>'/ruːl/','meaning_ar'=>'قاعدة'],
            ['word'=>'practice','pronunciation'=>'/ˈpræk.tɪs/','meaning_ar'=>'تمرين'],
            ['word'=>'change','pronunciation'=>'/tʃeɪndʒ/','meaning_ar'=>'يغير'],
        ],
    ],
    865 => [
        's1' => 'Common mistakes with plurals include adding S to uncountable nouns. We do not say informations or furnitures. Information and furniture have no plural.',
        's2' => 'Water, rice, and advice are uncountable nouns that never take S.',
        's3' => 'Avoid these common mistakes and your English will sound more natural.',
        'pe' => 'أخطاء شائعة: لا نضيف S للأسماء غير المعدودة مثل information و furniture.',
        'se' => 'تجنب هذي الأخطاء وإنجليزيك هيكون أطبع.',
        'v' => [
            ['word'=>'mistake','pronunciation'=>'/mɪˈsteɪk/','meaning_ar'=>'خطأ'],
            ['word'=>'uncountable','pronunciation'=>'/ʌnˈkaʊn.tə.bəl/','meaning_ar'=>'غير معدود'],
            ['word'=>'information','pronunciation'=>'/ˌɪn.fərˈmeɪ.ʃən/','meaning_ar'=>'معلومات'],
            ['word'=>'furniture','pronunciation'=>'/ˈfɜːr.nɪ.tʃər/','meaning_ar'=>'أثاث'],
            ['word'=>'water','pronunciation'=>'/ˈwɔː.tər/','meaning_ar'=>'ماء'],
            ['word'=>'rice','pronunciation'=>'/raɪs/','meaning_ar'=>'أرز'],
            ['word'=>'advice','pronunciation'=>'/ədˈvaɪs/','meaning_ar'=>'نصيحة'],
            ['word'=>'avoid','pronunciation'=>'/əˈvɔɪd/','meaning_ar'=>'يتجنب'],
            ['word'=>'common','pronunciation'=>'/ˈkɒm.ən/','meaning_ar'=>'شائع'],
            ['word'=>'natural','pronunciation'=>'/ˈnætʃ.ər.əl/','meaning_ar'=>'طبيعي'],
        ],
    ],
    866 => [
        's1' => 'Now test your knowledge of singular and plural nouns. Choose the correct plural form for each word. Remember all the rules you have learned.',
        's2' => 'Think carefully about which plural rule applies to each noun.',
        's3' => 'Great progress! You have mastered singular and plural forms.',
        'pe' => 'اختبر معرفتك بالمفرد والجمع — اختر الجمع الصحيح لكل كلمة.',
        'se' => 'تقدم رائع! أتقنت المفرد والجمع.',
        'v' => [
            ['word'=>'test','pronunciation'=>'/test/','meaning_ar'=>'اختبار'],
            ['word'=>'knowledge','pronunciation'=>'/ˈnɒl.ɪdʒ/','meaning_ar'=>'معرفة'],
            ['word'=>'choose','pronunciation'=>'/tʃuːz/','meaning_ar'=>'يختار'],
            ['word'=>'apply','pronunciation'=>'/əˈplaɪ/','meaning_ar'=>'يطبق'],
            ['word'=>'progress','pronunciation'=>'/ˈprɒɡ.res/','meaning_ar'=>'تقدم'],
            ['word'=>'mastered','pronunciation'=>'/ˈmæs.tərd/','meaning_ar'=>'أتقن'],
            ['word'=>'think','pronunciation'=>'/θɪŋk/','meaning_ar'=>'يفكر'],
            ['word'=>'carefully','pronunciation'=>'/ˈker.fə.li/','meaning_ar'=>'بعناية'],
            ['word'=>'great','pronunciation'=>'/ɡreɪt/','meaning_ar'=>'رائع'],
            ['word'=>'each','pronunciation'=>'/iːtʃ/','meaning_ar'=>'كل'],
        ],
    ],
    867 => [
        's1' => 'The articles A, An, and The are small but very important words. A and An are indefinite articles used before singular nouns. The is a definite article.',
        's2' => 'I saw a dog in the park. The dog was very friendly.',
        's3' => 'Articles help the listener know if you mean a specific thing or any thing.',
        'pe' => 'أدوات التعريف A, An, The كلمات صغيرة بس مهمة جداً. A و An غير محددة، The محددة.',
        'se' => 'أدوات التعريف تساعد المستمع يعرف إذا تقصد شيء محدد ولا أي شيء.',
        'v' => [
            ['word'=>'article','pronunciation'=>'/ˈɑːr.tɪ.kəl/','meaning_ar'=>'أداة تعريف'],
            ['word'=>'definite','pronunciation'=>'/ˈdef.ɪ.nət/','meaning_ar'=>'محدد'],
            ['word'=>'indefinite','pronunciation'=>'/ɪnˈdef.ɪ.nət/','meaning_ar'=>'غير محدد'],
            ['word'=>'specific','pronunciation'=>'/spəˈsɪf.ɪk/','meaning_ar'=>'محدد / معين'],
            ['word'=>'friendly','pronunciation'=>'/ˈfrend.li/','meaning_ar'=>'ودود'],
            ['word'=>'park','pronunciation'=>'/pɑːrk/','meaning_ar'=>'حديقة'],
            ['word'=>'listener','pronunciation'=>'/ˈlɪs.ən.ər/','meaning_ar'=>'مستمع'],
            ['word'=>'mean','pronunciation'=>'/miːn/','meaning_ar'=>'يقصد'],
            ['word'=>'any','pronunciation'=>'/ˈen.i/','meaning_ar'=>'أي'],
            ['word'=>'important','pronunciation'=>'/ɪmˈpɔːr.tənt/','meaning_ar'=>'مهم'],
        ],
    ],
    868 => [
        's1' => 'Use A before words that start with a consonant sound. Use An before words that start with a vowel sound. A university starts with a Y sound, so we say a university.',
        's2' => 'An hour is correct because the H in hour is silent.',
        's3' => 'Focus on the sound, not the spelling, when choosing A or An.',
        'pe' => 'A قبل صوت ساكن، An قبل صوت صوتي. ركز على الصوت مش الحرف — a university بس an hour.',
        'se' => 'ركز على الصوت مش الهجاء لما تختار A أو An.',
        'v' => [
            ['word'=>'university','pronunciation'=>'/ˌjuː.nɪˈvɜːr.sə.ti/','meaning_ar'=>'جامعة'],
            ['word'=>'hour','pronunciation'=>'/aʊər/','meaning_ar'=>'ساعة'],
            ['word'=>'honest','pronunciation'=>'/ˈɒn.ɪst/','meaning_ar'=>'صادق'],
            ['word'=>'uniform','pronunciation'=>'/ˈjuː.nɪ.fɔːrm/','meaning_ar'=>'زي موحد'],
            ['word'=>'umbrella','pronunciation'=>'/ʌmˈbrel.ə/','meaning_ar'=>'مظلة'],
            ['word'=>'European','pronunciation'=>'/ˌjʊr.əˈpiː.ən/','meaning_ar'=>'أوروبي'],
            ['word'=>'apple','pronunciation'=>'/ˈæp.əl/','meaning_ar'=>'تفاحة'],
            ['word'=>'focus','pronunciation'=>'/ˈfoʊ.kəs/','meaning_ar'=>'يركز'],
            ['word'=>'sound','pronunciation'=>'/saʊnd/','meaning_ar'=>'صوت'],
            ['word'=>'spelling','pronunciation'=>'/ˈspel.ɪŋ/','meaning_ar'=>'هجاء'],
        ],
    ],
    869 => [
        's1' => 'The definite article The is used when we talk about something specific that both the speaker and listener know about. The sun rises in the east.',
        's2' => 'We use The with unique things like the moon, the sky, and the Earth.',
        's3' => 'The Quran, the internet, and the news all use The.',
        'pe' => 'نستخدم The لما نتكلم عن شيء محدد يعرفه المتكلم والمستمع — مثل the sun, the moon.',
        'se' => 'القرآن والإنترنت والأخبار كلها تستخدم The.',
        'v' => [
            ['word'=>'rise','pronunciation'=>'/raɪz/','meaning_ar'=>'يطلع / يرتفع'],
            ['word'=>'east','pronunciation'=>'/iːst/','meaning_ar'=>'شرق'],
            ['word'=>'sun','pronunciation'=>'/sʌn/','meaning_ar'=>'شمس'],
            ['word'=>'moon','pronunciation'=>'/muːn/','meaning_ar'=>'قمر'],
            ['word'=>'sky','pronunciation'=>'/skaɪ/','meaning_ar'=>'سماء'],
            ['word'=>'unique','pronunciation'=>'/juˈniːk/','meaning_ar'=>'فريد'],
            ['word'=>'speaker','pronunciation'=>'/ˈspiː.kər/','meaning_ar'=>'متكلم'],
            ['word'=>'internet','pronunciation'=>'/ˈɪn.tər.net/','meaning_ar'=>'إنترنت'],
            ['word'=>'news','pronunciation'=>'/njuːz/','meaning_ar'=>'أخبار'],
            ['word'=>'both','pronunciation'=>'/boʊθ/','meaning_ar'=>'كلاهما'],
        ],
    ],
    870 => [
        's1' => 'Sometimes we do not use any article. We do not use articles with general plural nouns or uncountable nouns. Dogs are loyal. Water is essential.',
        's2' => 'We also skip articles with names, countries, and languages.',
        's3' => 'Knowing when to skip the article is just as important as knowing when to use one.',
        'pe' => 'أحياناً ما نستخدم أداة تعريف أبداً — مع الأسماء العامة الجمع أو غير المعدودة مثل Dogs are loyal.',
        'se' => 'معرفة متى ما نستخدم أداة تعريف مهمة بنفس القدر.',
        'v' => [
            ['word'=>'general','pronunciation'=>'/ˈdʒen.ər.əl/','meaning_ar'=>'عام'],
            ['word'=>'loyal','pronunciation'=>'/ˈlɔɪ.əl/','meaning_ar'=>'وفي'],
            ['word'=>'essential','pronunciation'=>'/ɪˈsen.ʃəl/','meaning_ar'=>'ضروري'],
            ['word'=>'skip','pronunciation'=>'/skɪp/','meaning_ar'=>'يتخطى'],
            ['word'=>'language','pronunciation'=>'/ˈlæŋ.ɡwɪdʒ/','meaning_ar'=>'لغة'],
            ['word'=>'country','pronunciation'=>'/ˈkʌn.tri/','meaning_ar'=>'بلد'],
            ['word'=>'sometimes','pronunciation'=>'/ˈsʌm.taɪmz/','meaning_ar'=>'أحياناً'],
            ['word'=>'knowing','pronunciation'=>'/ˈnoʊ.ɪŋ/','meaning_ar'=>'معرفة'],
            ['word'=>'also','pronunciation'=>'/ˈɔːl.soʊ/','meaning_ar'=>'أيضاً'],
            ['word'=>'just','pronunciation'=>'/dʒʌst/','meaning_ar'=>'فقط / تماماً'],
        ],
    ],
    871 => [
        's1' => 'Test your understanding of articles. Choose A, An, The, or no article for each sentence. Remember the rules about sounds and specific versus general meaning.',
        's2' => 'Articles may be small but they change the entire meaning of a sentence.',
        's3' => 'You now understand how to use English articles correctly!',
        'pe' => 'اختبر فهمك لأدوات التعريف — اختر A أو An أو The أو بدون أداة لكل جملة.',
        'se' => 'دلوقتي تفهم كيف تستخدم أدوات التعريف الإنجليزية بشكل صحيح!',
        'v' => [
            ['word'=>'understanding','pronunciation'=>'/ˌʌn.dərˈstæn.dɪŋ/','meaning_ar'=>'فهم'],
            ['word'=>'versus','pronunciation'=>'/ˈvɜːr.səs/','meaning_ar'=>'مقابل'],
            ['word'=>'entire','pronunciation'=>'/ɪnˈtaɪər/','meaning_ar'=>'كامل'],
            ['word'=>'correctly','pronunciation'=>'/kəˈrekt.li/','meaning_ar'=>'بشكل صحيح'],
            ['word'=>'sentence','pronunciation'=>'/ˈsen.təns/','meaning_ar'=>'جملة'],
            ['word'=>'meaning','pronunciation'=>'/ˈmiː.nɪŋ/','meaning_ar'=>'معنى'],
            ['word'=>'small','pronunciation'=>'/smɔːl/','meaning_ar'=>'صغير'],
            ['word'=>'remember','pronunciation'=>'/rɪˈmem.bər/','meaning_ar'=>'يتذكر'],
            ['word'=>'rule','pronunciation'=>'/ruːl/','meaning_ar'=>'قاعدة'],
            ['word'=>'choose','pronunciation'=>'/tʃuːz/','meaning_ar'=>'يختار'],
        ],
    ],
];

$created = 0; $updated = 0; $skipped = 0;
foreach ($data as $lid => $c) {
    $lesson = Lesson::find($lid);
    if (!$lesson) { echo "SKIP: {$lid}\n"; $skipped++; continue; }
    $lesson->update(['has_pronunciation_exercise' => true]);
    $ex = PronunciationExercise::where('lesson_id', $lid)->first();
    $d = ['lesson_id'=>$lid,'sentence_1'=>$c['s1'],'sentence_2'=>$c['s2'],'sentence_3'=>$c['s3'],
          'vocabulary_json'=>json_encode($c['v']),'passage_explanation'=>$c['pe'],
          'sentence_explanation'=>$c['se'],'passing_score'=>60,'max_duration_seconds'=>30,'allow_retake'=>true];
    if ($ex) { $ex->update($d); echo "UPD:{$lid}\n"; $updated++; }
    else { PronunciationExercise::create($d); echo "NEW:{$lid}\n"; $created++; }
}
echo "\n=== BATCH 4 DONE === C:{$created} U:{$updated} S:{$skipped}\n";
