<?php
// Batch 6: Lessons 883-926 (Types of Verbs, Verb to Be, Object, Adjectives, Adverbs, Attributive Nouns, Midterm 3)
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
use App\Models\PronunciationExercise;
use App\Models\Lesson;

$data = [
    883 => ['s1'=>'There are three main types of verbs: action verbs, linking verbs, and helping verbs. Action verbs show what the subject does, like run, eat, and write.','s2'=>'Linking verbs connect the subject to more information, like is, seem, and become.','s3'=>'Helping verbs assist the main verb, like can, will, and have.','pe'=>'ثلاث أنواع رئيسية من الأفعال: أفعال حركة، أفعال ربط، وأفعال مساعدة.','se'=>'الأفعال المساعدة تساعد الفعل الرئيسي مثل can, will, have.','v'=>json_encode([['word'=>'action','pronunciation'=>'/ˈæk.ʃən/','meaning_ar'=>'حركة'],['word'=>'linking','pronunciation'=>'/ˈlɪŋ.kɪŋ/','meaning_ar'=>'ربط'],['word'=>'helping','pronunciation'=>'/ˈhel.pɪŋ/','meaning_ar'=>'مساعد'],['word'=>'main','pronunciation'=>'/meɪn/','meaning_ar'=>'رئيسي'],['word'=>'type','pronunciation'=>'/taɪp/','meaning_ar'=>'نوع'],['word'=>'seem','pronunciation'=>'/siːm/','meaning_ar'=>'يبدو'],['word'=>'become','pronunciation'=>'/bɪˈkʌm/','meaning_ar'=>'يصبح'],['word'=>'assist','pronunciation'=>'/əˈsɪst/','meaning_ar'=>'يساعد'],['word'=>'connect','pronunciation'=>'/kəˈnekt/','meaning_ar'=>'يربط'],['word'=>'information','pronunciation'=>'/ˌɪn.fərˈmeɪ.ʃən/','meaning_ar'=>'معلومات']])],
    884 => ['s1'=>'Action verbs describe physical or mental activities. Physical actions include jump, kick, and throw. Mental actions include think, believe, and remember.','s2'=>'Every sentence needs at least one action to be complete.','s3'=>'She kicked the ball and he thought about the game.','pe'=>'أفعال الحركة تصف نشاطات جسدية أو عقلية. جسدية مثل jump, kick — عقلية مثل think, believe.','se'=>'هي ركلت الكرة وهو فكر في المباراة.','v'=>json_encode([['word'=>'physical','pronunciation'=>'/ˈfɪz.ɪ.kəl/','meaning_ar'=>'جسدي'],['word'=>'mental','pronunciation'=>'/ˈmen.təl/','meaning_ar'=>'عقلي'],['word'=>'jump','pronunciation'=>'/dʒʌmp/','meaning_ar'=>'يقفز'],['word'=>'kick','pronunciation'=>'/kɪk/','meaning_ar'=>'يركل'],['word'=>'throw','pronunciation'=>'/θroʊ/','meaning_ar'=>'يرمي'],['word'=>'believe','pronunciation'=>'/bɪˈliːv/','meaning_ar'=>'يؤمن'],['word'=>'remember','pronunciation'=>'/rɪˈmem.bər/','meaning_ar'=>'يتذكر'],['word'=>'activity','pronunciation'=>'/ækˈtɪv.ə.ti/','meaning_ar'=>'نشاط'],['word'=>'game','pronunciation'=>'/ɡeɪm/','meaning_ar'=>'لعبة'],['word'=>'describe','pronunciation'=>'/dɪˈskraɪb/','meaning_ar'=>'يصف']])],
    885 => ['s1'=>'Linking verbs connect the subject to a word that describes it. She is happy. The food smells delicious. He became a doctor.','s2'=>'Common linking verbs are be, seem, feel, look, and taste.','s3'=>'The flowers look beautiful and the cake tastes amazing.','pe'=>'أفعال الربط تربط الفاعل بكلمة تصفه. مثل She is happy — is يربط She بـ happy.','se'=>'الزهور تبدو جميلة والكعكة طعمها مذهل.','v'=>json_encode([['word'=>'link','pronunciation'=>'/lɪŋk/','meaning_ar'=>'يربط'],['word'=>'happy','pronunciation'=>'/ˈhæp.i/','meaning_ar'=>'سعيد'],['word'=>'delicious','pronunciation'=>'/dɪˈlɪʃ.əs/','meaning_ar'=>'لذيذ'],['word'=>'doctor','pronunciation'=>'/ˈdɒk.tər/','meaning_ar'=>'طبيب'],['word'=>'smell','pronunciation'=>'/smel/','meaning_ar'=>'يشم / رائحة'],['word'=>'feel','pronunciation'=>'/fiːl/','meaning_ar'=>'يشعر'],['word'=>'taste','pronunciation'=>'/teɪst/','meaning_ar'=>'يتذوق'],['word'=>'look','pronunciation'=>'/lʊk/','meaning_ar'=>'يبدو'],['word'=>'flower','pronunciation'=>'/ˈflaʊ.ər/','meaning_ar'=>'زهرة'],['word'=>'cake','pronunciation'=>'/keɪk/','meaning_ar'=>'كعكة']])],
    886 => ['s1'=>'The verb to be is the most important verb in English. It has many forms: am, is, are, was, were, been, being.','s2'=>'I am a student. She was tired yesterday. They have been friends for years.','s3'=>'Mastering the verb to be is essential for speaking English fluently.','pe'=>'فعل to be هو أهم فعل في الإنجليزي — له صيغ كثيرة: am, is, are, was, were, been, being.','se'=>'إتقان فعل to be أساسي للتحدث بالإنجليزي بطلاقة.','v'=>json_encode([['word'=>'student','pronunciation'=>'/ˈstuː.dənt/','meaning_ar'=>'طالب'],['word'=>'tired','pronunciation'=>'/taɪərd/','meaning_ar'=>'تعبان'],['word'=>'yesterday','pronunciation'=>'/ˈjes.tər.deɪ/','meaning_ar'=>'أمس'],['word'=>'friend','pronunciation'=>'/frend/','meaning_ar'=>'صديق'],['word'=>'fluently','pronunciation'=>'/ˈfluː.ənt.li/','meaning_ar'=>'بطلاقة'],['word'=>'mastering','pronunciation'=>'/ˈmæs.tər.ɪŋ/','meaning_ar'=>'إتقان'],['word'=>'essential','pronunciation'=>'/ɪˈsen.ʃəl/','meaning_ar'=>'ضروري'],['word'=>'form','pronunciation'=>'/fɔːrm/','meaning_ar'=>'صيغة'],['word'=>'most','pronunciation'=>'/moʊst/','meaning_ar'=>'أكثر'],['word'=>'year','pronunciation'=>'/jɪr/','meaning_ar'=>'سنة']])],
    887 => ['s1'=>'The negative form of to be uses not. I am not late. She is not here. They were not happy. We can also use contractions: isn\'t, aren\'t, wasn\'t, weren\'t.','s2'=>'Contractions make speech faster and more natural.','s3'=>'He isn\'t coming today. We aren\'t ready yet.','pe'=>'النفي بفعل to be نستخدم not. مثل I am not late. ونقدر نختصر: isn\'t, aren\'t.','se'=>'الاختصارات تخلي الكلام أسرع وأطبع.','v'=>json_encode([['word'=>'negative','pronunciation'=>'/ˈneɡ.ə.tɪv/','meaning_ar'=>'نفي'],['word'=>'late','pronunciation'=>'/leɪt/','meaning_ar'=>'متأخر'],['word'=>'here','pronunciation'=>'/hɪr/','meaning_ar'=>'هنا'],['word'=>'contraction','pronunciation'=>'/kənˈtræk.ʃən/','meaning_ar'=>'اختصار'],['word'=>'coming','pronunciation'=>'/ˈkʌm.ɪŋ/','meaning_ar'=>'قادم'],['word'=>'today','pronunciation'=>'/təˈdeɪ/','meaning_ar'=>'اليوم'],['word'=>'ready','pronunciation'=>'/ˈred.i/','meaning_ar'=>'جاهز'],['word'=>'yet','pronunciation'=>'/jet/','meaning_ar'=>'بعد / لسه'],['word'=>'faster','pronunciation'=>'/ˈfæs.tər/','meaning_ar'=>'أسرع'],['word'=>'speech','pronunciation'=>'/spiːtʃ/','meaning_ar'=>'كلام']])],
    888 => ['s1'=>'To form questions with to be, we put the verb before the subject. Are you happy? Is she a teacher? Were they at home?','s2'=>'Question formation with to be is simpler than with other verbs.','s3'=>'Was he late? Is it cold outside? Are we ready?','pe'=>'لتكوين سؤال بفعل to be نحط الفعل قبل الفاعل. مثل Are you happy? بدل You are happy.','se'=>'تكوين الأسئلة بفعل to be أبسط من الأفعال الثانية.','v'=>json_encode([['word'=>'form','pronunciation'=>'/fɔːrm/','meaning_ar'=>'يكوّن'],['word'=>'put','pronunciation'=>'/pʊt/','meaning_ar'=>'يحط'],['word'=>'before','pronunciation'=>'/bɪˈfɔːr/','meaning_ar'=>'قبل'],['word'=>'simpler','pronunciation'=>'/ˈsɪm.plər/','meaning_ar'=>'أبسط'],['word'=>'other','pronunciation'=>'/ˈʌð.ər/','meaning_ar'=>'آخر'],['word'=>'cold','pronunciation'=>'/koʊld/','meaning_ar'=>'بارد'],['word'=>'outside','pronunciation'=>'/ˌaʊtˈsaɪd/','meaning_ar'=>'خارج'],['word'=>'home','pronunciation'=>'/hoʊm/','meaning_ar'=>'بيت'],['word'=>'than','pronunciation'=>'/ðæn/','meaning_ar'=>'من (مقارنة)'],['word'=>'formation','pronunciation'=>'/fɔːrˈmeɪ.ʃən/','meaning_ar'=>'تكوين']])],
    889 => ['s1'=>'The object is the noun that receives the action of the verb. In the sentence she reads a book, the book is the object. The object answers what or whom.','s2'=>'Not every sentence needs an object, but many do.','s3'=>'He kicked the ball. She ate an apple. They watched a movie.','pe'=>'المفعول به هو الاسم اللي يستقبل حركة الفعل. في she reads a book — الـ book هو المفعول به.','se'=>'هو ركل الكرة. هي أكلت تفاحة. هم شاهدوا فيلم.','v'=>json_encode([['word'=>'object','pronunciation'=>'/ˈɒb.dʒekt/','meaning_ar'=>'مفعول به'],['word'=>'receive','pronunciation'=>'/rɪˈsiːv/','meaning_ar'=>'يستقبل'],['word'=>'whom','pronunciation'=>'/huːm/','meaning_ar'=>'من (مفعول)'],['word'=>'kick','pronunciation'=>'/kɪk/','meaning_ar'=>'يركل'],['word'=>'ball','pronunciation'=>'/bɔːl/','meaning_ar'=>'كرة'],['word'=>'apple','pronunciation'=>'/ˈæp.əl/','meaning_ar'=>'تفاحة'],['word'=>'watch','pronunciation'=>'/wɒtʃ/','meaning_ar'=>'يشاهد'],['word'=>'movie','pronunciation'=>'/ˈmuː.vi/','meaning_ar'=>'فيلم'],['word'=>'read','pronunciation'=>'/riːd/','meaning_ar'=>'يقرأ'],['word'=>'need','pronunciation'=>'/niːd/','meaning_ar'=>'يحتاج']])],
    890 => ['s1'=>'Adjectives describe nouns and come before the noun or after a linking verb. A tall building. The sky is blue. She wore a beautiful dress.','s2'=>'Adjectives answer: what kind, which one, or how many.','s3'=>'Three small red cars parked outside the big white house.','pe'=>'الصفات تصف الأسماء وتجي قبل الاسم أو بعد فعل ربط. مثل a tall building أو The sky is blue.','se'=>'ثلاث سيارات حمراء صغيرة واقفة برا البيت الأبيض الكبير.','v'=>json_encode([['word'=>'tall','pronunciation'=>'/tɔːl/','meaning_ar'=>'طويل'],['word'=>'blue','pronunciation'=>'/bluː/','meaning_ar'=>'أزرق'],['word'=>'dress','pronunciation'=>'/dres/','meaning_ar'=>'فستان'],['word'=>'small','pronunciation'=>'/smɔːl/','meaning_ar'=>'صغير'],['word'=>'red','pronunciation'=>'/red/','meaning_ar'=>'أحمر'],['word'=>'white','pronunciation'=>'/waɪt/','meaning_ar'=>'أبيض'],['word'=>'parked','pronunciation'=>'/pɑːrkt/','meaning_ar'=>'واقف / مركون'],['word'=>'wore','pronunciation'=>'/wɔːr/','meaning_ar'=>'لبس'],['word'=>'kind','pronunciation'=>'/kaɪnd/','meaning_ar'=>'نوع'],['word'=>'building','pronunciation'=>'/ˈbɪl.dɪŋ/','meaning_ar'=>'مبنى']])],
    891 => ['s1'=>'When using multiple adjectives, they follow a specific order: opinion, size, age, shape, color, origin, material, purpose. A beautiful small old round red Italian wooden dining table.','s2'=>'You do not need to memorize the order perfectly, but practice helps.','s3'=>'A lovely big new black German car.','pe'=>'لما نستخدم صفات متعددة، تتبع ترتيب معين: رأي، حجم، عمر، شكل، لون، أصل، مادة، غرض.','se'=>'سيارة ألمانية سوداء جديدة كبيرة جميلة.','v'=>json_encode([['word'=>'opinion','pronunciation'=>'/əˈpɪn.jən/','meaning_ar'=>'رأي'],['word'=>'size','pronunciation'=>'/saɪz/','meaning_ar'=>'حجم'],['word'=>'age','pronunciation'=>'/eɪdʒ/','meaning_ar'=>'عمر'],['word'=>'shape','pronunciation'=>'/ʃeɪp/','meaning_ar'=>'شكل'],['word'=>'origin','pronunciation'=>'/ˈɒr.ɪ.dʒɪn/','meaning_ar'=>'أصل'],['word'=>'material','pronunciation'=>'/məˈtɪr.i.əl/','meaning_ar'=>'مادة'],['word'=>'purpose','pronunciation'=>'/ˈpɜːr.pəs/','meaning_ar'=>'غرض'],['word'=>'order','pronunciation'=>'/ˈɔːr.dər/','meaning_ar'=>'ترتيب'],['word'=>'wooden','pronunciation'=>'/ˈwʊd.ən/','meaning_ar'=>'خشبي'],['word'=>'Italian','pronunciation'=>'/ɪˈtæl.jən/','meaning_ar'=>'إيطالي']])],
    892 => ['s1'=>'Adverbs modify verbs, adjectives, or other adverbs. She runs quickly. He is very tall. They speak extremely well.','s2'=>'Most adverbs are formed by adding ly to an adjective.','s3'=>'Slow becomes slowly. Careful becomes carefully. Happy becomes happily.','pe'=>'الظروف تصف الأفعال أو الصفات أو ظروف ثانية. مثل quickly, very, extremely.','se'=>'معظم الظروف تتكون بإضافة ly للصفة: slow → slowly, careful → carefully.','v'=>json_encode([['word'=>'quickly','pronunciation'=>'/ˈkwɪk.li/','meaning_ar'=>'بسرعة'],['word'=>'very','pronunciation'=>'/ˈver.i/','meaning_ar'=>'جداً'],['word'=>'extremely','pronunciation'=>'/ɪkˈstriːm.li/','meaning_ar'=>'للغاية'],['word'=>'well','pronunciation'=>'/wel/','meaning_ar'=>'بشكل جيد'],['word'=>'slowly','pronunciation'=>'/ˈsloʊ.li/','meaning_ar'=>'ببطء'],['word'=>'carefully','pronunciation'=>'/ˈker.fə.li/','meaning_ar'=>'بحرص'],['word'=>'happily','pronunciation'=>'/ˈhæp.ɪ.li/','meaning_ar'=>'بسعادة'],['word'=>'formed','pronunciation'=>'/fɔːrmd/','meaning_ar'=>'يتكون'],['word'=>'modify','pronunciation'=>'/ˈmɒd.ɪ.faɪ/','meaning_ar'=>'يعدّل'],['word'=>'most','pronunciation'=>'/moʊst/','meaning_ar'=>'معظم']])],
    893 => ['s1'=>'Not all adverbs end in ly. Some common adverbs are always, never, often, sometimes, already, just, soon, here, there, and very.','s2'=>'These adverbs tell us when, where, or how often something happens.','s3'=>'I always wake up early. She never eats fast food. They often visit us.','pe'=>'مش كل الظروف تنتهي بـ ly. بعض الظروف الشائعة: always, never, often, sometimes.','se'=>'أنا دايماً أصحى بدري. هي أبداً ما تاكل فاست فود. هم كثير يزورونا.','v'=>json_encode([['word'=>'always','pronunciation'=>'/ˈɔːl.weɪz/','meaning_ar'=>'دائماً'],['word'=>'never','pronunciation'=>'/ˈnev.ər/','meaning_ar'=>'أبداً'],['word'=>'often','pronunciation'=>'/ˈɒf.ən/','meaning_ar'=>'غالباً'],['word'=>'sometimes','pronunciation'=>'/ˈsʌm.taɪmz/','meaning_ar'=>'أحياناً'],['word'=>'already','pronunciation'=>'/ɔːlˈred.i/','meaning_ar'=>'بالفعل'],['word'=>'soon','pronunciation'=>'/suːn/','meaning_ar'=>'قريباً'],['word'=>'wake','pronunciation'=>'/weɪk/','meaning_ar'=>'يصحى'],['word'=>'early','pronunciation'=>'/ˈɜːr.li/','meaning_ar'=>'مبكراً'],['word'=>'visit','pronunciation'=>'/ˈvɪz.ɪt/','meaning_ar'=>'يزور'],['word'=>'happen','pronunciation'=>'/ˈhæp.ən/','meaning_ar'=>'يحصل']])],
    894 => ['s1'=>'Attributive nouns are nouns used as adjectives to describe other nouns. A school bus is a bus for school. A coffee cup is a cup for coffee.','s2'=>'The first noun acts like an adjective describing the second noun.','s3'=>'Chicken soup, gold ring, and football match are all examples.','pe'=>'الأسماء الوصفية هي أسماء تُستخدم كصفات لوصف أسماء ثانية. school bus = باص للمدرسة.','se'=>'شوربة دجاج وخاتم ذهب ومباراة كرة قدم كلها أمثلة.','v'=>json_encode([['word'=>'attributive','pronunciation'=>'/əˈtrɪb.jə.tɪv/','meaning_ar'=>'وصفي'],['word'=>'bus','pronunciation'=>'/bʌs/','meaning_ar'=>'حافلة'],['word'=>'cup','pronunciation'=>'/kʌp/','meaning_ar'=>'كوب'],['word'=>'chicken','pronunciation'=>'/ˈtʃɪk.ɪn/','meaning_ar'=>'دجاج'],['word'=>'soup','pronunciation'=>'/suːp/','meaning_ar'=>'شوربة'],['word'=>'gold','pronunciation'=>'/ɡoʊld/','meaning_ar'=>'ذهب'],['word'=>'ring','pronunciation'=>'/rɪŋ/','meaning_ar'=>'خاتم'],['word'=>'football','pronunciation'=>'/ˈfʊt.bɔːl/','meaning_ar'=>'كرة قدم'],['word'=>'match','pronunciation'=>'/mætʃ/','meaning_ar'=>'مباراة'],['word'=>'act','pronunciation'=>'/ækt/','meaning_ar'=>'يتصرف']])],
    926 => ['s1'=>'Congratulations! You have reached the third midterm. This exam covers verb types, to be, objects, adjectives, adverbs, and attributive nouns.','s2'=>'Take a deep breath, relax, and show what you have learned.','s3'=>'You have made incredible progress. Keep going!','pe'=>'مبروك! وصلت للاختبار النصفي الثالث — يغطي أنواع الأفعال، to be، المفعول به، الصفات، الظروف، والأسماء الوصفية.','se'=>'تقدمت تقدم رهيب — كمّل!','v'=>json_encode([['word'=>'congratulations','pronunciation'=>'/kənˌɡrætʃ.uˈleɪ.ʃənz/','meaning_ar'=>'مبروك'],['word'=>'breath','pronunciation'=>'/breθ/','meaning_ar'=>'نَفَس'],['word'=>'relax','pronunciation'=>'/rɪˈlæks/','meaning_ar'=>'يسترخي'],['word'=>'incredible','pronunciation'=>'/ɪnˈkred.ə.bəl/','meaning_ar'=>'لا يُصدق'],['word'=>'progress','pronunciation'=>'/ˈprɒɡ.res/','meaning_ar'=>'تقدم'],['word'=>'deep','pronunciation'=>'/diːp/','meaning_ar'=>'عميق'],['word'=>'going','pronunciation'=>'/ˈɡoʊ.ɪŋ/','meaning_ar'=>'مستمر'],['word'=>'made','pronunciation'=>'/meɪd/','meaning_ar'=>'صنع'],['word'=>'show','pronunciation'=>'/ʃoʊ/','meaning_ar'=>'يُظهر'],['word'=>'keep','pronunciation'=>'/kiːp/','meaning_ar'=>'يستمر']])],
];

$created = 0; $updated = 0; $skipped = 0;
foreach ($data as $lid => $c) {
    $lesson = Lesson::find($lid);
    if (!$lesson) { echo "SKIP:{$lid}\n"; $skipped++; continue; }
    $lesson->update(['has_pronunciation_exercise' => true]);
    $ex = PronunciationExercise::where('lesson_id', $lid)->first();
    $d = ['lesson_id'=>$lid,'sentence_1'=>$c['s1'],'sentence_2'=>$c['s2'],'sentence_3'=>$c['s3'],
          'vocabulary_json'=>$c['v'],'passage_explanation'=>$c['pe'],
          'sentence_explanation'=>$c['se'],'passing_score'=>60,'max_duration_seconds'=>30,'allow_retake'=>true];
    if ($ex) { $ex->update($d); echo "UPD:{$lid}\n"; $updated++; }
    else { PronunciationExercise::create($d); echo "NEW:{$lid}\n"; $created++; }
}
echo "\n=== BATCH 6 DONE === C:{$created} U:{$updated} S:{$skipped}\n";
