<?php
// Batch 11: Lessons 1085-1163 (Imperative, Modal Verbs, Wh Questions, Comparison, Quantifiers, Delexical, There is/are, Time, Date, Midterm 8, Final)
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
use App\Models\PronunciationExercise;
use App\Models\Lesson;

$data = [
    1085 => ['s1'=>'Imperative sentences give commands, instructions, or requests. Open the door. Please sit down. Do not touch that. Be careful!','s2'=>'The subject you is implied and not written in imperative sentences.','s3'=>'Close your books. Listen carefully. Don\'t be late.','pe'=>'جمل الأمر تعطي أوامر أو تعليمات أو طلبات. مثل Open the door. Please sit down.','se'=>'سكروا كتبكم. اسمعوا بعناية. لا تتأخرون.','v'=>json_encode([['word'=>'command','pronunciation'=>'/kəˈmænd/','meaning_ar'=>'أمر'],['word'=>'instruction','pronunciation'=>'/ɪnˈstrʌk.ʃən/','meaning_ar'=>'تعليمات'],['word'=>'request','pronunciation'=>'/rɪˈkwest/','meaning_ar'=>'طلب'],['word'=>'open','pronunciation'=>'/ˈoʊ.pən/','meaning_ar'=>'افتح'],['word'=>'door','pronunciation'=>'/dɔːr/','meaning_ar'=>'باب'],['word'=>'sit','pronunciation'=>'/sɪt/','meaning_ar'=>'اجلس'],['word'=>'touch','pronunciation'=>'/tʌtʃ/','meaning_ar'=>'يلمس'],['word'=>'careful','pronunciation'=>'/ˈker.fəl/','meaning_ar'=>'حذر'],['word'=>'close','pronunciation'=>'/kloʊz/','meaning_ar'=>'أغلق'],['word'=>'listen','pronunciation'=>'/ˈlɪs.ən/','meaning_ar'=>'اسمع']])],
    1092 => ['s1'=>'Modal verbs express ability, possibility, permission, or obligation. Can shows ability. May shows permission. Must shows obligation. Should shows advice.','s2'=>'Modal verbs do not change form: she can, he must, they should.','s3'=>'You can do it! You should study more. You must wear a seatbelt.','pe'=>'الأفعال المساعدة تعبر عن القدرة أو الإمكانية أو الإذن أو الالتزام. can = قدرة, must = لازم, should = نصيحة.','se'=>'تقدر تسويها! المفروض تدرس أكثر. لازم تلبس حزام الأمان.','v'=>json_encode([['word'=>'can','pronunciation'=>'/kæn/','meaning_ar'=>'يقدر'],['word'=>'may','pronunciation'=>'/meɪ/','meaning_ar'=>'ممكن / يسمح'],['word'=>'must','pronunciation'=>'/mʌst/','meaning_ar'=>'لازم'],['word'=>'should','pronunciation'=>'/ʃʊd/','meaning_ar'=>'يجب / ينبغي'],['word'=>'could','pronunciation'=>'/kʊd/','meaning_ar'=>'يقدر (ماضي)'],['word'=>'would','pronunciation'=>'/wʊd/','meaning_ar'=>'سوف (مشروط)'],['word'=>'might','pronunciation'=>'/maɪt/','meaning_ar'=>'قد / ربما'],['word'=>'ability','pronunciation'=>'/əˈbɪl.ə.ti/','meaning_ar'=>'قدرة'],['word'=>'permission','pronunciation'=>'/pərˈmɪʃ.ən/','meaning_ar'=>'إذن'],['word'=>'obligation','pronunciation'=>'/ˌɒb.lɪˈɡeɪ.ʃən/','meaning_ar'=>'التزام']])],
    1100 => ['s1'=>'Wh-questions start with question words: who, what, where, when, why, which, and how. Who is your teacher? What do you want? Where do you live?','s2'=>'Each question word asks for a different type of information.','s3'=>'When is the meeting? Why are you late? How do you spell your name?','pe'=>'أسئلة Wh تبدأ بكلمات استفهام: who, what, where, when, why, which, how.','se'=>'متى الاجتماع؟ ليش متأخر؟ كيف تهجي اسمك؟','v'=>json_encode([['word'=>'who','pronunciation'=>'/huː/','meaning_ar'=>'من'],['word'=>'what','pronunciation'=>'/wɒt/','meaning_ar'=>'ماذا'],['word'=>'where','pronunciation'=>'/wer/','meaning_ar'=>'أين'],['word'=>'when','pronunciation'=>'/wen/','meaning_ar'=>'متى'],['word'=>'why','pronunciation'=>'/waɪ/','meaning_ar'=>'لماذا'],['word'=>'which','pronunciation'=>'/wɪtʃ/','meaning_ar'=>'أي'],['word'=>'how','pronunciation'=>'/haʊ/','meaning_ar'=>'كيف'],['word'=>'meeting','pronunciation'=>'/ˈmiː.tɪŋ/','meaning_ar'=>'اجتماع'],['word'=>'spell','pronunciation'=>'/spel/','meaning_ar'=>'يهجي'],['word'=>'type','pronunciation'=>'/taɪp/','meaning_ar'=>'نوع']])],
    1110 => ['s1'=>'Comparatives compare two things using er or more. Bigger, faster, more beautiful. She is taller than her brother. This book is more interesting than that one.','s2'=>'Short adjectives add er: big becomes bigger. Long adjectives use more.','s3'=>'My car is faster than yours. English is easier than you think.','pe'=>'المقارنة بين شيئين نستخدم er أو more. الصفات القصيرة نضيف er، الطويلة نستخدم more.','se'=>'سيارتي أسرع من سيارتك. الإنجليزي أسهل مما تتوقع.','v'=>json_encode([['word'=>'bigger','pronunciation'=>'/ˈbɪɡ.ər/','meaning_ar'=>'أكبر'],['word'=>'faster','pronunciation'=>'/ˈfæs.tər/','meaning_ar'=>'أسرع'],['word'=>'taller','pronunciation'=>'/ˈtɔːl.ər/','meaning_ar'=>'أطول'],['word'=>'more','pronunciation'=>'/mɔːr/','meaning_ar'=>'أكثر'],['word'=>'than','pronunciation'=>'/ðæn/','meaning_ar'=>'من (مقارنة)'],['word'=>'better','pronunciation'=>'/ˈbet.ər/','meaning_ar'=>'أفضل'],['word'=>'worse','pronunciation'=>'/wɜːrs/','meaning_ar'=>'أسوأ'],['word'=>'easier','pronunciation'=>'/ˈiː.zi.ər/','meaning_ar'=>'أسهل'],['word'=>'shorter','pronunciation'=>'/ˈʃɔːr.tər/','meaning_ar'=>'أقصر'],['word'=>'longer','pronunciation'=>'/ˈlɒŋ.ɡər/','meaning_ar'=>'أطول']])],
    1120 => ['s1'=>'Quantifiers tell us how much or how many. Much is for uncountable nouns. Many is for countable nouns. Some works with both. A lot of is very common.','s2'=>'How much water do you drink? How many books do you have?','s3'=>'There is a lot of traffic today. She doesn\'t have much time.','pe'=>'المحددات الكمية: much لغير المعدود، many للمعدود، some للاثنين، a lot of شائعة جداً.','se'=>'فيه زحمة كثيرة اليوم. هي ما عندها وقت كثير.','v'=>json_encode([['word'=>'much','pronunciation'=>'/mʌtʃ/','meaning_ar'=>'كثير (غير معدود)'],['word'=>'many','pronunciation'=>'/ˈmen.i/','meaning_ar'=>'كثير (معدود)'],['word'=>'some','pronunciation'=>'/sʌm/','meaning_ar'=>'بعض'],['word'=>'any','pronunciation'=>'/ˈen.i/','meaning_ar'=>'أي'],['word'=>'few','pronunciation'=>'/fjuː/','meaning_ar'=>'قليل (معدود)'],['word'=>'little','pronunciation'=>'/ˈlɪt.əl/','meaning_ar'=>'قليل (غير معدود)'],['word'=>'enough','pronunciation'=>'/ɪˈnʌf/','meaning_ar'=>'كافي'],['word'=>'several','pronunciation'=>'/ˈsev.ər.əl/','meaning_ar'=>'عدة'],['word'=>'traffic','pronunciation'=>'/ˈtræf.ɪk/','meaning_ar'=>'مرور / زحمة'],['word'=>'plenty','pronunciation'=>'/ˈplen.ti/','meaning_ar'=>'وفرة']])],
    1130 => ['s1'=>'Delexical verbs are common verbs used with nouns to create specific meanings. Have a shower. Take a break. Make a mistake. Do your homework. Give a presentation.','s2'=>'The noun after the verb carries the main meaning, not the verb itself.','s3'=>'Let\'s take a walk. Can I have a look? She made a decision.','pe'=>'الأفعال الخفيفة أفعال شائعة تُستخدم مع أسماء لتكوين معاني محددة. مثل have a shower, take a break.','se'=>'خلنا نتمشى. أقدر ألقي نظرة؟ هي اتخذت قرار.','v'=>json_encode([['word'=>'shower','pronunciation'=>'/ˈʃaʊ.ər/','meaning_ar'=>'دش'],['word'=>'break','pronunciation'=>'/breɪk/','meaning_ar'=>'استراحة'],['word'=>'mistake','pronunciation'=>'/mɪˈsteɪk/','meaning_ar'=>'خطأ'],['word'=>'presentation','pronunciation'=>'/ˌprez.ənˈteɪ.ʃən/','meaning_ar'=>'عرض تقديمي'],['word'=>'walk','pronunciation'=>'/wɔːk/','meaning_ar'=>'مشي'],['word'=>'look','pronunciation'=>'/lʊk/','meaning_ar'=>'نظرة'],['word'=>'decision','pronunciation'=>'/dɪˈsɪʒ.ən/','meaning_ar'=>'قرار'],['word'=>'carry','pronunciation'=>'/ˈkær.i/','meaning_ar'=>'يحمل'],['word'=>'meaning','pronunciation'=>'/ˈmiː.nɪŋ/','meaning_ar'=>'معنى'],['word'=>'specific','pronunciation'=>'/spəˈsɪf.ɪk/','meaning_ar'=>'محدد']])],
    1140 => ['s1'=>'There is and there are introduce the existence of something. There is a cat on the roof. There are three books on the table. Is there a pharmacy nearby?','s2'=>'Use there is with singular nouns and there are with plural nouns.','s3'=>'There is a problem with the computer. There are many students in the class.','pe'=>'there is و there are تقدم وجود شيء. there is للمفرد و there are للجمع.','se'=>'فيه مشكلة في الكمبيوتر. فيه طلاب كثير في الفصل.','v'=>json_encode([['word'=>'there','pronunciation'=>'/ðer/','meaning_ar'=>'هناك / يوجد'],['word'=>'roof','pronunciation'=>'/ruːf/','meaning_ar'=>'سطح'],['word'=>'pharmacy','pronunciation'=>'/ˈfɑːr.mə.si/','meaning_ar'=>'صيدلية'],['word'=>'nearby','pronunciation'=>'/ˌnɪrˈbaɪ/','meaning_ar'=>'قريب'],['word'=>'existence','pronunciation'=>'/ɪɡˈzɪs.təns/','meaning_ar'=>'وجود'],['word'=>'introduce','pronunciation'=>'/ˌɪn.trəˈdjuːs/','meaning_ar'=>'يقدم'],['word'=>'problem','pronunciation'=>'/ˈprɒb.ləm/','meaning_ar'=>'مشكلة'],['word'=>'computer','pronunciation'=>'/kəmˈpjuː.tər/','meaning_ar'=>'كمبيوتر'],['word'=>'table','pronunciation'=>'/ˈteɪ.bəl/','meaning_ar'=>'طاولة'],['word'=>'class','pronunciation'=>'/klæs/','meaning_ar'=>'فصل']])],
    1150 => ['s1'=>'Telling time in English uses o\'clock for exact hours. Quarter past for fifteen minutes after. Half past for thirty minutes. Quarter to for fifteen minutes before the next hour.','s2'=>'It is half past three. The meeting starts at quarter to five.','s3'=>'What time is it? It is ten minutes past two.','pe'=>'إخبار الوقت: o\'clock للساعة بالضبط، quarter past ربع بعد، half past نص، quarter to ربع قبل.','se'=>'كم الساعة؟ الساعة 2 وعشر دقايق.','v'=>json_encode([['word'=>'o\'clock','pronunciation'=>'/əˈklɒk/','meaning_ar'=>'الساعة'],['word'=>'quarter','pronunciation'=>'/ˈkwɔːr.tər/','meaning_ar'=>'ربع'],['word'=>'half','pronunciation'=>'/hæf/','meaning_ar'=>'نص'],['word'=>'past','pronunciation'=>'/pæst/','meaning_ar'=>'بعد'],['word'=>'to','pronunciation'=>'/tuː/','meaning_ar'=>'قبل (للوقت)'],['word'=>'minute','pronunciation'=>'/ˈmɪn.ɪt/','meaning_ar'=>'دقيقة'],['word'=>'hour','pronunciation'=>'/aʊər/','meaning_ar'=>'ساعة'],['word'=>'time','pronunciation'=>'/taɪm/','meaning_ar'=>'وقت'],['word'=>'noon','pronunciation'=>'/nuːn/','meaning_ar'=>'ظهر'],['word'=>'midnight','pronunciation'=>'/ˈmɪd.naɪt/','meaning_ar'=>'منتصف الليل']])],
    1155 => ['s1'=>'Dates in English follow a specific format. In American English: month, day, year. March thirtieth, twenty twenty-six. In British English: day, month, year.','s2'=>'We say March thirtieth or the thirtieth of March for dates.','s3'=>'My birthday is on July fifteenth. The meeting is on October third.','pe'=>'التواريخ بالإنجليزي: الأمريكي شهر/يوم/سنة، البريطاني يوم/شهر/سنة.','se'=>'عيد ميلادي في 15 يوليو. الاجتماع في 3 أكتوبر.','v'=>json_encode([['word'=>'date','pronunciation'=>'/deɪt/','meaning_ar'=>'تاريخ'],['word'=>'month','pronunciation'=>'/mʌnθ/','meaning_ar'=>'شهر'],['word'=>'January','pronunciation'=>'/ˈdʒæn.ju.er.i/','meaning_ar'=>'يناير'],['word'=>'February','pronunciation'=>'/ˈfeb.ru.er.i/','meaning_ar'=>'فبراير'],['word'=>'March','pronunciation'=>'/mɑːrtʃ/','meaning_ar'=>'مارس'],['word'=>'birthday','pronunciation'=>'/ˈbɜːrθ.deɪ/','meaning_ar'=>'عيد ميلاد'],['word'=>'July','pronunciation'=>'/dʒuˈlaɪ/','meaning_ar'=>'يوليو'],['word'=>'October','pronunciation'=>'/ɒkˈtoʊ.bər/','meaning_ar'=>'أكتوبر'],['word'=>'format','pronunciation'=>'/ˈfɔːr.mæt/','meaning_ar'=>'صيغة'],['word'=>'American','pronunciation'=>'/əˈmer.ɪ.kən/','meaning_ar'=>'أمريكي']])],
    1162 => ['s1'=>'This is the eighth and final midterm. It covers imperative sentences, modal verbs, questions, comparisons, quantifiers, delexical verbs, there is and are, time, and dates.','s2'=>'You have covered the entire course content. Be proud of yourself!','s3'=>'One more step: the final comprehensive exam awaits you.','pe'=>'الاختبار النصفي الثامن — يغطي كل مواضيع المرحلة الرابعة.','se'=>'خطوة واحدة بعد: الاختبار النهائي الشامل ينتظرك.','v'=>json_encode([['word'=>'final','pronunciation'=>'/ˈfaɪ.nəl/','meaning_ar'=>'نهائي'],['word'=>'comprehensive','pronunciation'=>'/ˌkɒm.prɪˈhen.sɪv/','meaning_ar'=>'شامل'],['word'=>'awaits','pronunciation'=>'/əˈweɪts/','meaning_ar'=>'ينتظر'],['word'=>'entire','pronunciation'=>'/ɪnˈtaɪər/','meaning_ar'=>'كامل'],['word'=>'content','pronunciation'=>'/ˈkɒn.tent/','meaning_ar'=>'محتوى'],['word'=>'proud','pronunciation'=>'/praʊd/','meaning_ar'=>'فخور'],['word'=>'covered','pronunciation'=>'/ˈkʌv.ərd/','meaning_ar'=>'غطى'],['word'=>'step','pronunciation'=>'/step/','meaning_ar'=>'خطوة'],['word'=>'one','pronunciation'=>'/wʌn/','meaning_ar'=>'واحد'],['word'=>'more','pronunciation'=>'/mɔːr/','meaning_ar'=>'أكثر']])],
    1163 => ['s1'=>'Congratulations! This is the final exam. It covers everything from the alphabet to advanced grammar. You have learned over three thousand vocabulary words and mastered twelve tenses.','s2'=>'Take your time, believe in yourself, and do your absolute best.','s3'=>'You are now an English speaker. Be proud of how far you have come!','pe'=>'مبروك! هذا الاختبار النهائي — يغطي كل شيء من الأبجدية للقواعد المتقدمة. تعلمت أكثر من 3000 كلمة و12 زمن.','se'=>'أنت الآن متحدث إنجليزي — افتخر بالمشوار اللي قطعته!','v'=>json_encode([['word'=>'congratulations','pronunciation'=>'/kənˌɡrætʃ.uˈleɪ.ʃənz/','meaning_ar'=>'مبروك'],['word'=>'alphabet','pronunciation'=>'/ˈæl.fə.bet/','meaning_ar'=>'أبجدية'],['word'=>'advanced','pronunciation'=>'/ədˈvænst/','meaning_ar'=>'متقدم'],['word'=>'thousand','pronunciation'=>'/ˈθaʊ.zənd/','meaning_ar'=>'ألف'],['word'=>'mastered','pronunciation'=>'/ˈmæs.tərd/','meaning_ar'=>'أتقن'],['word'=>'absolute','pronunciation'=>'/ˈæb.sə.luːt/','meaning_ar'=>'مطلق'],['word'=>'speaker','pronunciation'=>'/ˈspiː.kər/','meaning_ar'=>'متحدث'],['word'=>'far','pronunciation'=>'/fɑːr/','meaning_ar'=>'بعيد'],['word'=>'come','pronunciation'=>'/kʌm/','meaning_ar'=>'جاء'],['word'=>'proud','pronunciation'=>'/praʊd/','meaning_ar'=>'فخور']])],
];

$created = 0; $updated = 0; $skipped = 0;
foreach ($data as $lid => $c) {
    $lesson = Lesson::find($lid);
    if (!$lesson) { echo "SKIP:{$lid}\n"; $skipped++; continue; }
    $lesson->update(['has_pronunciation_exercise' => true]);
    $ex = PronunciationExercise::where('lesson_id', $lid)->first();
    $d = ['lesson_id'=>$lid,'sentence_1'=>$c['s1'],'sentence_2'=>$c['s2'],'sentence_3'=>$c['s3'],
          'vocabulary_json'=>$c['v'],'passage_explanation'=>$c['pe'],
          'sentence_explanation'=>$c['se'],'passing_score'=>60,'max_duration_seconds'=>30,'allow_retake'=>true];
    if ($ex) { $ex->update($d); echo "UPD:{$lid}\n"; $updated++; }
    else { PronunciationExercise::create($d); echo "NEW:{$lid}\n"; $created++; }
}
echo "\n=== BATCH 11 (FINAL) DONE === C:{$created} U:{$updated} S:{$skipped}\n";
echo "ALL BATCHES COMPLETED! 🎉\n";
