<?php
// Batch 5: Lessons 872-882 (Subject + Verb Forms + Midterm 2)
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
use App\Models\PronunciationExercise;
use App\Models\Lesson;

$data = [
    872 => [
        's1' => 'The subject is the person or thing that does the action in a sentence. In the sentence the boy runs, the boy is the subject. The subject usually comes before the verb.',
        's2' => 'Every complete sentence must have a subject and a verb.',
        's3' => 'Finding the subject is the first step in understanding any sentence.',
        'pe' => 'الفاعل هو الشخص أو الشيء اللي يقوم بالفعل في الجملة. في the boy runs، الفاعل هو the boy.',
        'se' => 'إيجاد الفاعل هو أول خطوة لفهم أي جملة.',
        'v' => [
            ['word'=>'subject','pronunciation'=>'/ˈsʌb.dʒekt/','meaning_ar'=>'فاعل'],
            ['word'=>'person','pronunciation'=>'/ˈpɜːr.sən/','meaning_ar'=>'شخص'],
            ['word'=>'action','pronunciation'=>'/ˈæk.ʃən/','meaning_ar'=>'فعل / حركة'],
            ['word'=>'before','pronunciation'=>'/bɪˈfɔːr/','meaning_ar'=>'قبل'],
            ['word'=>'usually','pronunciation'=>'/ˈjuː.ʒu.ə.li/','meaning_ar'=>'عادةً'],
            ['word'=>'finding','pronunciation'=>'/ˈfaɪn.dɪŋ/','meaning_ar'=>'إيجاد'],
            ['word'=>'understanding','pronunciation'=>'/ˌʌn.dərˈstæn.dɪŋ/','meaning_ar'=>'فهم'],
            ['word'=>'complete','pronunciation'=>'/kəmˈpliːt/','meaning_ar'=>'كامل'],
            ['word'=>'first','pronunciation'=>'/fɜːrst/','meaning_ar'=>'أول'],
            ['word'=>'step','pronunciation'=>'/step/','meaning_ar'=>'خطوة'],
        ],
    ],
    873 => [
        's1' => 'A subject can be a noun, a pronoun, or even a phrase. I like coffee. The tall man speaks English. Swimming is good exercise.',
        's2' => 'Pronouns like he, she, and they are very common subjects.',
        's3' => 'Practice identifying the subject in every sentence you read.',
        'pe' => 'الفاعل ممكن يكون اسم أو ضمير أو حتى عبارة. مثل I, The tall man, Swimming.',
        'se' => 'تمرن على تحديد الفاعل في كل جملة تقرأها.',
        'v' => [
            ['word'=>'phrase','pronunciation'=>'/freɪz/','meaning_ar'=>'عبارة'],
            ['word'=>'coffee','pronunciation'=>'/ˈkɒf.i/','meaning_ar'=>'قهوة'],
            ['word'=>'swimming','pronunciation'=>'/ˈswɪm.ɪŋ/','meaning_ar'=>'سباحة'],
            ['word'=>'exercise','pronunciation'=>'/ˈek.sər.saɪz/','meaning_ar'=>'تمرين'],
            ['word'=>'speak','pronunciation'=>'/spiːk/','meaning_ar'=>'يتحدث'],
            ['word'=>'even','pronunciation'=>'/ˈiː.vən/','meaning_ar'=>'حتى'],
            ['word'=>'common','pronunciation'=>'/ˈkɒm.ən/','meaning_ar'=>'شائع'],
            ['word'=>'like','pronunciation'=>'/laɪk/','meaning_ar'=>'يحب'],
            ['word'=>'good','pronunciation'=>'/ɡʊd/','meaning_ar'=>'جيد'],
            ['word'=>'identify','pronunciation'=>'/aɪˈden.tɪ.faɪ/','meaning_ar'=>'يحدد'],
        ],
    ],
    874 => [
        's1' => 'Now practice finding the subject in different sentences. Ask yourself: who or what is doing the action? The answer is the subject.',
        's2' => 'The subject answers the question who or what before the verb.',
        's3' => 'Excellent work! You can now identify subjects with confidence.',
        'pe' => 'اسأل نفسك: مين أو إيه اللي يقوم بالفعل؟ الإجابة هي الفاعل.',
        'se' => 'عمل ممتاز! دلوقتي تقدر تحدد الفاعل بثقة.',
        'v' => [
            ['word'=>'different','pronunciation'=>'/ˈdɪf.ər.ənt/','meaning_ar'=>'مختلف'],
            ['word'=>'yourself','pronunciation'=>'/jɔːrˈself/','meaning_ar'=>'نفسك'],
            ['word'=>'doing','pronunciation'=>'/ˈduː.ɪŋ/','meaning_ar'=>'يفعل'],
            ['word'=>'answer','pronunciation'=>'/ˈæn.sər/','meaning_ar'=>'إجابة'],
            ['word'=>'excellent','pronunciation'=>'/ˈek.sə.lənt/','meaning_ar'=>'ممتاز'],
            ['word'=>'confidence','pronunciation'=>'/ˈkɒn.fɪ.dəns/','meaning_ar'=>'ثقة'],
            ['word'=>'ask','pronunciation'=>'/æsk/','meaning_ar'=>'يسأل'],
            ['word'=>'who','pronunciation'=>'/huː/','meaning_ar'=>'من'],
            ['word'=>'what','pronunciation'=>'/wɒt/','meaning_ar'=>'ماذا'],
            ['word'=>'work','pronunciation'=>'/wɜːrk/','meaning_ar'=>'عمل'],
        ],
    ],
    875 => [
        's1' => 'Verb conjugation means changing a verb to match the subject. I play, he plays, they play. The verb changes based on who is doing the action.',
        's2' => 'In English, the third person singular adds S to the verb.',
        's3' => 'She eats, he drinks, it works — all add S in present simple.',
        'pe' => 'تصريف الفعل يعني تغيير الفعل ليتوافق مع الفاعل. مثل I play بس he plays.',
        'se' => 'في المضارع البسيط، الشخص الثالث المفرد يضيف S للفعل.',
        'v' => [
            ['word'=>'conjugation','pronunciation'=>'/ˌkɒn.dʒəˈɡeɪ.ʃən/','meaning_ar'=>'تصريف'],
            ['word'=>'match','pronunciation'=>'/mætʃ/','meaning_ar'=>'يتوافق'],
            ['word'=>'play','pronunciation'=>'/pleɪ/','meaning_ar'=>'يلعب'],
            ['word'=>'based','pronunciation'=>'/beɪst/','meaning_ar'=>'بناءً على'],
            ['word'=>'third','pronunciation'=>'/θɜːrd/','meaning_ar'=>'ثالث'],
            ['word'=>'present','pronunciation'=>'/ˈprez.ənt/','meaning_ar'=>'مضارع / حالي'],
            ['word'=>'drink','pronunciation'=>'/drɪŋk/','meaning_ar'=>'يشرب'],
            ['word'=>'eat','pronunciation'=>'/iːt/','meaning_ar'=>'يأكل'],
            ['word'=>'change','pronunciation'=>'/tʃeɪndʒ/','meaning_ar'=>'يغير'],
            ['word'=>'person','pronunciation'=>'/ˈpɜːr.sən/','meaning_ar'=>'شخص'],
        ],
    ],
    876 => [
        's1' => 'The verb to be has special conjugations. I am, you are, he is, she is, it is, we are, they are. These forms are used every day.',
        's2' => 'Am, is, and are are the present tense forms of the verb to be.',
        's3' => 'I am happy. She is tall. They are students.',
        'pe' => 'فعل to be له تصريفات خاصة: I am, you are, he/she/it is, we/they are.',
        'se' => 'am, is, are هي صيغ المضارع لفعل to be.',
        'v' => [
            ['word'=>'am','pronunciation'=>'/æm/','meaning_ar'=>'أكون'],
            ['word'=>'is','pronunciation'=>'/ɪz/','meaning_ar'=>'يكون'],
            ['word'=>'are','pronunciation'=>'/ɑːr/','meaning_ar'=>'يكونون'],
            ['word'=>'was','pronunciation'=>'/wɒz/','meaning_ar'=>'كان'],
            ['word'=>'were','pronunciation'=>'/wɜːr/','meaning_ar'=>'كانوا'],
            ['word'=>'been','pronunciation'=>'/biːn/','meaning_ar'=>'كان (تصريف ثالث)'],
            ['word'=>'being','pronunciation'=>'/ˈbiː.ɪŋ/','meaning_ar'=>'يكون (مستمر)'],
            ['word'=>'tense','pronunciation'=>'/tens/','meaning_ar'=>'زمن'],
            ['word'=>'special','pronunciation'=>'/ˈspeʃ.əl/','meaning_ar'=>'خاص'],
            ['word'=>'daily','pronunciation'=>'/ˈdeɪ.li/','meaning_ar'=>'يومياً'],
        ],
    ],
    877 => [
        's1' => 'The verb to have also has special forms. I have, you have, he has, she has. In the past, we use had for all subjects.',
        's2' => 'Has is used only with he, she, and it in the present tense.',
        's3' => 'I have a book. She has two cats. They had a great time.',
        'pe' => 'فعل to have له صيغ خاصة: I/you/we/they have، بس he/she/it has.',
        'se' => 'has نستخدمها فقط مع he, she, it في المضارع.',
        'v' => [
            ['word'=>'have','pronunciation'=>'/hæv/','meaning_ar'=>'يملك'],
            ['word'=>'has','pronunciation'=>'/hæz/','meaning_ar'=>'يملك (للمفرد الغائب)'],
            ['word'=>'had','pronunciation'=>'/hæd/','meaning_ar'=>'كان يملك'],
            ['word'=>'own','pronunciation'=>'/oʊn/','meaning_ar'=>'يملك'],
            ['word'=>'belong','pronunciation'=>'/bɪˈlɒŋ/','meaning_ar'=>'ينتمي'],
            ['word'=>'possess','pronunciation'=>'/pəˈzes/','meaning_ar'=>'يمتلك'],
            ['word'=>'great','pronunciation'=>'/ɡreɪt/','meaning_ar'=>'رائع'],
            ['word'=>'time','pronunciation'=>'/taɪm/','meaning_ar'=>'وقت'],
            ['word'=>'only','pronunciation'=>'/ˈoʊn.li/','meaning_ar'=>'فقط'],
            ['word'=>'also','pronunciation'=>'/ˈɔːl.soʊ/','meaning_ar'=>'أيضاً'],
        ],
    ],
    878 => [
        's1' => 'The verb to do is used as a helping verb in questions and negatives. Do you like pizza? I do not understand. Does she speak Arabic?',
        's2' => 'Do is used with I, you, we, they. Does is used with he, she, it.',
        's3' => 'Did is the past tense of both do and does.',
        'pe' => 'فعل to do يُستخدم كفعل مساعد في الأسئلة والنفي. Do you like pizza? I do not understand.',
        'se' => 'did هي صيغة الماضي لـ do و does.',
        'v' => [
            ['word'=>'do','pronunciation'=>'/duː/','meaning_ar'=>'يفعل'],
            ['word'=>'does','pronunciation'=>'/dʌz/','meaning_ar'=>'يفعل (للمفرد الغائب)'],
            ['word'=>'did','pronunciation'=>'/dɪd/','meaning_ar'=>'فعل (ماضي)'],
            ['word'=>'helping','pronunciation'=>'/ˈhel.pɪŋ/','meaning_ar'=>'مساعد'],
            ['word'=>'negative','pronunciation'=>'/ˈneɡ.ə.tɪv/','meaning_ar'=>'نفي'],
            ['word'=>'question','pronunciation'=>'/ˈkwes.tʃən/','meaning_ar'=>'سؤال'],
            ['word'=>'pizza','pronunciation'=>'/ˈpiːt.sə/','meaning_ar'=>'بيتزا'],
            ['word'=>'understand','pronunciation'=>'/ˌʌn.dərˈstænd/','meaning_ar'=>'يفهم'],
            ['word'=>'Arabic','pronunciation'=>'/ˈær.ə.bɪk/','meaning_ar'=>'عربي'],
            ['word'=>'past','pronunciation'=>'/pæst/','meaning_ar'=>'ماضي'],
        ],
    ],
    879 => [
        's1' => 'Regular verbs form the past tense by adding ED. Walk becomes walked. Play becomes played. Talk becomes talked.',
        's2' => 'The ED ending has three different sounds: T, D, and ID.',
        's3' => 'Walked sounds like walkt. Played sounds like playd. Wanted sounds like want-id.',
        'pe' => 'الأفعال المنتظمة تكوّن الماضي بإضافة ED. مثل walked, played, talked.',
        'se' => 'نهاية ED لها 3 أصوات مختلفة: T (walked), D (played), ID (wanted).',
        'v' => [
            ['word'=>'walked','pronunciation'=>'/wɔːkt/','meaning_ar'=>'مشى'],
            ['word'=>'played','pronunciation'=>'/pleɪd/','meaning_ar'=>'لعب'],
            ['word'=>'talked','pronunciation'=>'/tɔːkt/','meaning_ar'=>'تكلم'],
            ['word'=>'wanted','pronunciation'=>'/ˈwɒn.tɪd/','meaning_ar'=>'أراد'],
            ['word'=>'regular','pronunciation'=>'/ˈreɡ.jə.lər/','meaning_ar'=>'منتظم'],
            ['word'=>'form','pronunciation'=>'/fɔːrm/','meaning_ar'=>'يشكّل'],
            ['word'=>'tense','pronunciation'=>'/tens/','meaning_ar'=>'زمن'],
            ['word'=>'adding','pronunciation'=>'/ˈæd.ɪŋ/','meaning_ar'=>'إضافة'],
            ['word'=>'different','pronunciation'=>'/ˈdɪf.ər.ənt/','meaning_ar'=>'مختلف'],
            ['word'=>'sound','pronunciation'=>'/saʊnd/','meaning_ar'=>'صوت'],
        ],
    ],
    880 => [
        's1' => 'Irregular verbs do not follow the ED rule. Go becomes went. See becomes saw. Eat becomes ate. You must memorize these forms.',
        's2' => 'There are about two hundred common irregular verbs in English.',
        's3' => 'Buy, bought. Think, thought. Write, wrote. Read these out loud.',
        'pe' => 'الأفعال الشاذة ما تتبع قاعدة ED. مثل go-went, see-saw, eat-ate. لازم تحفظها.',
        'se' => 'في حوالي 200 فعل شاذ شائع في الإنجليزي.',
        'v' => [
            ['word'=>'go','pronunciation'=>'/ɡoʊ/','meaning_ar'=>'يذهب'],
            ['word'=>'went','pronunciation'=>'/went/','meaning_ar'=>'ذهب'],
            ['word'=>'see','pronunciation'=>'/siː/','meaning_ar'=>'يرى'],
            ['word'=>'saw','pronunciation'=>'/sɔː/','meaning_ar'=>'رأى'],
            ['word'=>'eat','pronunciation'=>'/iːt/','meaning_ar'=>'يأكل'],
            ['word'=>'ate','pronunciation'=>'/eɪt/','meaning_ar'=>'أكل'],
            ['word'=>'buy','pronunciation'=>'/baɪ/','meaning_ar'=>'يشتري'],
            ['word'=>'bought','pronunciation'=>'/bɔːt/','meaning_ar'=>'اشترى'],
            ['word'=>'write','pronunciation'=>'/raɪt/','meaning_ar'=>'يكتب'],
            ['word'=>'wrote','pronunciation'=>'/roʊt/','meaning_ar'=>'كتب'],
        ],
    ],
    881 => [
        's1' => 'Now practice conjugating verbs with different subjects. I walk, she walks, they walked. I am, he is, we are. I have, she has, they had.',
        's2' => 'Mix regular and irregular verbs in your daily practice.',
        's3' => 'Consistent practice is the key to mastering verb forms.',
        'pe' => 'تمرن على تصريف الأفعال مع فاعلين مختلفين — أفعال منتظمة وشاذة.',
        'se' => 'التمرين المستمر هو مفتاح إتقان تصريف الأفعال.',
        'v' => [
            ['word'=>'conjugate','pronunciation'=>'/ˈkɒn.dʒə.ɡeɪt/','meaning_ar'=>'يصرّف'],
            ['word'=>'mix','pronunciation'=>'/mɪks/','meaning_ar'=>'يخلط'],
            ['word'=>'consistent','pronunciation'=>'/kənˈsɪs.tənt/','meaning_ar'=>'مستمر / ثابت'],
            ['word'=>'daily','pronunciation'=>'/ˈdeɪ.li/','meaning_ar'=>'يومي'],
            ['word'=>'master','pronunciation'=>'/ˈmæs.tər/','meaning_ar'=>'يتقن'],
            ['word'=>'walk','pronunciation'=>'/wɔːk/','meaning_ar'=>'يمشي'],
            ['word'=>'run','pronunciation'=>'/rʌn/','meaning_ar'=>'يجري'],
            ['word'=>'speak','pronunciation'=>'/spiːk/','meaning_ar'=>'يتحدث'],
            ['word'=>'write','pronunciation'=>'/raɪt/','meaning_ar'=>'يكتب'],
            ['word'=>'read','pronunciation'=>'/riːd/','meaning_ar'=>'يقرأ'],
        ],
    ],
    882 => [
        's1' => 'You have reached the second midterm exam. This test covers singular and plural forms, articles, subjects, and verb conjugation.',
        's2' => 'Review everything you learned in stage two before the exam.',
        's3' => 'Stay calm, take your time, and do your best. You are ready!',
        'pe' => 'وصلت للاختبار النصفي الثاني — يغطي المفرد والجمع وأدوات التعريف والفاعل وتصريف الأفعال.',
        'se' => 'خلك هادي وخذ وقتك واعمل أفضل ما عندك — أنت جاهز!',
        'v' => [
            ['word'=>'midterm','pronunciation'=>'/ˈmɪd.tɜːrm/','meaning_ar'=>'اختبار نصفي'],
            ['word'=>'calm','pronunciation'=>'/kɑːm/','meaning_ar'=>'هادئ'],
            ['word'=>'ready','pronunciation'=>'/ˈred.i/','meaning_ar'=>'جاهز'],
            ['word'=>'review','pronunciation'=>'/rɪˈvjuː/','meaning_ar'=>'يراجع'],
            ['word'=>'cover','pronunciation'=>'/ˈkʌv.ər/','meaning_ar'=>'يغطي'],
            ['word'=>'stage','pronunciation'=>'/steɪdʒ/','meaning_ar'=>'مرحلة'],
            ['word'=>'exam','pronunciation'=>'/ɪɡˈzæm/','meaning_ar'=>'اختبار'],
            ['word'=>'reach','pronunciation'=>'/riːtʃ/','meaning_ar'=>'يصل'],
            ['word'=>'best','pronunciation'=>'/best/','meaning_ar'=>'أفضل'],
            ['word'=>'learned','pronunciation'=>'/lɜːrnd/','meaning_ar'=>'تعلم'],
        ],
    ],
];

$created = 0; $updated = 0; $skipped = 0;
foreach ($data as $lid => $c) {
    $lesson = Lesson::find($lid);
    if (!$lesson) { echo "SKIP:{$lid}\n"; $skipped++; continue; }
    $lesson->update(['has_pronunciation_exercise' => true]);
    $ex = PronunciationExercise::where('lesson_id', $lid)->first();
    $d = ['lesson_id'=>$lid,'sentence_1'=>$c['s1'],'sentence_2'=>$c['s2'],'sentence_3'=>$c['s3'],
          'vocabulary_json'=>json_encode($c['v']),'passage_explanation'=>$c['pe'],
          'sentence_explanation'=>$c['se'],'passing_score'=>60,'max_duration_seconds'=>30,'allow_retake'=>true];
    if ($ex) { $ex->update($d); echo "UPD:{$lid}\n"; $updated++; }
    else { PronunciationExercise::create($d); echo "NEW:{$lid}\n"; $created++; }
}
echo "\n=== BATCH 5 DONE === C:{$created} U:{$updated} S:{$skipped}\n";
