<?php
// Batch 3: Lessons 838-882 (Second Intro + Prefix/Suffix + Punctuation + Singular/Plural + Articles + Subject + Verb Forms + Midterm 2)
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
use App\Models\PronunciationExercise;
use App\Models\Lesson;

$data = [
    838 => [
        'sentence_1' => 'Welcome to stage two of this course. You have completed the basics and now it is time to go deeper into English grammar.',
        'sentence_2' => 'Stage two builds on everything you learned in stage one.',
        'sentence_3' => 'Keep pushing forward and never give up.',
        'passage_explanation' => 'مرحباً بالمرحلة الثانية — خلصت الأساسيات ودلوقتي وقت نتعمق أكثر في القواعد.',
        'sentence_explanation' => 'كمّل للأمام ولا تستسلم أبداً.',
        'vocabulary_json' => json_encode([
            ['word' => 'stage', 'pronunciation' => '/steɪdʒ/', 'meaning_ar' => 'مرحلة'],
            ['word' => 'basics', 'pronunciation' => '/ˈbeɪ.sɪks/', 'meaning_ar' => 'أساسيات'],
            ['word' => 'deeper', 'pronunciation' => '/ˈdiː.pər/', 'meaning_ar' => 'أعمق'],
            ['word' => 'grammar', 'pronunciation' => '/ˈɡræm.ər/', 'meaning_ar' => 'قواعد'],
            ['word' => 'forward', 'pronunciation' => '/ˈfɔːr.wərd/', 'meaning_ar' => 'للأمام'],
            ['word' => 'push', 'pronunciation' => '/pʊʃ/', 'meaning_ar' => 'يدفع'],
            ['word' => 'never', 'pronunciation' => '/ˈnev.ər/', 'meaning_ar' => 'أبداً'],
            ['word' => 'give up', 'pronunciation' => '/ɡɪv ʌp/', 'meaning_ar' => 'يستسلم'],
            ['word' => 'everything', 'pronunciation' => '/ˈev.ri.θɪŋ/', 'meaning_ar' => 'كل شيء'],
            ['word' => 'build', 'pronunciation' => '/bɪld/', 'meaning_ar' => 'يبني'],
        ]),
    ],
    839 => [
        'sentence_1' => 'The curriculum for stage two includes prefixes, suffixes, punctuation, singular and plural forms, articles, subjects, and verb conjugation.',
        'sentence_2' => 'Follow the curriculum step by step for the best results.',
        'sentence_3' => 'Each lesson is designed to prepare you for the next one.',
        'passage_explanation' => 'المنهج يشمل البادئات واللاحقات وعلامات الترقيم والمفرد والجمع وأدوات التعريف والفاعل وتصريف الأفعال.',
        'sentence_explanation' => 'كل درس مصمم يجهزك للدرس اللي بعده.',
        'vocabulary_json' => json_encode([
            ['word' => 'curriculum', 'pronunciation' => '/kəˈrɪk.jə.ləm/', 'meaning_ar' => 'منهج'],
            ['word' => 'prefix', 'pronunciation' => '/ˈpriː.fɪks/', 'meaning_ar' => 'بادئة'],
            ['word' => 'suffix', 'pronunciation' => '/ˈsʌf.ɪks/', 'meaning_ar' => 'لاحقة'],
            ['word' => 'punctuation', 'pronunciation' => '/ˌpʌŋk.tʃuˈeɪ.ʃən/', 'meaning_ar' => 'علامات ترقيم'],
            ['word' => 'singular', 'pronunciation' => '/ˈsɪŋ.ɡjə.lər/', 'meaning_ar' => 'مفرد'],
            ['word' => 'plural', 'pronunciation' => '/ˈplʊr.əl/', 'meaning_ar' => 'جمع'],
            ['word' => 'article', 'pronunciation' => '/ˈɑːr.tɪ.kəl/', 'meaning_ar' => 'أداة تعريف'],
            ['word' => 'conjugation', 'pronunciation' => '/ˌkɒn.dʒəˈɡeɪ.ʃən/', 'meaning_ar' => 'تصريف'],
            ['word' => 'design', 'pronunciation' => '/dɪˈzaɪn/', 'meaning_ar' => 'يصمم'],
            ['word' => 'prepare', 'pronunciation' => '/prɪˈper/', 'meaning_ar' => 'يجهز'],
        ]),
    ],
    843 => [
        'sentence_1' => 'Prefixes and suffixes are small parts added to words to change their meaning. A prefix goes before the root word. A suffix goes after the root word.',
        'sentence_2' => 'Understanding prefixes and suffixes helps you guess the meaning of new words.',
        'sentence_3' => 'Word parts are the secret to expanding your vocabulary quickly.',
        'passage_explanation' => 'البادئات واللاحقات أجزاء صغيرة تضاف للكلمة عشان تغير معناها — البادئة قبل الجذر واللاحقة بعده.',
        'sentence_explanation' => 'أجزاء الكلمة هي السر في توسيع مفرداتك بسرعة.',
        'vocabulary_json' => json_encode([
            ['word' => 'prefix', 'pronunciation' => '/ˈpriː.fɪks/', 'meaning_ar' => 'بادئة'],
            ['word' => 'suffix', 'pronunciation' => '/ˈsʌf.ɪks/', 'meaning_ar' => 'لاحقة'],
            ['word' => 'root', 'pronunciation' => '/ruːt/', 'meaning_ar' => 'جذر'],
            ['word' => 'meaning', 'pronunciation' => '/ˈmiː.nɪŋ/', 'meaning_ar' => 'معنى'],
            ['word' => 'change', 'pronunciation' => '/tʃeɪndʒ/', 'meaning_ar' => 'يغير'],
            ['word' => 'added', 'pronunciation' => '/ˈæd.ɪd/', 'meaning_ar' => 'يُضاف'],
            ['word' => 'guess', 'pronunciation' => '/ɡes/', 'meaning_ar' => 'يخمن'],
            ['word' => 'secret', 'pronunciation' => '/ˈsiː.krɪt/', 'meaning_ar' => 'سر'],
            ['word' => 'expand', 'pronunciation' => '/ɪkˈspænd/', 'meaning_ar' => 'يوسع'],
            ['word' => 'vocabulary', 'pronunciation' => '/vəˈkæb.jə.ler.i/', 'meaning_ar' => 'مفردات'],
        ]),
    ],
    844 => [
        'sentence_1' => 'A prefix is added to the beginning of a word. Un means not, so unhappy means not happy. Re means again, so replay means play again.',
        'sentence_2' => 'The prefix dis changes agree into disagree, which means to not agree.',
        'sentence_3' => 'Learning common prefixes unlocks thousands of new words.',
        'passage_explanation' => 'البادئة تضاف لبداية الكلمة: un = مش (unhappy = مش سعيد)، re = مرة ثانية (replay = يعيد التشغيل).',
        'sentence_explanation' => 'تعلم البادئات الشائعة يفتحلك آلاف الكلمات الجديدة.',
        'vocabulary_json' => json_encode([
            ['word' => 'unhappy', 'pronunciation' => '/ʌnˈhæp.i/', 'meaning_ar' => 'غير سعيد'],
            ['word' => 'replay', 'pronunciation' => '/riːˈpleɪ/', 'meaning_ar' => 'إعادة تشغيل'],
            ['word' => 'disagree', 'pronunciation' => '/ˌdɪs.əˈɡriː/', 'meaning_ar' => 'لا يوافق'],
            ['word' => 'beginning', 'pronunciation' => '/bɪˈɡɪn.ɪŋ/', 'meaning_ar' => 'بداية'],
            ['word' => 'unlock', 'pronunciation' => '/ʌnˈlɒk/', 'meaning_ar' => 'يفتح'],
            ['word' => 'undo', 'pronunciation' => '/ʌnˈduː/', 'meaning_ar' => 'يتراجع'],
            ['word' => 'rewrite', 'pronunciation' => '/riːˈraɪt/', 'meaning_ar' => 'يعيد كتابة'],
            ['word' => 'unable', 'pronunciation' => '/ʌnˈeɪ.bəl/', 'meaning_ar' => 'غير قادر'],
            ['word' => 'invisible', 'pronunciation' => '/ɪnˈvɪz.ə.bəl/', 'meaning_ar' => 'غير مرئي'],
            ['word' => 'misunderstand', 'pronunciation' => '/ˌmɪs.ʌn.dəˈstænd/', 'meaning_ar' => 'يسيء الفهم'],
        ]),
    ],
    845 => [
        'sentence_1' => 'A suffix is added to the end of a word. Adding ful to beauty gives us beautiful. Adding ly to quick gives us quickly.',
        'sentence_2' => 'Suffixes can change a noun into an adjective or a verb into an adverb.',
        'sentence_3' => 'Practice adding suffixes to words you already know.',
        'passage_explanation' => 'اللاحقة تضاف لنهاية الكلمة: ful + beauty = beautiful، ly + quick = quickly.',
        'sentence_explanation' => 'تمرن على إضافة اللاحقات لكلمات تعرفها أصلاً.',
        'vocabulary_json' => json_encode([
            ['word' => 'beautiful', 'pronunciation' => '/ˈbjuː.tɪ.fəl/', 'meaning_ar' => 'جميل'],
            ['word' => 'quickly', 'pronunciation' => '/ˈkwɪk.li/', 'meaning_ar' => 'بسرعة'],
            ['word' => 'careful', 'pronunciation' => '/ˈker.fəl/', 'meaning_ar' => 'حريص'],
            ['word' => 'teacher', 'pronunciation' => '/ˈtiː.tʃər/', 'meaning_ar' => 'معلم'],
            ['word' => 'happiness', 'pronunciation' => '/ˈhæp.i.nəs/', 'meaning_ar' => 'سعادة'],
            ['word' => 'kindness', 'pronunciation' => '/ˈkaɪnd.nəs/', 'meaning_ar' => 'لطف'],
            ['word' => 'powerful', 'pronunciation' => '/ˈpaʊ.ər.fəl/', 'meaning_ar' => 'قوي'],
            ['word' => 'hopeless', 'pronunciation' => '/ˈhoʊp.ləs/', 'meaning_ar' => 'يائس'],
            ['word' => 'usable', 'pronunciation' => '/ˈjuː.zə.bəl/', 'meaning_ar' => 'قابل للاستخدام'],
            ['word' => 'player', 'pronunciation' => '/ˈpleɪ.ər/', 'meaning_ar' => 'لاعب'],
        ]),
    ],
    846 => [
        'sentence_1' => 'Some words have both a prefix and a suffix. Uncomfortable has the prefix un and the suffix able. Disagreement has dis and ment.',
        'sentence_2' => 'Breaking complex words into parts makes them much easier to understand.',
        'sentence_3' => 'You are becoming a word detective!',
        'passage_explanation' => 'بعض الكلمات فيها بادئة ولاحقة مع بعض — مثل uncomfortable (un + comfort + able).',
        'sentence_explanation' => 'أنت صرت محقق كلمات! تقسيم الكلمات لأجزاء يسهّل فهمها.',
        'vocabulary_json' => json_encode([
            ['word' => 'uncomfortable', 'pronunciation' => '/ʌnˈkʌm.fər.tə.bəl/', 'meaning_ar' => 'غير مريح'],
            ['word' => 'disagreement', 'pronunciation' => '/ˌdɪs.əˈɡriː.mənt/', 'meaning_ar' => 'خلاف'],
            ['word' => 'complex', 'pronunciation' => '/ˈkɒm.pleks/', 'meaning_ar' => 'معقد'],
            ['word' => 'detective', 'pronunciation' => '/dɪˈtek.tɪv/', 'meaning_ar' => 'محقق'],
            ['word' => 'impossible', 'pronunciation' => '/ɪmˈpɒs.ə.bəl/', 'meaning_ar' => 'مستحيل'],
            ['word' => 'unforgettable', 'pronunciation' => '/ˌʌn.fərˈɡet.ə.bəl/', 'meaning_ar' => 'لا يُنسى'],
            ['word' => 'replacement', 'pronunciation' => '/rɪˈpleɪs.mənt/', 'meaning_ar' => 'استبدال'],
            ['word' => 'unbelievable', 'pronunciation' => '/ˌʌn.bɪˈliː.və.bəl/', 'meaning_ar' => 'لا يُصدق'],
            ['word' => 'discomfort', 'pronunciation' => '/dɪsˈkʌm.fərt/', 'meaning_ar' => 'عدم ارتياح'],
            ['word' => 'enjoyment', 'pronunciation' => '/ɪnˈdʒɔɪ.mənt/', 'meaning_ar' => 'متعة'],
        ]),
    ],
    847 => [
        'sentence_1' => 'Test your knowledge of prefixes and suffixes. What does the word reusable mean? It means something that can be used again.',
        'sentence_2' => 'Can you identify the prefix and suffix in the word uncomfortable?',
        'sentence_3' => 'Great work! You understand how word parts change meaning.',
        'passage_explanation' => 'اختبر معرفتك — reusable معناها قابل للاستخدام مرة ثانية (re + use + able).',
        'sentence_explanation' => 'عمل رائع! فاهم كيف أجزاء الكلمة تغير المعنى.',
        'vocabulary_json' => json_encode([
            ['word' => 'knowledge', 'pronunciation' => '/ˈnɒl.ɪdʒ/', 'meaning_ar' => 'معرفة'],
            ['word' => 'reusable', 'pronunciation' => '/riːˈjuː.zə.bəl/', 'meaning_ar' => 'قابل لإعادة الاستخدام'],
            ['word' => 'identify', 'pronunciation' => '/aɪˈden.tɪ.faɪ/', 'meaning_ar' => 'يحدد'],
            ['word' => 'recyclable', 'pronunciation' => '/riːˈsaɪ.klə.bəl/', 'meaning_ar' => 'قابل لإعادة التدوير'],
            ['word' => 'helpful', 'pronunciation' => '/ˈhelp.fəl/', 'meaning_ar' => 'مفيد'],
            ['word' => 'careless', 'pronunciation' => '/ˈker.ləs/', 'meaning_ar' => 'مهمل'],
            ['word' => 'preview', 'pronunciation' => '/ˈpriː.vjuː/', 'meaning_ar' => 'معاينة'],
            ['word' => 'overdo', 'pronunciation' => '/ˌoʊ.vərˈduː/', 'meaning_ar' => 'يبالغ'],
            ['word' => 'rebuild', 'pronunciation' => '/riːˈbɪld/', 'meaning_ar' => 'يعيد بناء'],
            ['word' => 'meaningful', 'pronunciation' => '/ˈmiː.nɪŋ.fəl/', 'meaning_ar' => 'ذو معنى'],
        ]),
    ],
    848 => [
        'sentence_1' => 'Now answer the regular questions about prefixes and suffixes. Look at each word and decide which part is the prefix and which is the suffix.',
        'sentence_2' => 'Take your time and think carefully before choosing your answer.',
        'sentence_3' => 'You have learned a powerful skill that will help you forever.',
        'passage_explanation' => 'أجب على أسئلة البادئات واللاحقات — حدد البادئة واللاحقة في كل كلمة.',
        'sentence_explanation' => 'تعلمت مهارة قوية هتساعدك للأبد.',
        'vocabulary_json' => json_encode([
            ['word' => 'regular', 'pronunciation' => '/ˈreɡ.jə.lər/', 'meaning_ar' => 'عادي'],
            ['word' => 'decide', 'pronunciation' => '/dɪˈsaɪd/', 'meaning_ar' => 'يقرر'],
            ['word' => 'powerful', 'pronunciation' => '/ˈpaʊ.ər.fəl/', 'meaning_ar' => 'قوي'],
            ['word' => 'skill', 'pronunciation' => '/skɪl/', 'meaning_ar' => 'مهارة'],
            ['word' => 'forever', 'pronunciation' => '/fərˈev.ər/', 'meaning_ar' => 'للأبد'],
            ['word' => 'look', 'pronunciation' => '/lʊk/', 'meaning_ar' => 'ينظر'],
            ['word' => 'choose', 'pronunciation' => '/tʃuːz/', 'meaning_ar' => 'يختار'],
            ['word' => 'carefully', 'pronunciation' => '/ˈker.fə.li/', 'meaning_ar' => 'بعناية'],
            ['word' => 'learned', 'pronunciation' => '/lɜːrnd/', 'meaning_ar' => 'تعلم'],
            ['word' => 'answer', 'pronunciation' => '/ˈæn.sər/', 'meaning_ar' => 'إجابة'],
        ]),
    ],
    849 => [
        'sentence_1' => 'In English, we capitalize the first letter of a sentence, names, places, and days of the week. For example, Monday and Ahmed always start with a capital letter.',
        'sentence_2' => 'Always capitalize the word I, no matter where it appears in a sentence.',
        'sentence_3' => 'Capitalization rules are simple but very important in writing.',
        'passage_explanation' => 'في الإنجليزي نكبّر أول حرف في الجملة والأسماء والأماكن وأيام الأسبوع. مثل Monday و Ahmed.',
        'sentence_explanation' => 'قواعد الحرف الكبير بسيطة بس مهمة جداً في الكتابة.',
        'vocabulary_json' => json_encode([
            ['word' => 'capitalize', 'pronunciation' => '/ˈkæp.ɪ.tə.laɪz/', 'meaning_ar' => 'يكتب بحرف كبير'],
            ['word' => 'capital', 'pronunciation' => '/ˈkæp.ɪ.təl/', 'meaning_ar' => 'كبير / عاصمة'],
            ['word' => 'sentence', 'pronunciation' => '/ˈsen.təns/', 'meaning_ar' => 'جملة'],
            ['word' => 'name', 'pronunciation' => '/neɪm/', 'meaning_ar' => 'اسم'],
            ['word' => 'place', 'pronunciation' => '/pleɪs/', 'meaning_ar' => 'مكان'],
            ['word' => 'week', 'pronunciation' => '/wiːk/', 'meaning_ar' => 'أسبوع'],
            ['word' => 'Monday', 'pronunciation' => '/ˈmʌn.deɪ/', 'meaning_ar' => 'الاثنين'],
            ['word' => 'matter', 'pronunciation' => '/ˈmæt.ər/', 'meaning_ar' => 'يهم'],
            ['word' => 'appear', 'pronunciation' => '/əˈpɪr/', 'meaning_ar' => 'يظهر'],
            ['word' => 'writing', 'pronunciation' => '/ˈraɪ.tɪŋ/', 'meaning_ar' => 'كتابة'],
        ]),
    ],
    850 => [
        'sentence_1' => 'A full stop or period marks the end of a complete sentence. It tells the reader to pause. Every statement ends with a full stop.',
        'sentence_2' => 'I go to school every day. My teacher is kind. I love learning.',
        'sentence_3' => 'Without periods, reading would be very confusing.',
        'passage_explanation' => 'النقطة توضع في نهاية الجملة الكاملة — تخبر القارئ يتوقف. كل جملة خبرية تنتهي بنقطة.',
        'sentence_explanation' => 'بدون النقاط، القراءة بتكون مربكة جداً.',
        'vocabulary_json' => json_encode([
            ['word' => 'period', 'pronunciation' => '/ˈpɪr.i.əd/', 'meaning_ar' => 'نقطة'],
            ['word' => 'full stop', 'pronunciation' => '/fʊl stɒp/', 'meaning_ar' => 'نقطة'],
            ['word' => 'mark', 'pronunciation' => '/mɑːrk/', 'meaning_ar' => 'يحدد / علامة'],
            ['word' => 'complete', 'pronunciation' => '/kəmˈpliːt/', 'meaning_ar' => 'كامل'],
            ['word' => 'reader', 'pronunciation' => '/ˈriː.dər/', 'meaning_ar' => 'قارئ'],
            ['word' => 'pause', 'pronunciation' => '/pɔːz/', 'meaning_ar' => 'يتوقف'],
            ['word' => 'statement', 'pronunciation' => '/ˈsteɪt.mənt/', 'meaning_ar' => 'جملة خبرية'],
            ['word' => 'kind', 'pronunciation' => '/kaɪnd/', 'meaning_ar' => 'لطيف'],
            ['word' => 'confusing', 'pronunciation' => '/kənˈfjuː.zɪŋ/', 'meaning_ar' => 'مربك'],
            ['word' => 'love', 'pronunciation' => '/lʌv/', 'meaning_ar' => 'يحب'],
        ]),
    ],
    851 => [
        'sentence_1' => 'A question mark is used at the end of a question. What is your name? Where do you live? How old are you? These are all questions.',
        'sentence_2' => 'Every question in English must end with a question mark.',
        'sentence_3' => 'Questions help us learn new information and start conversations.',
        'passage_explanation' => 'علامة الاستفهام توضع في نهاية السؤال — مثل What is your name? و Where do you live?',
        'sentence_explanation' => 'الأسئلة تساعدنا نتعلم معلومات جديدة ونبدأ محادثات.',
        'vocabulary_json' => json_encode([
            ['word' => 'question mark', 'pronunciation' => '/ˈkwes.tʃən mɑːrk/', 'meaning_ar' => 'علامة استفهام'],
            ['word' => 'what', 'pronunciation' => '/wɒt/', 'meaning_ar' => 'ماذا'],
            ['word' => 'where', 'pronunciation' => '/wer/', 'meaning_ar' => 'أين'],
            ['word' => 'how', 'pronunciation' => '/haʊ/', 'meaning_ar' => 'كيف'],
            ['word' => 'live', 'pronunciation' => '/lɪv/', 'meaning_ar' => 'يعيش'],
            ['word' => 'age', 'pronunciation' => '/eɪdʒ/', 'meaning_ar' => 'عمر'],
            ['word' => 'information', 'pronunciation' => '/ˌɪn.fərˈmeɪ.ʃən/', 'meaning_ar' => 'معلومات'],
            ['word' => 'conversation', 'pronunciation' => '/ˌkɒn.vərˈseɪ.ʃən/', 'meaning_ar' => 'محادثة'],
            ['word' => 'who', 'pronunciation' => '/huː/', 'meaning_ar' => 'من'],
            ['word' => 'why', 'pronunciation' => '/waɪ/', 'meaning_ar' => 'لماذا'],
        ]),
    ],
    852 => [
        'sentence_1' => 'A comma creates a short pause in a sentence. We use commas in lists, after introductory words, and before conjunctions. I bought apples, bananas, and oranges.',
        'sentence_2' => 'However, you should not use too many commas in one sentence.',
        'sentence_3' => 'Commas help organize your thoughts and make sentences clearer.',
        'passage_explanation' => 'الفاصلة تعمل وقفة قصيرة — نستخدمها في القوائم وبعد كلمات المقدمة وقبل حروف العطف.',
        'sentence_explanation' => 'الفواصل تنظم أفكارك وتخلي الجمل أوضح.',
        'vocabulary_json' => json_encode([
            ['word' => 'comma', 'pronunciation' => '/ˈkɒm.ə/', 'meaning_ar' => 'فاصلة'],
            ['word' => 'pause', 'pronunciation' => '/pɔːz/', 'meaning_ar' => 'وقفة'],
            ['word' => 'list', 'pronunciation' => '/lɪst/', 'meaning_ar' => 'قائمة'],
            ['word' => 'introductory', 'pronunciation' => '/ˌɪn.trəˈdʌk.tər.i/', 'meaning_ar' => 'تمهيدي'],
            ['word' => 'bought', 'pronunciation' => '/bɔːt/', 'meaning_ar' => 'اشترى'],
            ['word' => 'banana', 'pronunciation' => '/bəˈnæn.ə/', 'meaning_ar' => 'موزة'],
            ['word' => 'however', 'pronunciation' => '/haʊˈev.ər/', 'meaning_ar' => 'ومع ذلك'],
            ['word' => 'organize', 'pronunciation' => '/ˈɔːr.ɡən.aɪz/', 'meaning_ar' => 'ينظم'],
            ['word' => 'thought', 'pronunciation' => '/θɔːt/', 'meaning_ar' => 'فكرة'],
            ['word' => 'clear', 'pronunciation' => '/klɪr/', 'meaning_ar' => 'واضح'],
        ]),
    ],
    853 => [
        'sentence_1' => 'An apostrophe shows ownership or marks a contraction. Sarah apostrophe s book means the book belongs to Sarah. Do not becomes don apostrophe t.',
        'sentence_2' => 'It is important to place the apostrophe in the correct position.',
        'sentence_3' => 'Apostrophes are small but they make a big difference in meaning.',
        'passage_explanation' => 'الفاصلة العلوية تدل على الملكية أو الاختصار — Sarah\'s book يعني كتاب سارة، don\'t يعني do not.',
        'sentence_explanation' => 'الفواصل العلوية صغيرة بس تعمل فرق كبير في المعنى.',
        'vocabulary_json' => json_encode([
            ['word' => 'apostrophe', 'pronunciation' => '/əˈpɒs.trə.fi/', 'meaning_ar' => 'فاصلة علوية'],
            ['word' => 'ownership', 'pronunciation' => '/ˈoʊ.nər.ʃɪp/', 'meaning_ar' => 'ملكية'],
            ['word' => 'contraction', 'pronunciation' => '/kənˈtræk.ʃən/', 'meaning_ar' => 'اختصار'],
            ['word' => 'belong', 'pronunciation' => '/bɪˈlɒŋ/', 'meaning_ar' => 'يخص / ينتمي'],
            ['word' => 'position', 'pronunciation' => '/pəˈzɪʃ.ən/', 'meaning_ar' => 'موقع'],
            ['word' => 'small', 'pronunciation' => '/smɔːl/', 'meaning_ar' => 'صغير'],
            ['word' => 'difference', 'pronunciation' => '/ˈdɪf.ər.əns/', 'meaning_ar' => 'فرق'],
            ['word' => 'important', 'pronunciation' => '/ɪmˈpɔːr.tənt/', 'meaning_ar' => 'مهم'],
            ['word' => 'correct', 'pronunciation' => '/kəˈrekt/', 'meaning_ar' => 'صحيح'],
            ['word' => 'mark', 'pronunciation' => '/mɑːrk/', 'meaning_ar' => 'يحدد / علامة'],
        ]),
    ],
    854 => [
        'sentence_1' => 'An exclamation mark shows strong emotion like surprise, excitement, or anger. What a beautiful day! Stop right there! I cannot believe it!',
        'sentence_2' => 'Do not overuse exclamation marks in formal writing.',
        'sentence_3' => 'One exclamation mark is enough to show strong feeling.',
        'passage_explanation' => 'علامة التعجب توضح عاطفة قوية مثل الدهشة أو الحماس أو الغضب.',
        'sentence_explanation' => 'علامة تعجب واحدة كافية لإظهار الشعور القوي.',
        'vocabulary_json' => json_encode([
            ['word' => 'exclamation', 'pronunciation' => '/ˌek.skləˈmeɪ.ʃən/', 'meaning_ar' => 'تعجب'],
            ['word' => 'surprise', 'pronunciation' => '/sərˈpraɪz/', 'meaning_ar' => 'مفاجأة'],
            ['word' => 'excitement', 'pronunciation' => '/ɪkˈsaɪt.mənt/', 'meaning_ar' => 'حماس'],
            ['word' => 'anger', 'pronunciation' => '/ˈæŋ.ɡər/', 'meaning_ar' => 'غضب'],
            ['word' => 'stop', 'pronunciation' => '/stɒp/', 'meaning_ar' => 'توقف'],
            ['word' => 'believe', 'pronunciation' => '/bɪˈliːv/', 'meaning_ar' => 'يصدق'],
            ['word' => 'overuse', 'pronunciation' => '/ˌoʊ.vərˈjuːz/', 'meaning_ar' => 'يفرط في الاستخدام'],
            ['word' => 'formal', 'pronunciation' => '/ˈfɔːr.məl/', 'meaning_ar' => 'رسمي'],
            ['word' => 'enough', 'pronunciation' => '/ɪˈnʌf/', 'meaning_ar' => 'كافي'],
            ['word' => 'feeling', 'pronunciation' => '/ˈfiː.lɪŋ/', 'meaning_ar' => 'شعور'],
        ]),
    ],
    855 => [
        'sentence_1' => 'A colon introduces a list, an explanation, or a quote. Here is what you need: a pen, a notebook, and an eraser.',
        'sentence_2' => 'The colon tells the reader that more information is coming.',
        'sentence_3' => 'Use a colon after a complete sentence to introduce what follows.',
        'passage_explanation' => 'النقطتان الرأسيتان تقدم قائمة أو شرح أو اقتباس — مثل Here is what you need: ...',
        'sentence_explanation' => 'استخدم النقطتين بعد جملة كاملة لتقديم ما يأتي بعدها.',
        'vocabulary_json' => json_encode([
            ['word' => 'colon', 'pronunciation' => '/ˈkoʊ.lən/', 'meaning_ar' => 'نقطتان رأسيتان'],
            ['word' => 'introduce', 'pronunciation' => '/ˌɪn.trəˈdjuːs/', 'meaning_ar' => 'يقدم'],
            ['word' => 'explanation', 'pronunciation' => '/ˌek.spləˈneɪ.ʃən/', 'meaning_ar' => 'شرح'],
            ['word' => 'quote', 'pronunciation' => '/kwoʊt/', 'meaning_ar' => 'اقتباس'],
            ['word' => 'notebook', 'pronunciation' => '/ˈnoʊt.bʊk/', 'meaning_ar' => 'دفتر'],
            ['word' => 'eraser', 'pronunciation' => '/ɪˈreɪ.zər/', 'meaning_ar' => 'ممحاة'],
            ['word' => 'follow', 'pronunciation' => '/ˈfɒl.oʊ/', 'meaning_ar' => 'يتبع'],
            ['word' => 'coming', 'pronunciation' => '/ˈkʌm.ɪŋ/', 'meaning_ar' => 'قادم'],
            ['word' => 'information', 'pronunciation' => '/ˌɪn.fərˈmeɪ.ʃən/', 'meaning_ar' => 'معلومات'],
            ['word' => 'complete', 'pronunciation' => '/kəmˈpliːt/', 'meaning_ar' => 'كامل'],
        ]),
    ],
    856 => [
        'sentence_1' => 'Now practice using all the punctuation marks you have learned. Write sentences with periods, question marks, exclamation marks, commas, apostrophes, and colons.',
        'sentence_2' => 'Good punctuation makes your writing professional and easy to read.',
        'sentence_3' => 'Keep practicing until punctuation becomes natural to you.',
        'passage_explanation' => 'تمرن على كل علامات الترقيم اللي تعلمتها — النقطة وعلامة الاستفهام والتعجب والفاصلة والفاصلة العلوية والنقطتين.',
        'sentence_explanation' => 'كمّل التمرين لحد ما علامات الترقيم تصير طبيعية عندك.',
        'vocabulary_json' => json_encode([
            ['word' => 'punctuation', 'pronunciation' => '/ˌpʌŋk.tʃuˈeɪ.ʃən/', 'meaning_ar' => 'علامات ترقيم'],
            ['word' => 'professional', 'pronunciation' => '/prəˈfeʃ.ən.əl/', 'meaning_ar' => 'احترافي'],
            ['word' => 'easy', 'pronunciation' => '/ˈiː.zi/', 'meaning_ar' => 'سهل'],
            ['word' => 'until', 'pronunciation' => '/ʌnˈtɪl/', 'meaning_ar' => 'حتى'],
            ['word' => 'become', 'pronunciation' => '/bɪˈkʌm/', 'meaning_ar' => 'يصبح'],
            ['word' => 'natural', 'pronunciation' => '/ˈnætʃ.ər.əl/', 'meaning_ar' => 'طبيعي'],
            ['word' => 'write', 'pronunciation' => '/raɪt/', 'meaning_ar' => 'يكتب'],
            ['word' => 'keep', 'pronunciation' => '/kiːp/', 'meaning_ar' => 'يستمر'],
            ['word' => 'practice', 'pronunciation' => '/ˈpræk.tɪs/', 'meaning_ar' => 'تمرين'],
            ['word' => 'learned', 'pronunciation' => '/lɜːrnd/', 'meaning_ar' => 'تعلم'],
        ]),
    ],
    857 => [
        'sentence_1' => 'Answer these regular questions about punctuation. Choose the correct punctuation mark for each sentence. Think about whether it is a statement, question, or exclamation.',
        'sentence_2' => 'Punctuation quiz time! Show what you have learned.',
        'sentence_3' => 'You are doing an amazing job so far!',
        'passage_explanation' => 'أجب على الأسئلة — اختر علامة الترقيم الصحيحة لكل جملة. فكر إذا كانت خبرية أو استفهامية أو تعجبية.',
        'sentence_explanation' => 'أنت تأدي عمل مذهل لحد الآن!',
        'vocabulary_json' => json_encode([
            ['word' => 'choose', 'pronunciation' => '/tʃuːz/', 'meaning_ar' => 'يختار'],
            ['word' => 'whether', 'pronunciation' => '/ˈweð.ər/', 'meaning_ar' => 'إذا'],
            ['word' => 'statement', 'pronunciation' => '/ˈsteɪt.mənt/', 'meaning_ar' => 'جملة خبرية'],
            ['word' => 'quiz', 'pronunciation' => '/kwɪz/', 'meaning_ar' => 'اختبار قصير'],
            ['word' => 'show', 'pronunciation' => '/ʃoʊ/', 'meaning_ar' => 'يُظهر'],
            ['word' => 'amazing', 'pronunciation' => '/əˈmeɪ.zɪŋ/', 'meaning_ar' => 'مذهل'],
            ['word' => 'far', 'pronunciation' => '/fɑːr/', 'meaning_ar' => 'بعيد'],
            ['word' => 'about', 'pronunciation' => '/əˈbaʊt/', 'meaning_ar' => 'عن'],
            ['word' => 'each', 'pronunciation' => '/iːtʃ/', 'meaning_ar' => 'كل'],
            ['word' => 'correct', 'pronunciation' => '/kəˈrekt/', 'meaning_ar' => 'صحيح'],
        ]),
    ],
];

$created = 0; $updated = 0; $skipped = 0;
foreach ($data as $lessonId => $content) {
    $lesson = Lesson::find($lessonId);
    if (!$lesson) { echo "SKIP: Lesson {$lessonId}\n"; $skipped++; continue; }
    $lesson->update(['has_pronunciation_exercise' => true]);
    $exercise = PronunciationExercise::where('lesson_id', $lessonId)->first();
    $d = [
        'lesson_id' => $lessonId, 'sentence_1' => $content['sentence_1'],
        'sentence_2' => $content['sentence_2'], 'sentence_3' => $content['sentence_3'],
        'vocabulary_json' => $content['vocabulary_json'],
        'passage_explanation' => $content['passage_explanation'],
        'sentence_explanation' => $content['sentence_explanation'],
        'passing_score' => 60, 'max_duration_seconds' => 30, 'allow_retake' => true,
    ];
    if ($exercise) { $exercise->update($d); echo "UPD: {$lessonId}\n"; $updated++; }
    else { PronunciationExercise::create($d); echo "NEW: {$lessonId}\n"; $created++; }
}
echo "\n=== BATCH 3 DONE === Created:{$created} Updated:{$updated} Skipped:{$skipped}\n";
