<?php
// Batch 9: Lessons 1008-1043 (Past Tenses + Midterm 6)
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
use App\Models\PronunciationExercise;
use App\Models\Lesson;

$data = [
    1008 => ['s1'=>'The past simple tense describes completed actions in the past. I visited my grandmother last week. She cooked a delicious meal yesterday.','s2'=>'Regular verbs add ED. Irregular verbs change their form completely.','s3'=>'He went to school. They ate lunch. We watched a movie last night.','pe'=>'الماضي البسيط يصف أفعال مكتملة في الماضي. الأفعال المنتظمة نضيف ED والشاذة تتغير.','se'=>'هو راح المدرسة. هم أكلوا غداء. إحنا شاهدنا فيلم الليلة الماضية.','v'=>json_encode([['word'=>'visited','pronunciation'=>'/ˈvɪz.ɪ.tɪd/','meaning_ar'=>'زار'],['word'=>'grandmother','pronunciation'=>'/ˈɡræn.mʌð.ər/','meaning_ar'=>'جدة'],['word'=>'cooked','pronunciation'=>'/kʊkt/','meaning_ar'=>'طبخ'],['word'=>'delicious','pronunciation'=>'/dɪˈlɪʃ.əs/','meaning_ar'=>'لذيذ'],['word'=>'meal','pronunciation'=>'/miːl/','meaning_ar'=>'وجبة'],['word'=>'went','pronunciation'=>'/went/','meaning_ar'=>'ذهب'],['word'=>'ate','pronunciation'=>'/eɪt/','meaning_ar'=>'أكل'],['word'=>'lunch','pronunciation'=>'/lʌntʃ/','meaning_ar'=>'غداء'],['word'=>'watched','pronunciation'=>'/wɒtʃt/','meaning_ar'=>'شاهد'],['word'=>'last','pronunciation'=>'/læst/','meaning_ar'=>'الماضي / آخر']])],
    1015 => ['s1'=>'The past continuous tense describes actions that were happening at a specific time in the past. I was sleeping at midnight. They were studying when the phone rang.','s2'=>'Form it with was or were plus the verb with ing.','s3'=>'She was reading a book while he was cooking dinner.','pe'=>'الماضي المستمر يصف أفعال كانت تحصل في وقت محدد في الماضي. نكونه بـ was/were + verb+ing.','se'=>'هي كانت تقرأ كتاب بينما هو كان يطبخ عشاء.','v'=>json_encode([['word'=>'sleeping','pronunciation'=>'/ˈsliː.pɪŋ/','meaning_ar'=>'ينام'],['word'=>'midnight','pronunciation'=>'/ˈmɪd.naɪt/','meaning_ar'=>'منتصف الليل'],['word'=>'rang','pronunciation'=>'/ræŋ/','meaning_ar'=>'رنّ'],['word'=>'reading','pronunciation'=>'/ˈriː.dɪŋ/','meaning_ar'=>'يقرأ'],['word'=>'while','pronunciation'=>'/waɪl/','meaning_ar'=>'بينما'],['word'=>'specific','pronunciation'=>'/spəˈsɪf.ɪk/','meaning_ar'=>'محدد'],['word'=>'was','pronunciation'=>'/wɒz/','meaning_ar'=>'كان'],['word'=>'were','pronunciation'=>'/wɜːr/','meaning_ar'=>'كانوا'],['word'=>'happened','pronunciation'=>'/ˈhæp.ənd/','meaning_ar'=>'حصل'],['word'=>'during','pronunciation'=>'/ˈdjʊr.ɪŋ/','meaning_ar'=>'خلال']])],
    1022 => ['s1'=>'The past perfect tense describes an action completed before another past action. I had eaten before she arrived. They had left when I called them.','s2'=>'Form it with had plus the past participle of the verb.','s3'=>'She had already studied the lesson before the teacher explained it.','pe'=>'الماضي التام يصف فعل اكتمل قبل فعل ماضي ثاني. نكونه بـ had + التصريف الثالث.','se'=>'هي كانت درست الدرس بالفعل قبل ما المعلم يشرحه.','v'=>json_encode([['word'=>'eaten','pronunciation'=>'/ˈiː.tən/','meaning_ar'=>'أكل (تصريف ثالث)'],['word'=>'arrived','pronunciation'=>'/əˈraɪvd/','meaning_ar'=>'وصل'],['word'=>'left','pronunciation'=>'/left/','meaning_ar'=>'غادر'],['word'=>'called','pronunciation'=>'/kɔːld/','meaning_ar'=>'اتصل'],['word'=>'already','pronunciation'=>'/ɔːlˈred.i/','meaning_ar'=>'بالفعل'],['word'=>'explained','pronunciation'=>'/ɪkˈspleɪnd/','meaning_ar'=>'شرح'],['word'=>'completed','pronunciation'=>'/kəmˈpliː.tɪd/','meaning_ar'=>'مكتمل'],['word'=>'before','pronunciation'=>'/bɪˈfɔːr/','meaning_ar'=>'قبل'],['word'=>'another','pronunciation'=>'/əˈnʌð.ər/','meaning_ar'=>'آخر'],['word'=>'had','pronunciation'=>'/hæd/','meaning_ar'=>'كان قد']])],
    1030 => ['s1'=>'The past perfect continuous shows an action that had been happening for a duration before another past event. I had been waiting for two hours before the bus came.','s2'=>'Form it with had been plus the verb with ing ending.','s3'=>'She had been working at the company for ten years before she retired.','pe'=>'الماضي التام المستمر يوضح فعل كان مستمر لمدة قبل حدث ماضي. نكونه بـ had been + verb+ing.','se'=>'هي كانت تشتغل في الشركة 10 سنين قبل ما تتقاعد.','v'=>json_encode([['word'=>'waiting','pronunciation'=>'/ˈweɪ.tɪŋ/','meaning_ar'=>'ينتظر'],['word'=>'duration','pronunciation'=>'/djʊˈreɪ.ʃən/','meaning_ar'=>'مدة'],['word'=>'event','pronunciation'=>'/ɪˈvent/','meaning_ar'=>'حدث'],['word'=>'company','pronunciation'=>'/ˈkʌm.pə.ni/','meaning_ar'=>'شركة'],['word'=>'retired','pronunciation'=>'/rɪˈtaɪərd/','meaning_ar'=>'تقاعد'],['word'=>'years','pronunciation'=>'/jɪrz/','meaning_ar'=>'سنوات'],['word'=>'came','pronunciation'=>'/keɪm/','meaning_ar'=>'جاء'],['word'=>'before','pronunciation'=>'/bɪˈfɔːr/','meaning_ar'=>'قبل'],['word'=>'working','pronunciation'=>'/ˈwɜːr.kɪŋ/','meaning_ar'=>'يشتغل'],['word'=>'bus','pronunciation'=>'/bʌs/','meaning_ar'=>'حافلة']])],
    1043 => ['s1'=>'This is the sixth midterm covering all four past tenses. You now understand simple, continuous, perfect, and perfect continuous in the past.','s2'=>'Compare the past tenses to see which one fits each situation.','s3'=>'You are more than halfway through the course. Amazing progress!','pe'=>'الاختبار النصفي السادس — يغطي الأزمنة الماضية الأربعة.','se'=>'أنت أكثر من نصف الطريق في الكورس — تقدم مذهل!','v'=>json_encode([['word'=>'compare','pronunciation'=>'/kəmˈper/','meaning_ar'=>'يقارن'],['word'=>'situation','pronunciation'=>'/ˌsɪtʃ.uˈeɪ.ʃən/','meaning_ar'=>'موقف'],['word'=>'fits','pronunciation'=>'/fɪts/','meaning_ar'=>'يناسب'],['word'=>'past','pronunciation'=>'/pæst/','meaning_ar'=>'ماضي'],['word'=>'amazing','pronunciation'=>'/əˈmeɪ.zɪŋ/','meaning_ar'=>'مذهل'],['word'=>'more','pronunciation'=>'/mɔːr/','meaning_ar'=>'أكثر'],['word'=>'halfway','pronunciation'=>'/ˌhæfˈweɪ/','meaning_ar'=>'نصف الطريق'],['word'=>'through','pronunciation'=>'/θruː/','meaning_ar'=>'خلال'],['word'=>'understand','pronunciation'=>'/ˌʌn.dərˈstænd/','meaning_ar'=>'يفهم'],['word'=>'progress','pronunciation'=>'/ˈprɒɡ.res/','meaning_ar'=>'تقدم']])],
];

$created = 0; $updated = 0; $skipped = 0;
foreach ($data as $lid => $c) {
    $lesson = Lesson::find($lid);
    if (!$lesson) { echo "SKIP:{$lid}\n"; $skipped++; continue; }
    $lesson->update(['has_pronunciation_exercise' => true]);
    $ex = PronunciationExercise::where('lesson_id', $lid)->first();
    $d = ['lesson_id'=>$lid,'sentence_1'=>$c['s1'],'sentence_2'=>$c['s2'],'sentence_3'=>$c['s3'],
          'vocabulary_json'=>$c['v'],'passage_explanation'=>$c['pe'],
          'sentence_explanation'=>$c['se'],'passing_score'=>60,'max_duration_seconds'=>30,'allow_retake'=>true];
    if ($ex) { $ex->update($d); echo "UPD:{$lid}\n"; $updated++; }
    else { PronunciationExercise::create($d); echo "NEW:{$lid}\n"; $created++; }
}
echo "\n=== BATCH 9 DONE === C:{$created} U:{$updated} S:{$skipped}\n";
