<?php
// Batch 10: Lessons 1044-1084 (Fourth Intro + Future Tenses + Midterm 7)
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
use App\Models\PronunciationExercise;
use App\Models\Lesson;

$data = [
    1044 => ['s1'=>'Welcome to stage four, the final stage of this course. You will learn future tenses, imperative sentences, modal verbs, questions, comparisons, and more.','s2'=>'This stage will prepare you for real-world English conversations.','s3'=>'You have come so far. The finish line is in sight!','pe'=>'مرحباً بالمرحلة الرابعة — المرحلة الأخيرة! هتتعلم الأزمنة المستقبلية والأمر والأفعال المساعدة والمقارنات.','se'=>'جيت من بعيد — خط النهاية باين!','v'=>json_encode([['word'=>'final','pronunciation'=>'/ˈfaɪ.nəl/','meaning_ar'=>'أخير'],['word'=>'future','pronunciation'=>'/ˈfjuː.tʃər/','meaning_ar'=>'مستقبل'],['word'=>'imperative','pronunciation'=>'/ɪmˈper.ə.tɪv/','meaning_ar'=>'أمر'],['word'=>'modal','pronunciation'=>'/ˈmoʊ.dəl/','meaning_ar'=>'مساعد (أفعال)'],['word'=>'comparison','pronunciation'=>'/kəmˈpær.ɪ.sən/','meaning_ar'=>'مقارنة'],['word'=>'conversation','pronunciation'=>'/ˌkɒn.vərˈseɪ.ʃən/','meaning_ar'=>'محادثة'],['word'=>'prepare','pronunciation'=>'/prɪˈper/','meaning_ar'=>'يجهز'],['word'=>'real-world','pronunciation'=>'/rɪəl wɜːrld/','meaning_ar'=>'العالم الحقيقي'],['word'=>'finish','pronunciation'=>'/ˈfɪn.ɪʃ/','meaning_ar'=>'ينهي'],['word'=>'sight','pronunciation'=>'/saɪt/','meaning_ar'=>'مرأى']])],
    1048 => ['s1'=>'The future simple tense uses will plus the base verb to talk about decisions, promises, and predictions. I will help you. She will call you tomorrow. It will rain tonight.','s2'=>'Will is the same for all subjects: I will, you will, he will, they will.','s3'=>'I will study harder next semester. They will arrive at noon.','pe'=>'المستقبل البسيط يستخدم will + الفعل الأساسي للقرارات والوعود والتوقعات.','se'=>'هدرس أكثر الترم الجاي. هم بيوصلون الظهر.','v'=>json_encode([['word'=>'will','pronunciation'=>'/wɪl/','meaning_ar'=>'سوف'],['word'=>'promise','pronunciation'=>'/ˈprɒm.ɪs/','meaning_ar'=>'وعد'],['word'=>'prediction','pronunciation'=>'/prɪˈdɪk.ʃən/','meaning_ar'=>'توقع'],['word'=>'decision','pronunciation'=>'/dɪˈsɪʒ.ən/','meaning_ar'=>'قرار'],['word'=>'tonight','pronunciation'=>'/təˈnaɪt/','meaning_ar'=>'الليلة'],['word'=>'harder','pronunciation'=>'/ˈhɑːr.dər/','meaning_ar'=>'أصعب'],['word'=>'semester','pronunciation'=>'/sɪˈmes.tər/','meaning_ar'=>'فصل دراسي'],['word'=>'arrive','pronunciation'=>'/əˈraɪv/','meaning_ar'=>'يصل'],['word'=>'noon','pronunciation'=>'/nuːn/','meaning_ar'=>'ظهر'],['word'=>'call','pronunciation'=>'/kɔːl/','meaning_ar'=>'يتصل']])],
    1055 => ['s1'=>'The future continuous tense describes actions that will be in progress at a specific time in the future. At eight o\'clock tomorrow, I will be sleeping. This time next week, she will be flying to Paris.','s2'=>'Form it with will be plus the verb with ing ending.','s3'=>'They will be waiting for us at the airport when we arrive.','pe'=>'المستقبل المستمر يصف أفعال بتكون مستمرة في وقت محدد في المستقبل. نكونه بـ will be + verb+ing.','se'=>'هم بيكونون ينتظرونا في المطار لما نوصل.','v'=>json_encode([['word'=>'progress','pronunciation'=>'/ˈprɒɡ.res/','meaning_ar'=>'تقدم'],['word'=>'sleeping','pronunciation'=>'/ˈsliː.pɪŋ/','meaning_ar'=>'ينام'],['word'=>'flying','pronunciation'=>'/ˈflaɪ.ɪŋ/','meaning_ar'=>'يطير'],['word'=>'Paris','pronunciation'=>'/ˈpær.ɪs/','meaning_ar'=>'باريس'],['word'=>'airport','pronunciation'=>'/ˈer.pɔːrt/','meaning_ar'=>'مطار'],['word'=>'waiting','pronunciation'=>'/ˈweɪ.tɪŋ/','meaning_ar'=>'ينتظر'],['word'=>'o\'clock','pronunciation'=>'/əˈklɒk/','meaning_ar'=>'الساعة'],['word'=>'arrive','pronunciation'=>'/əˈraɪv/','meaning_ar'=>'يصل'],['word'=>'tomorrow','pronunciation'=>'/təˈmɒr.oʊ/','meaning_ar'=>'بكرة'],['word'=>'week','pronunciation'=>'/wiːk/','meaning_ar'=>'أسبوع']])],
    1062 => ['s1'=>'The future perfect tense describes an action that will be completed before a certain time in the future. By next year, I will have graduated from university.','s2'=>'Form it with will have plus the past participle.','s3'=>'She will have finished the book by tonight. They will have left by the time we arrive.','pe'=>'المستقبل التام يصف فعل بيكون مكتمل قبل وقت معين في المستقبل. نكونه بـ will have + التصريف الثالث.','se'=>'هي بتكون خلصت الكتاب الليلة. هم بيكونون مشوا قبل ما نوصل.','v'=>json_encode([['word'=>'graduated','pronunciation'=>'/ˈɡrædʒ.u.eɪ.tɪd/','meaning_ar'=>'تخرج'],['word'=>'university','pronunciation'=>'/ˌjuː.nɪˈvɜːr.sə.ti/','meaning_ar'=>'جامعة'],['word'=>'certain','pronunciation'=>'/ˈsɜːr.tən/','meaning_ar'=>'معين'],['word'=>'completed','pronunciation'=>'/kəmˈpliː.tɪd/','meaning_ar'=>'مكتمل'],['word'=>'finished','pronunciation'=>'/ˈfɪn.ɪʃt/','meaning_ar'=>'أنهى'],['word'=>'tonight','pronunciation'=>'/təˈnaɪt/','meaning_ar'=>'الليلة'],['word'=>'left','pronunciation'=>'/left/','meaning_ar'=>'غادر'],['word'=>'time','pronunciation'=>'/taɪm/','meaning_ar'=>'وقت'],['word'=>'next','pronunciation'=>'/nekst/','meaning_ar'=>'القادم'],['word'=>'year','pronunciation'=>'/jɪr/','meaning_ar'=>'سنة']])],
    1070 => ['s1'=>'The future perfect continuous shows an action that will have been going on for a duration by a future time. By December, I will have been learning English for one year.','s2'=>'Form it with will have been plus the verb with ing.','s3'=>'By next month, she will have been working here for five years.','pe'=>'المستقبل التام المستمر يوضح فعل بيكون مستمر لمدة في وقت مستقبلي. نكونه بـ will have been + verb+ing.','se'=>'الشهر الجاي، هي بتكون اشتغلت هنا 5 سنين.','v'=>json_encode([['word'=>'December','pronunciation'=>'/dɪˈsem.bər/','meaning_ar'=>'ديسمبر'],['word'=>'learning','pronunciation'=>'/ˈlɜːr.nɪŋ/','meaning_ar'=>'تعلم'],['word'=>'month','pronunciation'=>'/mʌnθ/','meaning_ar'=>'شهر'],['word'=>'going on','pronunciation'=>'/ˈɡoʊ.ɪŋ ɒn/','meaning_ar'=>'مستمر'],['word'=>'duration','pronunciation'=>'/djʊˈreɪ.ʃən/','meaning_ar'=>'مدة'],['word'=>'future','pronunciation'=>'/ˈfjuː.tʃər/','meaning_ar'=>'مستقبل'],['word'=>'working','pronunciation'=>'/ˈwɜːr.kɪŋ/','meaning_ar'=>'يشتغل'],['word'=>'here','pronunciation'=>'/hɪr/','meaning_ar'=>'هنا'],['word'=>'five','pronunciation'=>'/faɪv/','meaning_ar'=>'خمسة'],['word'=>'year','pronunciation'=>'/jɪr/','meaning_ar'=>'سنة']])],
    1084 => ['s1'=>'This is the seventh midterm. It covers all four future tenses: simple, continuous, perfect, and perfect continuous. You are almost at the end!','s2'=>'Compare all twelve tenses you have learned throughout this course.','s3'=>'You have made remarkable progress. The final exam is near!','pe'=>'الاختبار النصفي السابع — يغطي الأزمنة المستقبلية الأربعة. أنت تقريباً عند النهاية!','se'=>'تقدمت تقدم ملحوظ — الاختبار النهائي قريب!','v'=>json_encode([['word'=>'almost','pronunciation'=>'/ˈɔːl.moʊst/','meaning_ar'=>'تقريباً'],['word'=>'twelve','pronunciation'=>'/twelv/','meaning_ar'=>'اثنا عشر'],['word'=>'throughout','pronunciation'=>'/θruːˈaʊt/','meaning_ar'=>'طوال'],['word'=>'remarkable','pronunciation'=>'/rɪˈmɑːr.kə.bəl/','meaning_ar'=>'ملحوظ'],['word'=>'near','pronunciation'=>'/nɪr/','meaning_ar'=>'قريب'],['word'=>'final','pronunciation'=>'/ˈfaɪ.nəl/','meaning_ar'=>'نهائي'],['word'=>'end','pronunciation'=>'/end/','meaning_ar'=>'نهاية'],['word'=>'compare','pronunciation'=>'/kəmˈper/','meaning_ar'=>'يقارن'],['word'=>'tense','pronunciation'=>'/tens/','meaning_ar'=>'زمن'],['word'=>'course','pronunciation'=>'/kɔːrs/','meaning_ar'=>'دورة']])],
];

$created = 0; $updated = 0; $skipped = 0;
foreach ($data as $lid => $c) {
    $lesson = Lesson::find($lid);
    if (!$lesson) { echo "SKIP:{$lid}\n"; $skipped++; continue; }
    $lesson->update(['has_pronunciation_exercise' => true]);
    $ex = PronunciationExercise::where('lesson_id', $lid)->first();
    $d = ['lesson_id'=>$lid,'sentence_1'=>$c['s1'],'sentence_2'=>$c['s2'],'sentence_3'=>$c['s3'],
          'vocabulary_json'=>$c['v'],'passage_explanation'=>$c['pe'],
          'sentence_explanation'=>$c['se'],'passing_score'=>60,'max_duration_seconds'=>30,'allow_retake'=>true];
    if ($ex) { $ex->update($d); echo "UPD:{$lid}\n"; $updated++; }
    else { PronunciationExercise::create($d); echo "NEW:{$lid}\n"; $created++; }
}
echo "\n=== BATCH 10 DONE === C:{$created} U:{$updated} S:{$skipped}\n";
